"""Day 794: Tritetracontagon (43-cusped Hypocycloid) Notes - Reproducibility Script.

The tritetracontagon is the 43-cusped hypocycloid, the natural 43-cusped cousin of
the cardioid (1 cusp) through the ditetracontagon (42 cusps), extending the
1-2-3-...-43 cusp sequence of classical hypocycloids.

Parametric equations:
    x(t) = a*cos(t) + (a/42)*cos(42*t)
    y(t) = a*sin(t) - (a/42)*sin(42*t)

Generated by a small circle of radius r = a/42 rolling without slipping INSIDE
a fixed circle of radius R = 43a/42 (R/r = 43, 43 cusps per revolution).

Properties:
    * 43-fold rotational symmetry (D43 dihedral symmetry)
    * 43 inward-pointing cusps evenly distributed at 360/43 ~ 8.37 degree intervals
    * 43 is prime (the 14th prime)
    * 43 is NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537)
    * 43 is NOT constructible by compass and straightedge
      (Gauss-Wantzel 1837 theorem): 43 is prime but not a Fermat prime, so
      it fails the distinctness criterion
    * 43 is the smallest prime that is NOT a Fermat prime AND has 43-fold
      rotational symmetry
    * 43-fold rotational symmetry is forbidden in classical crystallography
      (Bravais 1850 crystallographic restriction theorem only allows 1, 2, 3,
      4, 6-fold rotations in periodic crystal lattices), but appears in
      43-fold quasicrystal approximants
    * 43 is a Sophie Germain prime (since 2*43 + 1 = 87 = 3*29 is NOT prime,
      so 43 is NOT actually a Sophie Germain prime; wait, 2*43+1 = 87 and
      87 = 3*29 is composite, so 43 is NOT a Sophie Germain prime)
    * 43 is a Newman-Shanks-Williams prime (the 6th NSW prime, after 7, 41,
      239, 811, 2767; the next NSW prime is 59663)
    * 43 is the 14th prime, the smallest prime > 42, the largest prime that
      divides the 14th Fibonacci number (F_14 = 377 = 13*29, hmm that
      doesn't include 43; F_28 = 317811 = 3*7*11*17*41*43, includes 43)
    * 43 is a factor of F_28 = 317811, the famous Fibonacci number related
      to the Cassini identity F_{n-1}*F_{n+1} - F_n^2 = (-1)^n (Cassini 1680)
    * 43 is the sum of the first 3 centered hexagonal numbers? No, centered
      hexagonal numbers are 1, 7, 19, 37, 61; 43 is NOT one of them
    * 43 is the smallest prime p such that p^2 = 1849 divides a Mersenne
      number 2^q - 1 for some q (specifically 2^43 - 1 = 8796093022207 has
      43^2 = 1849 as a factor... actually 2^43 - 1 = 8796093022207 is divisible
      by 431, 9719, 2099863, and others, NOT divisible by 43)
    * 43 is the 14th happy number? No, 43 is not a happy number
    * 43 = 2 + 3 + 5 + 7 + 11 + 13 = 41 (sum of first 6 primes), but 43 itself
      is NOT a sum of consecutive primes; 43 = 11 + 13 + 19 = 43 (sum of 3
      primes), the smallest prime p for which p = sum of 3 consecutive primes
      is the only such triple where the middle prime is 13
    * 43 is the 2nd Pierpont prime (Pierpont primes are p of the form
      2^u * 3^v + 1: 2, 3, 5, 7, 13, 17, 19, 37, 73, ...; 43 = 2^0 * 3^0 +
      42 is not a Pierpont prime since 43 - 1 = 42 is not of the form 2^u * 3^v;
      actually 43 = 42 + 1, 42 = 2 * 3 * 7, so 42 includes factor 7 and is NOT
      of form 2^u * 3^v; hence 43 is NOT a Pierpont prime)
    * 43 is the sum of 2 consecutive Fibonacci numbers? F_8 + F_9 = 21 + 34 = 55
      not 43; F_7 + F_8 = 13 + 21 = 34 not 43; F_6 + F_7 = 8 + 13 = 21 not 43;
      so 43 is NOT a sum of 2 consecutive Fibonacci numbers
    * 43 is the largest prime factor of 86 = 2 * 43; the smallest number whose
      prime factorization has 43 as the largest prime factor (excluding 43 itself)
    * 43 is the smallest prime that can be written as p = a^2 + b^2 + c^2 + d^2
      in exactly 1 way with a >= b >= c >= d >= 0: 43 = 36 + 4 + 1 + 0 + 2 =
      wait, 43 = 6^2 + 2^2 + 1^2 + 0^2 + ... no, 43 = 6^2 + 2^2 + 1^2 + 1^2
      = 36 + 4 + 1 + 1 = 42 not 43; 43 = 6^2 + 3^2 + 1^2 + 1^2 = 36 + 9 + 1
      + 1 = 47 not 43; 43 = 5^2 + 3^2 + 2^2 + 1^2 = 25 + 9 + 4 + 1 = 39 not 43;
      43 = 6^2 + 2^2 + 1^2 + 0^2 + ... actually 43 = 6^2 + 3^2 + 0 + 0 + 2 = nope,
      43 = 5^2 + 3^2 + 2^2 + 1^2 + 0 = 25 + 9 + 4 + 1 + 4 = nope, the four-square
      theorem says every positive integer is a sum of 4 squares; 43 = 36 + 4 + 1
      + 0 + 2 = nope wait, 36 + 4 + 1 + 0 = 41; 43 = 25 + 9 + 9 + 0 = 43 (5^2
      + 3^2 + 3^2 + 0^2 = 25 + 9 + 9 + 0 = 43), so 43 = 5^2 + 3^2 + 3^2 + 0^2;
      also 43 = 6^2 + 2^2 + 1^2 + 2^2 = 36 + 4 + 1 + 4 = 45 nope; 43 = 6^2
      + 2^2 + 1^2 + 0^2 = 36 + 4 + 1 + 0 = 41 nope; 43 = 5^2 + 4^2 + 1^2 + 1^2
      = 25 + 16 + 1 + 1 = 43 yes, so 43 = 5^2 + 4^2 + 1^2 + 1^2 = 25 + 16 + 1 + 1
      = 43
    * 43 = 1000_5 (in base 5, 1*125 + 0*25 + 0*5 + 0 = 125, not 43); 43 = 133_5
      (1*25 + 3*5 + 3 = 25 + 15 + 3 = 43 yes, so 43 in base 5 is 133)
    * 43 = 0x2B in hexadecimal, 0b101011 in binary, 0101 in BCD
    * 43 is the 14th prime, between 41 and 47
    * 43 = 33 + 10 (digits 3+3+10 reversed are 03+3 = 6 nope), 43 has digit sum
      4+3 = 7, the 4th prime is 7
    * 43 is the smallest prime where the decimal expansion of 1/43 has period
      21 (the multiplicative order of 10 modulo 43 is 21), so 1/43 is a
      "full reptend" of period 21, NOT 42 (since 43 - 1 = 42 and the actual
      order is 21, a proper divisor)
    * 43 is the atomic number of technetium (Tc), the lightest radioactive
      element, used in medical imaging (Tc-99m is the most widely used
      medical radioisotope, used in over 30 million medical procedures per
      year), a transition metal in Group 7, Period 5
    * 43 is the country code for Austria (+43)
    * 43 is the 43rd US president is George W. Bush (served 2001-2009)
    * 43 is the number of chromosomes in the duck-billed platypus genome
      (platypus has 52 chromosomes actually, but 43 is the number of
      autosomes in some species)
    * 43 is the total number of presidents of Mexico, the total number of
      provinces in Indonesia
    * 43 = 2^5 + 11 = 32 + 11, the smallest prime expressible as 2^5 + 11
    * 43 is the 14th of 100 primes, an ordinary prime (not Sophie Germain,
      not twin prime, not Mersenne prime, not Fermat prime, not Wieferich prime)

This script demonstrates the tritetracontagon parametric form by computing
a discretized sample of the curve.
"""

import math


def main():
    a = 4.0  # scale parameter
    n = 43   # number of cusps
    length = 32  # number of samples

    # Compute samples along the curve
    samples = []
    for i in range(length):
        t = (2.0 * math.pi) * i / max(1, length - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_42t = math.cos(42.0 * t)
        sin_42t = math.sin(42.0 * t)
        x = a * cos_t + (a / 42.0) * cos_42t
        y = a * sin_t - (a / 42.0) * sin_42t
        samples.append((x, y))

    print(f"Tritetracontagon (43-cusped hypocycloid):")
    print(f"  Parametric: x = a*cos(t) + (a/42)*cos(42t)")
    print(f"             y = a*sin(t) - (a/42)*sin(42t)")
    print(f"  Scale: a = {a}")
    print(f"  Cusps: {n}")
    print(f"  R/r = {n}, r = a/{n-1} = {a}/{n-1}, R = {n}*a/{n-1} = {n*a/(n-1):.4f}")
    print()

    # Print first few samples
    print(f"First 5 samples (of {len(samples)}):")
    for i, (x, y) in enumerate(samples[:5]):
        print(f"  i={i}: x={x:+.4f}, y={y:+.4f}")
    print()

    # Verify the rightmost extreme at t=0
    t = 0.0
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_42t = math.cos(42.0 * t)
    sin_42t = math.sin(42.0 * t)
    x_at_0 = a * cos_t + (a / 42.0) * cos_42t
    y_at_0 = a * sin_t - (a / 42.0) * sin_42t
    expected_x = a + a / 42.0  # 43a/42

    print(f"At t=0 (rightmost extreme):")
    print(f"  x = a + a/42 = {a} + {a/42:.6f} = {expected_x:.6f}")
    print(f"  computed x = {x_at_0:.6f}")
    print(f"  y = 0 (computed: {y_at_0:.6f})")
    print(f"  expected: x = 43a/42 = {43*a/42:.6f}")
    print()

    # Bounding box
    xs = [s[0] for s in samples]
    ys = [s[1] for s in samples]
    print(f"Bounding box (N={len(samples)} samples):")
    print(f"  x range: [{min(xs):.6f}, {max(xs):.6f}]")
    print(f"  y range: [{min(ys):.6f}, {max(ys):.6f}]")


if __name__ == "__main__":
    main()