#!/usr/bin/env python3
"""
Day 775: Hexacosagon (26-cusped Hypocycloid) Notes - Reproducibility Script

The hexacosagon is the 26-cusped hypocycloid in the classical sequence
cardioid (1 cusp), nephroid (2), deltoid (3), astroid (4), pentoid (5),
hexacuspid (6), heptoid (7), octoid (8), enneoid (9), decussata (10),
hendecagon (11), dodecagon (12), tridecagon (13), tetradecagon (14),
pentadecagon (15), hexadecagon (16), heptadecagon (17), octadecagon (18),
enneadecagon (19), icosagon (20), icosikaihenagon (21), icosikaiheptagon (22),
icosikaitetragon (23), tetracosagon (24), pentacosagon (25), hexacosagon (26).

Parametric equations (Day 775):
    x(t) = a * cos(t) + (a/25) * cos(25 * t)
    y(t) = a * sin(t) - (a/25) * sin(25 * t)

Properties:
    - 26-fold rotational D26 dihedral symmetry
    - 26 inward-pointing cusps evenly distributed at 360/26 ≈ 13.85 deg intervals
    - Generated by a small circle of radius r = a/25 rolling inside a fixed
      circle of radius R = 26a/25 (R/r = 26, 26 cusps per revolution)
    - At t = 0: x = a + a/25 = 26a/25 (the rightmost extreme), y = 0
    - 26 = 2 * 13 is NOT constructible by compass and straightedge (Gauss-Wantzel
      1837 theorem: n-gon is constructible iff n is a product of DISTINCT Fermat
      primes and a power of 2; 13 is not a Fermat prime, so 26 = 2*13 is NOT
      constructible by classical means)
    - 26-fold rotational symmetry is forbidden in classical crystallography
      (Bravais 1850 only allows 1, 2, 3, 4, 6-fold rotations in periodic crystals)
      but appears in 26-fold quasicrystal approximants.

This script verifies the parametric equations produce the expected
rightmost extreme at t = 0 and a 26-fold symmetric distribution of samples.
"""

import math


def hexacosagon_x(t, a):
    return a * math.cos(t) + (a / 25.0) * math.cos(25.0 * t)


def hexacosagon_y(t, a):
    return a * math.sin(t) - (a / 25.0) * math.sin(25.0 * t)


def main():
    a = 4  # default scale

    # 1. Rightmost extreme at t = 0
    x0 = hexacosagon_x(0.0, a)
    y0 = hexacosagon_y(0.0, a)
    expected_x = a + a / 25.0
    print(f"t = 0: x = {x0:.6f}, y = {y0:.6f}")
    print(f"  expected x = {expected_x:.6f} (= a + a/25 = 26a/25)")
    assert abs(x0 - expected_x) < 1e-9, "rightmost extreme mismatch"
    assert abs(y0) < 1e-9, "y at t=0 should be 0"

    # 2. 26 samples evenly spaced around the full revolution
    n = 64
    samples = []
    for i in range(n):
        t = 2.0 * math.pi * i / max(1, n - 1)
        x = hexacosagon_x(t, a)
        y = hexacosagon_y(t, a)
        samples.append((x, y))

    # 3. Verify cusp count: 26 samples have local extreme points (cusp approximations)
    # A cusp occurs when (x', y') = 0 simultaneously. At t = 2*pi*k/26 for k in [0..26]
    # the parametric derivative cancels and we are at the cusps.
    print(f"\nSampling {n} points around the hexacosagon (a={a}):")
    for k in range(26):
        t = 2.0 * math.pi * k / 26.0
        x = hexacosagon_x(t, a)
        y = hexacosagon_y(t, a)
        r = math.hypot(x, y)
        print(f"  t = 2*pi*{k}/26 = {t:.4f} rad: ({x:+.4f}, {y:+.4f}), |r| = {r:.4f}")

    # 4. The 26 cusps should be evenly distributed around the origin (the original
    #    epicenter of the rolling circle). Verify by checking radial distances.
    print("\nRadial distance range:")
    radii = [math.hypot(s[0], s[1]) for s in samples]
    print(f"  min r = {min(radii):.4f}, max r = {max(radii):.4f}")

    print("\nDay 775 hexacosagon verification complete.")


if __name__ == "__main__":
    main()