"""Day 798: Heptatetracontagon (47-cusped Hypocycloid) Notes - Reproducibility Script.

The heptatetracontagon is the 47-cusped hypocycloid, the natural 47-cusped cousin of
the cardioid (1 cusp) through the hexatetracontagon (46 cusps), extending the
1-2-3-...-47 cusp sequence of classical hypocycloids.

Parametric equations:
    x(t) = a*cos(t) + (a/46)*cos(46*t)
    y(t) = a*sin(t) - (a/46)*sin(46*t)

Generated by a small circle of radius r = a/46 rolling without slipping INSIDE
a fixed circle of radius R = 47a/46 (R/r = 47, 47 cusps per revolution).

Properties:
    * 47-fold rotational symmetry (D47 dihedral symmetry)
    * 47 inward-pointing cusps evenly distributed at 360/47 ~ 7.66 degree intervals
    * 47 is prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537),
      so the 47-gon is NOT constructible by compass and straightedge (Gauss-Wantzel
      1837 theorem: n is constructible iff n is a product of DISTINCT Fermat primes
      and a power of 2; 47 is prime but NOT Fermat, so 47 fails the distinctness
      criterion).
    * 47-fold rotational symmetry is forbidden in classical crystallography
      (Bravais 1850 crystallographic restriction theorem only allows 1, 2, 3,
      4, 6-fold rotations in periodic crystal lattices), but appears in
      47-fold quasicrystal approximants.
    * 47 is the 15th prime number (after 43, before 53); the sequence of primes
      is 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, ...
    * 47 is a safe prime (since (47-1)/2 = 23 is also prime, making 47 a safe
      prime; safe primes p have (p-1)/2 also prime); 23 is the corresponding
      Sophie Germain prime (since 2*23+1 = 47 is prime).
    * 47 is a Lucas prime (47 appears in the Lucas sequence: L(0)=2, L(1)=1,
      L(2)=3, L(3)=4, L(4)=7, L(5)=11, L(6)=18, L(7)=29, L(8)=47, yes).
    * 47 is the sum of 5 consecutive primes: 47 = 5 + 7 + 11 + 13 + 11 nope
      (need distinct); 47 = 3 + 5 + 7 + 11 + 13 + 8 nope; actually 47 =
      2 + 3 + 5 + 7 + 11 + 13 + 6 nope; the simplest representation is
      47 = 23 + 24 (not prime). 47 is the sum of 3 consecutive primes
      13 + 15 + 19 nope (15 not prime); 47 = 11 + 13 + 23 (yes, sum of
      3 primes), or 47 = 5 + 19 + 23, etc. So 47 has many prime representations
      as sums.
    * 47 is NOT a triangular number (T_9 = 45, T_10 = 55, 47 is between).
    * 47 is the atomic number of silver (Ag, a transition metal in Group 11,
      Period 5, the element with the highest electrical conductivity).
    * 47 is the smallest prime p such that the decimal expansion of 1/p has
      period 46 (the multiplicative order of 10 mod 47 is 46; ord_47(10) = 46,
      so 1/47 = 0.0212765957446808510638297872340425531914893617... recurring
      with 46-digit period; 47 is a full reptend prime because 10 is a primitive
      root mod 47, making 47 the smallest full reptend prime after 7, 17, 19, 23,
      29, 47, 59, 61, 97, ...). 47 is the smallest prime greater than 7 whose
      repetend has 46 digits, all of 1..46 in some order if 10 is a full
      multiplicative generator (which it is for 47).

This script reproduces the parametric curve and verifies the rightmost extreme.
"""

import math


def main():
    a = 4.0  # scale parameter
    n = 47   # number of cusps
    length = 32  # number of samples

    # Compute samples along the curve
    samples = []
    for i in range(length):
        t = (2.0 * math.pi) * i / max(1, length - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_46t = math.cos(46.0 * t)
        sin_46t = math.sin(46.0 * t)
        x = a * cos_t + (a / 46.0) * cos_46t
        y = a * sin_t - (a / 46.0) * sin_46t
        samples.append((x, y))

    print("Heptatetracontagon (47-cusped hypocycloid):")
    print("  Parametric: x = a*cos(t) + (a/46)*cos(46t)")
    print("             y = a*sin(t) - (a/46)*sin(46t)")
    print(f"  Scale: a = {a}")
    print(f"  Cusps: {n}")
    print(f"  R/r = {n}, r = a/{n-1} = {a}/{n-1}, R = {n}*a/{n-1} = {n*a/(n-1):.4f}")
    print()

    # Print first few samples
    print(f"First 5 samples (of {len(samples)}):")
    for i, (x, y) in enumerate(samples[:5]):
        print(f"  i={i}: x={x:+.4f}, y={y:+.4f}")
    print()

    # Verify the rightmost extreme at t=0
    t = 0.0
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_46t = math.cos(46.0 * t)
    sin_46t = math.sin(46.0 * t)
    x_at_0 = a * cos_t + (a / 46.0) * cos_46t
    y_at_0 = a * sin_t - (a / 46.0) * sin_46t
    expected_x = a + a / 46.0  # 47a/46

    print("At t=0 (rightmost extreme):")
    print(f"  x = a + a/46 = {a} + {a/46:.6f} = {expected_x:.6f}")
    print(f"  computed x = {x_at_0:.6f}")
    print(f"  y = 0 (computed: {y_at_0:.6f})")
    print(f"  expected: x = 47a/46 = {47*a/46:.6f}")
    print()

    # Bounding box
    xs = [s[0] for s in samples]
    ys = [s[1] for s in samples]
    print(f"Bounding box (N={len(samples)} samples):")
    print(f"  x range: [{min(xs):.6f}, {max(xs):.6f}]")
    print(f"  y range: [{min(ys):.6f}, {max(ys):.6f}]")
    print()

    # 47 constructibility check (Gauss-Wantzel 1837)
    print("Constructibility analysis (Gauss-Wantzel 1837):")
    print("  47 is prime (the 15th prime)")
    print("  Fermat primes are: 3, 5, 17, 257, 65537")
    print("  47 is prime but NOT a Fermat prime -> 47-gon is NOT constructible")
    print()
    print("Additional properties of 47:")
    print("  - 47 is a Sophie Germain-derived safe prime: 2*23+1=47 where 23 is SG prime")
    print("  - 47 is a Lucas prime (47 = L(8) in the Lucas sequence)")
    print("  - 47 is a full reptend prime (10 is a primitive root mod 47, period 46)")
    print("  - 47 is the atomic number of silver (Ag)")


if __name__ == "__main__":
    main()