#!/usr/bin/env python3
"""
Day 772: Icosikaitetragon (23-cusped Hypocycloid) Notes reproducibility script.

Plots samples along the icosikaitetragon (23-cusped hypocycloid) curve to verify the
parametric form x = a*cos(t) + (a/22)*cos(22t), y = a*sin(t) - (a/22)*sin(22t).

The icosikaitetragon is the natural 23-cusped hypocycloid in the classical
1-2-3-...-23 cusp sequence of hypocycloids. Generated by a small circle of radius
r = a/22 rolling inside a fixed circle of radius R = 23a/22.

23 is a prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537).
The regular icosikaitetragon is NOT constructible by compass and straightedge
(Gauss-Wantzel 1837). 23-fold rotational symmetry is forbidden in classical
crystallography but allowed in 23-fold quasicrystal approximants.
"""

import math


def icosikaitetragon_sample(a, t):
    """Return (x, y) on the icosikaitetragon (23-cusped hypocycloid) at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_22t = math.cos(22 * t)
    sin_22t = math.sin(22 * t)
    x = a * cos_t + (a / 22) * cos_22t
    y = a * sin_t - (a / 22) * sin_22t
    return x, y


def main():
    a = 4.0
    length = 32
    # STANDARD shape: t in [0, 2*pi]
    samples = [icosikaitetragon_sample(a, 2 * math.pi * i / max(1, length - 1))
               for i in range(length)]
    print(f"Icosikaitetragon (R/r=23, a={a}, N={length}) samples:")
    for i, (x, y) in enumerate(samples):
        print(f"  i={i:2d}  x={x:+.4f}  y={y:+.4f}")

    # Verify the rightmost extreme at t=0: x = a + a/22 = 23a/22
    x0, y0 = icosikaitetragon_sample(a, 0)
    expected_x0 = a + a / 22
    print(f"\nAt t=0: x={x0:+.6f} (expected {expected_x0:+.6f} = 23a/22), y={y0:+.6f} (expected 0)")

    # Cusps: 23 cusps per revolution, one cusp per 2pi/23 radians
    print(f"\n23 cusps per revolution (one cusp every 2pi/23 = {2*math.pi/23:.4f} rad = {360/23:.2f} deg)")


if __name__ == "__main__":
    main()
