#!/usr/bin/env python3
"""Day 799 Octatetracontagon (48-cusped Hypocycloid) Notes - reproducibility script.

Generates the parametric x,y samples that the octatetracontagonNotes method places
on the SnugOS sequencer grid, demonstrating the 48-fold D48 dihedral symmetry
of the 48-cusped hypocycloid curve.

Parametric form (Day 799):
    x(t) = a*cos(t) + (a/47)*cos(47*t)
    y(t) = a*sin(t) - (a/47)*sin(47*t)

Generated by a small circle of radius r = a/47 rolling without slipping INSIDE
a fixed circle of radius R = 48a/47 (R/r = 48, 48 cusps per revolution).
48 = 2^4 * 3 is constructible by compass and straightedge (Gauss-Wantzel 1837
theorem: n is constructible iff n is a product of DISTINCT Fermat primes and a
power of 2; 3 is a Fermat prime and 16 is a power of 2, so 48 satisfies the
criterion).
"""
import math

A = 4  # scale parameter (matches Track.js default OCTATETRACONTAGON_NOTES_DEFAULT_A)
N = 32  # number of samples (matches OCTATETRACONTAGON_NOTES_DEFAULT_LENGTH)

samples = []
for i in range(N):
    t = 2 * math.pi * i / max(1, N - 1)  # full revolution, [0, 2*pi]
    x = A * math.cos(t) + (A / 47) * math.cos(47 * t)
    y = A * math.sin(t) - (A / 47) * math.sin(47 * t)
    if not (math.isfinite(x) and math.isfinite(y)):
        continue
    samples.append((x, y, t))

print(f"Day 799 Octatetracontagon (48-cusped Hypocycloid)")
print(f"  N = {N}, A = {A}")
print(f"  Samples: {len(samples)} finite (out of {N} computed)")
print(f"  Cusp interval: 360/48 = {360/48} deg = 2pi/48 = {2*math.pi/48:.6f} rad")
print(f"  Symmetry: D48 (48-fold rotational)")
print(f"  Constructible by compass+straightedge: YES (48 = 2^4 * 3, 3 is Fermat prime)")
print()
print(f"  Rightmost extreme at t=0: x = {samples[0][0]:.4f}, y = {samples[0][1]:.4f}")
print(f"  Expected: x = A + A/47 = 48A/47 = {48*A/47:.4f}, y = 0")
print()
print("  Sample points (first 5):")
for i, (x, y, t) in enumerate(samples[:5]):
    print(f"    i={i:2d}, t={t:.4f}, x={x:+.4f}, y={y:+.4f}")
print()
print("  Sample points (last 5):")
for i, (x, y, t) in enumerate(samples[-5:]):
    print(f"    i={N-5+i:2d}, t={t:.4f}, x={x:+.4f}, y={y:+.4f}")

# Sanity-check that 48-fold rotational symmetry approximately holds
print()
print("  48-fold symmetry check: rotate by 2*pi/48 and compare to next sample")
print(f"  Sample 0:        x={samples[0][0]:+.4f}, y={samples[0][1]:+.4f}")
print(f"  Sample 1 (~7.5deg): x={samples[1][0]:+.4f}, y={samples[1][1]:+.4f}")