"""Day 792: Hepatetracontagon (41-cusped Hypocycloid) Notes - Reproducibility Script.

The hepatetracontagon is the 41-cusped hypocycloid, the natural 41-cusped cousin of
the cardioid (1 cusp) through the tetracontagon (40 cusps), extending the
1-2-3-...-41 cusp sequence of classical hypocycloids.

Parametric equations:
    x(t) = a*cos(t) + (a/40)*cos(40*t)
    y(t) = a*sin(t) - (a/40)*sin(40*t)

Generated by a small circle of radius r = a/40 rolling without slipping INSIDE
a fixed circle of radius R = 41a/40 (R/r = 41, 41 cusps per revolution).

Properties:
    * 41-fold rotational symmetry (D41 dihedral symmetry)
    * 41 inward-pointing cusps evenly distributed at 360/41 degree intervals
    * 41 is the 13th prime number
    * 41 is prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537),
      so the regular 41-gon is NOT constructible by compass and straightedge
      (Gauss-Wantzel 1837 theorem)
    * 41 = 2^5 + 2^3 + 2^0 = 32 + 8 + 1 = 41 (binary 101001)
    * 41 is the smallest prime expressible as the sum of the first six primes:
      2 + 3 + 5 + 7 + 11 + 13 = 41
    * 41 is a Newman-Shanks-Williams prime
    * 41 is a centered square number? No, 41 is not a centered square number.
    * 41 is the atomic number of niobium (Nb)
    * 41 is the sum of three consecutive squares: 9 + 16 + 16 nope; 25 + 16 = 41
      but 16 is not a perfect square distinct; 41 = 25 + 16 = 5^2 + 4^2, sum of
      two squares
    * 41 is the smallest prime that is the sum of 2 distinct squares (5^2 + 4^2 = 41)
    * 41 is the 13th prime, the 6th Sophie Germain prime? No, 41 is not Sophie
      Germain since 2*41+1 = 83 is prime, so 41 IS a Sophie Germain prime
    * 41 is the 6th Sophie Germain prime after 2, 3, 5, 11, 23 (Sophie Germain
      primes p where 2p+1 is also prime; the 6th is 41 since 2*41+1 = 83 is prime)
"""

import math


def hepatetracontagon_samples(num_samples, scale):
    """Generate num_samples points along the hepatetracontagon curve."""
    a = scale
    a_over_40 = a / 40
    samples = []
    for i in range(num_samples):
        t = 2 * math.pi * i / max(1, num_samples - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_40t = math.cos(40 * t)
        sin_40t = math.sin(40 * t)
        x = a * cos_t + a_over_40 * cos_40t
        y = a * sin_t - a_over_40 * sin_40t
        samples.append((x, y))
    return samples


def main():
    print("Day 792: Hepatetracontagon (41-cusped Hypocycloid) Notes")
    print()
    print("Parametric equations:")
    print("  x(t) = a*cos(t) + (a/40)*cos(40*t)")
    print("  y(t) = a*sin(t) - (a/40)*sin(40*t)")
    print()

    # Verify 41 is prime
    is_prime_41 = all(41 % i != 0 for i in range(2, int(math.sqrt(41)) + 1))
    print(f"41 is prime: {is_prime_41}")
    print(f"41 = sum of first six primes (2+3+5+7+11+13) = {2+3+5+7+11+13}")
    print(f"41 = 2^5 + 2^3 + 2^0 = {2**5 + 2**3 + 2**0} (binary 101001)")
    print(f"41-fold rotational D41 dihedral symmetry, NOT constructible (Gauss-Wantzel 1837)")
    print()

    a = 4
    num_samples = 32
    samples = hepatetracontagon_samples(num_samples, a)

    print(f"Sample points (N={num_samples}, a={a}):")
    for i in range(0, min(8, len(samples))):
        x, y = samples[i]
        t = 2 * math.pi * i / max(1, num_samples - 1)
        print(f"  i={i:3d}  t={t:.6f}  x={x:+.6f}  y={y:+.6f}")
    print(f"  ... ({len(samples)} total samples)")
    print()

    # Verification at t=0
    print("Verification at t=0:")
    x0 = a * math.cos(0) + (a / 40) * math.cos(40 * 0)
    y0 = a * math.sin(0) - (a / 40) * math.sin(40 * 0)
    print(f"  x(0) = {x0:.10f} (expected a + a/40 = {a + a/40:.10f}, i.e. 41a/40)")
    print(f"  y(0) = {y0:.10f} (expected 0)")
    print()
    print(f"At t=0, the hepatetracontagon is at its rightmost extreme (41a/40, 0).")
    print()

    xs = [s[0] for s in samples]
    ys = [s[1] for s in samples]
    print(f"Bounding box (N={len(samples)} samples):")
    print(f"  x range: [{min(xs):.6f}, {max(xs):.6f}]")
    print(f"  y range: [{min(ys):.6f}, {max(ys):.6f}]")


if __name__ == "__main__":
    main()
