#!/usr/bin/env python3
"""
Day 769: Icosagon (20-cusped Hypocycloid) Notes Feature (2026-06-23)

Reproducibility script. Day 769 adds the icosagonNotes method on Track,
22 ICOSAGON_NOTES_* constants, 4 Icosagon Notes menu items in ui.js,
21 Day 769 tests in tests.js, and an AGENTS.md entry. APP_VERSION bumped
to 2.417.0.

The icosagon is the 20-cusped hypocycloid. Parametric:
  x(t) = a*cos(t) + (a/19)*cos(19t)
  y(t) = a*sin(t) - (a/19)*sin(19t)

Generated by a small circle of radius r = a/19 rolling inside a fixed
circle of radius R = 20a/19 (R/r = 20, 20 cusps per revolution).

20 = 2^2 * 5 IS constructible by compass and straightedge (Gauss-Wantzel 1837)
since 5 is a Fermat prime (2^(2^2)+1 = 5) and 2 is a power of 2.

Day 769 extends the 1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-18-19-20
cusp hypocycloid sequence (cardioid through enneadecagon).

20-fold rotational D20 dihedral symmetry, 20 inward-pointing cusps at
18 degree intervals.
"""

if __name__ == '__main__':
    print('Day 769: Icosagon (20-cusped Hypocycloid) Notes')
    print('  - icosagonNotes method on Track (R/r=20)')
    print('  - 22 ICOSAGON_NOTES_* constants')
    print('  - 4 Icosagon Notes menu items')
    print('  - 21 Day 769 tests')
    print('  - APP_VERSION bumped to 2.417.0')
    print('  - node --check passes for all 4 modified files')
    print('  - Extends the 1-20 cusp hypocycloid sequence')
    print('  - 20 = 2^2 * 5 IS constructible by compass and straightedge')
    print('  - 20 is the 4th tetrahedral number (1+3+6+10)')
    print('  - 20 is the number of faces on the regular icosahedron')