#!/usr/bin/env python3
"""Day 764: Add Hexadecagon (16-cusped) Notes feature to snugos/app."""
import sys

REPO = "/home/.z/automation-workspaces/app-repo"

# ===== CONSTANTS: Hexadecagon (16-cusped Hypocycloid) =====
# 16 = 2^4 is a power of 2, so the regular 16-gon IS constructible by compass and straightedge.
# Hexadecagon parametric: x = a*cos(t) + (a/15)*cos(15t), y = a*sin(t) - (a/15)*sin(15t)
# At t=0: x = a + a/15 = 16a/15, y = 0 (the rightmost extreme).
# The SHAPE name is 'hexadecagon' (the 16-cusped hypocycloid).
HEXADECAGON_BLOCK = """// Day 764: Hexadecagon (16-cusped Hypocycloid) Notes constants - 16-fold D16 symmetric hypocycloid (R/r=16)
// The 16-cusped hypocycloid in the 1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16 cusp hypocycloid sequence.
// Generated by a small circle of radius r = a/15 rolling inside a fixed circle of radius R = 16a/15.
// Parametric: x = a*cos(t) + (a/15)*cos(15t), y = a*sin(t) - (a/15)*sin(15t).
// At t=0: x = a + a/15 = 16a/15, y = 0 (the rightmost extreme).
// 16 = 2^4 is a power of 2, so the regular 16-gon IS constructible by compass and straightedge (Gauss-Wantzel 1837).
export const HEXADECAGON_NOTES_MIN_LENGTH = 8;
export const HEXADECAGON_NOTES_MAX_LENGTH = 64;
export const HEXADECAGON_NOTES_DEFAULT_LENGTH = 32;
export const HEXADECAGON_NOTES_MIN_A = 1;
export const HEXADECAGON_NOTES_MAX_A = 8;
export const HEXADECAGON_NOTES_DEFAULT_A = 4;
export const HEXADECAGON_NOTES_MIN_VELOCITY_DECAY = 0.1;
export const HEXADECAGON_NOTES_MAX_VELOCITY_DECAY = 1.0;
export const HEXADECAGON_NOTES_DEFAULT_VELOCITY_DECAY = 0.95;
export const HEXADECAGON_NOTES_DEFAULT_T_MIN = 0;
export const HEXADECAGON_NOTES_DEFAULT_T_MAX = 2 * Math.PI;
export const HEXADECAGON_NOTES_INVERTED_T_MIN = 2 * Math.PI;
export const HEXADECAGON_NOTES_INVERTED_T_MAX = 0;
export const HEXADECAGON_NOTES_HEXADECAGON_T_MIN = 0;
export const HEXADECAGON_NOTES_HEXADECAGON_T_MAX = 2 * Math.PI / 16;
export const HEXADECAGON_NOTES_TIGHT_T_MIN = -Math.PI / 16;
export const HEXADECAGON_NOTES_TIGHT_T_MAX = Math.PI / 16;
export const HEXADECAGON_NOTES_SHAPE_STANDARD = 'standard';
export const HEXADECAGON_NOTES_SHAPE_INVERTED = 'inverted';
export const HEXADECAGON_NOTES_SHAPE_HEXADECAGON = 'hexadecagon';
export const HEXADECAGON_NOTES_SHAPE_TIGHT = 'tight';
export const HEXADECAGON_NOTES_SHAPES = [
    HEXADECAGON_NOTES_SHAPE_STANDARD,
    HEXADECAGON_NOTES_SHAPE_INVERTED,
    HEXADECAGON_NOTES_SHAPE_HEXADECAGON,
    HEXADECAGON_NOTES_SHAPE_TIGHT
];

"""

# ===== Track.js: hexadecagonNotes method =====
# Mirrors pentadecagonNotes exactly, with renames:
# pentadecagon -> hexadecagon, 14 -> 15 (n-1), 15 -> 16 (n).
HEXADECAGON_METHOD = """    // Day 764: Hexadecagon (16-cusped Hypocycloid) Notes - 16-fold D16 symmetric hypocycloid (R/r=16)
    // The 16-cusped hypocycloid in the 1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16 cusp hypocycloid sequence.
    // Generated by a small circle of radius r = a/15 rolling inside a fixed circle of radius R = 16a/15.
    // Parametric: x = a*cos(t) + (a/15)*cos(15t), y = a*sin(t) - (a/15)*sin(15t).
    // At t=0: x = a + a/15 = 16a/15, y = 0 (the rightmost extreme).
    hexadecagonNotes(length = Constants.HEXADECAGON_NOTES_DEFAULT_LENGTH, scale = Constants.HEXADECAGON_NOTES_DEFAULT_A, velocityDecay = Constants.HEXADECAGON_NOTES_DEFAULT_VELOCITY_DECAY, shape = Constants.HEXADECAGON_NOTES_SHAPE_STANDARD, skipOccupied = true) {
        if (this.type === 'Audio') return 0;
        const activeSeq = this.getActiveSequence();
        if (!activeSeq || !activeSeq.data) {
            console.warn(`[Track ${this.id} hexadecagonNotes] No active sequence found.`);
            return 0;
        }

        const clampedLength = Math.max(Constants.HEXADECAGON_NOTES_MIN_LENGTH, Math.min(Constants.HEXADECAGON_NOTES_MAX_LENGTH, Math.floor(length)));
        const clampedA = Math.max(Constants.HEXADECAGON_NOTES_MIN_A, Math.min(Constants.HEXADECAGON_NOTES_MAX_A, Math.floor(scale)));
        const clampedDecay = Math.max(Constants.HEXADECAGON_NOTES_MIN_VELOCITY_DECAY, Math.min(Constants.HEXADECAGON_NOTES_MAX_VELOCITY_DECAY, velocityDecay));
        const useShape = Constants.HEXADECAGON_NOTES_SHAPES.includes(shape) ? shape : Constants.HEXADECAGON_NOTES_SHAPE_STANDARD;

        const tRangeMap = {
            [Constants.HEXADECAGON_NOTES_SHAPE_STANDARD]: [Constants.HEXADECAGON_NOTES_DEFAULT_T_MIN, Constants.HEXADECAGON_NOTES_DEFAULT_T_MAX],
            [Constants.HEXADECAGON_NOTES_SHAPE_INVERTED]: [Constants.HEXADECAGON_NOTES_INVERTED_T_MIN, Constants.HEXADECAGON_NOTES_INVERTED_T_MAX],
            [Constants.HEXADECAGON_NOTES_SHAPE_HEXADECAGON]: [Constants.HEXADECAGON_NOTES_HEXADECAGON_T_MIN, Constants.HEXADECAGON_NOTES_HEXADECAGON_T_MAX],
            [Constants.HEXADECAGON_NOTES_SHAPE_TIGHT]: [Constants.HEXADECAGON_NOTES_TIGHT_T_MIN, Constants.HEXADECAGON_NOTES_TIGHT_T_MAX]
        };
        const tRange = tRangeMap[useShape] || tRangeMap[Constants.HEXADECAGON_NOTES_SHAPE_STANDARD];
        const tMin = tRange[0];
        const tMax = tRange[1];

        this._captureUndoState(`Hexadecagon Notes (${useShape}, a=${clampedA}, N=${clampedLength}) on ${activeSeq.name}`);

        const numRows = activeSeq.data.length;
        const totalSteps = activeSeq.length;
        let hexadecagonCount = 0;
        const defaultVel = Constants.defaultVelocity || 0.7;
        const newNotes = [];

        const samples = [];
        const a = clampedA;
        const aOver15 = a / 15;
        for (let i = 0; i < clampedLength; i++) {
            const t = tMin + (tMax - tMin) * i / Math.max(1, clampedLength - 1);
            const cosT = Math.cos(t);
            const sinT = Math.sin(t);
            const cos15T = Math.cos(15 * t);
            const sin15T = Math.sin(15 * t);
            const x = a * cosT + aOver15 * cos15T;
            const y = a * sinT - aOver15 * sin15T;
            if (!isFinite(x) || !isFinite(y)) continue;
            samples.push({ x, y });
        }

        let xMin = Infinity, xMax = -Infinity, yMin = Infinity, yMax = -Infinity;
        for (const p of samples) {
            if (p.x < xMin) xMin = p.x;
            if (p.x > xMax) xMax = p.x;
            if (p.y < yMin) yMin = p.y;
            if (p.y > yMax) yMax = p.y;
        }
        if (!isFinite(xMin)) { xMin = -a; xMax = a; yMin = -a; yMax = a; }
        const xRange = Math.max(0.01, xMax - xMin);
        const yRange = Math.max(0.01, yMax - yMin);
        const colScale = (clampedLength - 1) / xRange;
        const rowScale = (clampedLength - 1) / (2 * yRange);

        for (let rowIndex = 0; rowIndex < numRows; rowIndex++) {
            const row = activeSeq.data[rowIndex];
            if (!row) continue;

            for (let col = 0; col < totalSteps; col++) {
                const stepData = row[col];
                if (!stepData || !stepData.active) continue;

                const origVel = (stepData.velocity !== undefined) ? stepData.velocity : defaultVel;

                for (let i = 0; i < samples.length; i++) {
                    const pt = samples[i];
                    const rowOffset = Math.max(-(clampedLength - 1) / 2, Math.min((clampedLength - 1) / 2, Math.round((pt.y - yMin) * rowScale - (clampedLength - 1) / 2)));
                    const colOffset = Math.max(0, Math.min(clampedLength - 1, Math.round((pt.x - xMin) * colScale)));
                    const targetRow = rowIndex + rowOffset;
                    const targetCol = col + colOffset;

                    if (targetRow < 0 || targetRow >= numRows) continue;
                    if (targetCol < 0 || targetCol >= totalSteps) continue;
                    if (skipOccupied && activeSeq.data[targetRow] && activeSeq.data[targetRow][targetCol] && activeSeq.data[targetRow][targetCol].active) continue;
                    if (targetRow === rowIndex && targetCol === col) continue;

                    const decayedVel = Math.max(0.05, Math.min(1.0, origVel * Math.pow(clampedDecay, i)));
                    newNotes.push({
                        rowIndex: targetRow,
                        col: targetCol,
                        velocity: Math.round(decayedVel * 100) / 100,
                        probability: stepData.probability
                    });
                }
            }
        }

        for (const note of newNotes) {
            if (!activeSeq.data[note.rowIndex]) {
                activeSeq.data[note.rowIndex] = Array(totalSteps).fill(null);
            }
            activeSeq.data[note.rowIndex][note.col] = {
                active: true,
                velocity: note.velocity,
                probability: note.probability
            };
            hexadecagonCount++;
        }

        return hexadecagonCount;
    }

"""

# ===== UI: 4 menu items for Hexadecagon Notes =====
UI_NEW_ITEMS = """                { label: `Hexadecagon Notes (Standard, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Hexadecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.hexadecagonNotes(32, 4, 0.95, 'standard', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Hexadecagon'd ${result} note(s) (standard, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to hexadecagon.", 2000); } } },
                { label: `Hexadecagon Notes (Inverted, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Hexadecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.hexadecagonNotes(32, 4, 0.95, 'inverted', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Hexadecagon'd ${result} note(s) (inverted, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to hexadecagon.", 2000); } } },
                { label: `Hexadecagon Notes (Hexadecagon, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Hexadecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.hexadecagonNotes(32, 4, 0.95, 'hexadecagon', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Hexadecagon'd ${result} note(s) (hexadecagon, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to hexadecagon.", 2000); } } },
                { label: `Hexadecagon Notes (Tight, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Hexadecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.hexadecagonNotes(32, 4, 0.95, 'tight', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Hexadecagon'd ${result} note(s) (tight, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to hexadecagon.", 2000); } } },

"""

# ===== 1. Update constants.js =====
constants_path = f"{REPO}/js/constants.js"
with open(constants_path) as f:
    constants = f.read()

old_app_version = "export const APP_VERSION = '2.412.0';\n"
new_app_version = "export const APP_VERSION = '2.413.0';\n"
if old_app_version not in constants:
    print("ERROR: APP_VERSION 2.412.0 marker not found in constants.js", file=sys.stderr)
    sys.exit(1)
constants = constants.replace(old_app_version, HEXADECAGON_BLOCK + new_app_version)
with open(constants_path, "w") as f:
    f.write(constants)
print("constants.js: added HEXADECAGON_NOTES_* block, bumped APP_VERSION to 2.413.0")

# ===== 2. Update Track.js =====
track_path = f"{REPO}/js/Track.js"
with open(track_path) as f:
    track = f.read()

anchor = """            pentadecagonCount++;
        }

        return pentadecagonCount;
    }

}
"""
if anchor not in track:
    print("ERROR: pentadecagonNotes closing anchor not found in Track.js", file=sys.stderr)
    sys.exit(1)
new_track = track.replace(anchor, """            pentadecagonCount++;
        }

        return pentadecagonCount;
    }

""" + HEXADECAGON_METHOD + "}\n", 1)
with open(track_path, "w") as f:
    f.write(new_track)
print("Track.js: added hexadecagonNotes method")

# ===== 3. Update ui.js =====
ui_path = f"{REPO}/js/ui.js"
with open(ui_path) as f:
    ui = f.read()

ui_anchor = """                { label: `Pentadecagon Notes (Tight, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Pentadecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.pentadecagonNotes(32, 4, 0.95, 'tight', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Pentadecagon'd ${result} note(s) (tight, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to pentadecagon.", 2000); } } },

                { label: `Deltoid Notes (Standard, 32)`, action: () =>"""
if ui_anchor not in ui:
    print("ERROR: Pentadecagon menu anchor not found in ui.js", file=sys.stderr)
    sys.exit(1)
new_ui = ui.replace(ui_anchor, """                { label: `Pentadecagon Notes (Tight, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Pentadecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.pentadecagonNotes(32, 4, 0.95, 'tight', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Pentadecagon'd ${result} note(s) (tight, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to pentadecagon.", 2000); } } },
""" + UI_NEW_ITEMS + """                { label: `Deltoid Notes (Standard, 32)`, action: () =>""", 1)
with open(ui_path, "w") as f:
    f.write(new_ui)
print("ui.js: added 4 Hexadecagon Notes menu items")

print("DONE")
