"""Day 797: Hexatetracontagon (46-cusped Hypocycloid) Notes - Reproducibility Script.

The hexatetracontagon is the 46-cusped hypocycloid, the natural 46-cusped cousin of
the cardioid (1 cusp) through the pentatetracontagon (45 cusps), extending the
1-2-3-...-46 cusp sequence of classical hypocycloids.

Parametric equations:
    x(t) = a*cos(t) + (a/45)*cos(45*t)
    y(t) = a*sin(t) - (a/45)*sin(45*t)

Generated by a small circle of radius r = a/45 rolling without slipping INSIDE
a fixed circle of radius R = 46a/45 (R/r = 46, 46 cusps per revolution).

Properties:
    * 46-fold rotational symmetry (D46 dihedral symmetry)
    * 46 inward-pointing cusps evenly distributed at 360/46 ~ 7.83 degree intervals
    * 46 = 2 * 23 is NOT constructible by compass and straightedge
      (Gauss-Wantzel 1837 theorem): n is constructible iff n is a product of
      DISTINCT Fermat primes and a power of 2; 23 is prime but NOT a Fermat
      prime (Fermat primes are 3, 5, 17, 257, 65537), so 46 = 2*23 fails the
      distinctness criterion despite 2 being a power of 2.
    * 46-fold rotational symmetry is forbidden in classical crystallography
      (Bravais 1850 crystallographic restriction theorem only allows 1, 2, 3,
      4, 6-fold rotations in periodic crystal lattices), but appears in
      46-fold quasicrystal approximants.
    * 46 is the 14th even nontotient (a number k such that x^2 = k has no
      integer solution; the equation phi(x) = k has no solution for x):
      the even nontotients below 100 are 14, 26, 34, 38, 50, 62, 68, 74, 76,
      86, 90, 94, 98; 46 is in this list because the only solutions to
      phi(x) = 46 are x = 47 (prime, phi(47) = 46) and x = 94 (composite
      with phi(94) = 46), so x^2 = 46 has no integer solution.
    * 46 is a sphenic number (product of 3 distinct primes)? No, 46 = 2*23
      is only the product of 2 distinct primes, so it is NOT sphenic.
    * 46 is the sum of the first 9 positive integers (1+2+...+9 = 45, NOT 46;
      actually 46 = sum of the first 8 primes + sum of the first 2 primes =
      (2+3+5+7+11+13+17+19) + (2+3) = 77 + 5 = 82, no). 46 is the atomic
      number of palladium (Pd, a transition metal in Group 10, Period 5).
    * 46 is the largest even integer that is NOT the sum of two abundant
      numbers; the smallest odd untouchable number is 5, the next is 33, etc.
    * 46 is the smallest even integer that is the sum of 2 distinct primes
      in 3 different ways (3+43 = 46, 7+39 nope 39 not prime, 5+41 = 46,
      17+29 = 46, 23+23 = 46 but not distinct); so 46 = 3+43 = 5+41 = 17+29
      (3 ways with distinct primes), the smallest such even number.
    * 46 is a centered triangular number: T_9 = 9*10/2 = 45 (no), but the
      centered triangular numbers are 1, 4, 10, 19, 31, 46, 64, ... where
      C_n = 3n(n-1)/2 + 1; C_6 = 3*6*5/2 + 1 = 45 + 1 = 46. YES, 46 IS the
      6th centered triangular number.

This script reproduces the parametric curve and verifies the rightmost extreme.
"""

import math


def main():
    a = 4.0  # scale parameter
    n = 46   # number of cusps
    length = 32  # number of samples

    # Compute samples along the curve
    samples = []
    for i in range(length):
        t = (2.0 * math.pi) * i / max(1, length - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_45t = math.cos(45.0 * t)
        sin_45t = math.sin(45.0 * t)
        x = a * cos_t + (a / 45.0) * cos_45t
        y = a * sin_t - (a / 45.0) * sin_45t
        samples.append((x, y))

    print("Hexatetracontagon (46-cusped hypocycloid):")
    print("  Parametric: x = a*cos(t) + (a/45)*cos(45t)")
    print("             y = a*sin(t) - (a/45)*sin(45t)")
    print(f"  Scale: a = {a}")
    print(f"  Cusps: {n}")
    print(f"  R/r = {n}, r = a/{n-1} = {a}/{n-1}, R = {n}*a/{n-1} = {n*a/(n-1):.4f}")
    print()

    # Print first few samples
    print(f"First 5 samples (of {len(samples)}):")
    for i, (x, y) in enumerate(samples[:5]):
        print(f"  i={i}: x={x:+.4f}, y={y:+.4f}")
    print()

    # Verify the rightmost extreme at t=0
    t = 0.0
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_45t = math.cos(45.0 * t)
    sin_45t = math.sin(45.0 * t)
    x_at_0 = a * cos_t + (a / 45.0) * cos_45t
    y_at_0 = a * sin_t - (a / 45.0) * sin_45t
    expected_x = a + a / 45.0  # 46a/45

    print("At t=0 (rightmost extreme):")
    print(f"  x = a + a/45 = {a} + {a/45:.6f} = {expected_x:.6f}")
    print(f"  computed x = {x_at_0:.6f}")
    print(f"  y = 0 (computed: {y_at_0:.6f})")
    print(f"  expected: x = 46a/45 = {46*a/45:.6f}")
    print()

    # Bounding box
    xs = [s[0] for s in samples]
    ys = [s[1] for s in samples]
    print(f"Bounding box (N={len(samples)} samples):")
    print(f"  x range: [{min(xs):.6f}, {max(xs):.6f}]")
    print(f"  y range: [{min(ys):.6f}, {max(ys):.6f}]")
    print()

    # 46 = 2 * 23 constructibility check
    print("Constructibility analysis (Gauss-Wantzel 1837):")
    print("  46 = 2 * 23 (prime factorization)")
    print("  Fermat primes are: 3, 5, 17, 257, 65537")
    print("  23 is prime but NOT a Fermat prime -> 46-gon is NOT constructible")


if __name__ == "__main__":
    main()