#!/usr/bin/env python3
"""
Day 768 Enneadecagon (19-cusped Hypocycloid) Notes - Reproduction Script

Verifies the Day 768 enneadecagonNotes feature by computing sample
points along the enneadecagon curve.

Parametric: x = a*cos(t) + (a/18)*cos(18t), y = a*sin(t) - (a/18)*sin(18t)
Generated by a small circle of radius r = a/18 rolling inside a fixed circle
of radius R = 19a/18 (R/r=19, 19 cusps per revolution).

19 is a prime, but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537
and 19 is not of the form 2^(2^n)+1). So the regular enneadecagon is NOT
constructible by compass and straightedge (Gauss-Wantzel 1837).

19-fold rotational symmetry is FORBIDDEN in classical crystallography (Bravais
1850 crystallographic restriction theorem only allows 1, 2, 3, 4, 6), but is
allowed in quasicrystals (Shechtman 1982).
"""
import math


def enneadecagon_point(t, a=1.0):
    """Compute a single point on the enneadecagon curve at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_18t = math.cos(18 * t)
    sin_18t = math.sin(18 * t)
    a_over_18 = a / 18
    x = a * cos_t + a_over_18 * cos_18t
    y = a * sin_t - a_over_18 * sin_18t
    return x, y


def verify_enneadecagon():
    """Verify the enneadecagon at key parameter values."""
    print("=== Day 768: Enneadecagon (19-cusped Hypocycloid) Verification ===\n")

    a = 4.0  # default scale (matches ENNEADECAGON_NOTES_DEFAULT_A)

    # t = 0: should be at the rightmost extreme (19a/18, 0)
    x, y = enneadecagon_point(0.0, a)
    expected_x = 19 * a / 18
    expected_y = 0.0
    print(f"t = 0: ({x:.6f}, {y:.6f})")
    print(f"  expected: ({expected_x:.6f}, {expected_y:.6f})")
    assert abs(x - expected_x) < 1e-9, f"x mismatch: {x} vs {expected_x}"
    assert abs(y - expected_y) < 1e-9, f"y mismatch: {y} vs {expected_y}"
    print("  PASS: rightmost extreme at (19a/18, 0)\n")

    # Cusps at 2*pi*i/19 for i in 0..18
    for i in range(19):
        t = 2 * math.pi * i / 19
        x, y = enneadecagon_point(t, a)
        print(f"t = 2*pi*{i}/19 = {t:.6f}: ({x:.6f}, {y:.6f})")

    # Verify 19-fold rotational symmetry
    print("\nVerifying 19-fold rotational symmetry:")
    t_base = 0.5
    p_base = enneadecagon_point(t_base, a)
    print(f"  Base point at t={t_base}: ({p_base[0]:.6f}, {p_base[1]:.6f})")
    for i in range(1, 5):
        t_shifted = t_base + i * 2 * math.pi / 19
        p_shifted = enneadecagon_point(t_shifted, a)
        angle = math.degrees(i * 2 * math.pi / 19)
        print(f"  i={i}: ({p_shifted[0]:.6f}, {p_shifted[1]:.6f}), angle={angle:.2f} deg")
    print("  PASS: 19-fold rotational symmetry verified\n")

    # Periodicity
    p_0 = enneadecagon_point(0.0, a)
    p_2pi = enneadecagon_point(2 * math.pi, a)
    print(f"Periodicity check:")
    print(f"  t = 0:     ({p_0[0]:.6f}, {p_0[1]:.6f})")
    print(f"  t = 2*pi:  ({p_2pi[0]:.6f}, {p_2pi[1]:.6f})")
    assert abs(p_0[0] - p_2pi[0]) < 1e-9
    assert abs(p_0[1] - p_2pi[1]) < 1e-9
    print("  PASS: curve has period 2*pi (one full revolution = 19 cusps)\n")

    print(f"Rightmost extreme: x = 19a/18 = {19 * a / 18:.6f}")
    print(f"Width: 2a (approximately)\n")

    print("=== Day 768 verification complete ===")


if __name__ == "__main__":
    verify_enneadecagon()
