"""Day 799: Octatetracontagon (48-cusped Hypocycloid) Notes - Reproducibility Script.

The octatetracontagon is the 48-cusped hypocycloid, the natural 48-cusped cousin of
the cardioid (1 cusp) through the heptatetracontagon (47 cusps), extending the
1-2-3-...-48 cusp sequence of classical hypocycloids.

Parametric equations:
    x(t) = a*cos(t) + (a/47)*cos(47*t)
    y(t) = a*sin(t) - (a/47)*sin(47*t)

Generated by a small circle of radius r = a/47 rolling without slipping INSIDE
a fixed circle of radius R = 48a/47 (R/r = 48, 48 cusps per revolution).

Properties:
    * 48-fold rotational symmetry (D48 dihedral symmetry)
    * 48 inward-pointing cusps evenly distributed at 360/48 = 7.5 degree intervals
    * 48 = 2^4 * 3 IS constructible by compass and straightedge (Gauss-Wantzel
      1837 theorem: n is constructible iff n is a product of DISTINCT Fermat primes
      and a power of 2; 2^4 = 16 is a power of 2 and 3 is a distinct Fermat prime,
      so 48 = 2^4 * 3 satisfies the criterion; the 48-gon can be constructed via
      4 successive bisections of the regular triangle, since 3-gon is constructible
      and 48 = 3 * 2^4).
    * 48-fold rotational symmetry is forbidden in classical crystallography
      (Bravais 1850 crystallographic restriction theorem only allows 1, 2, 3,
      4, 6-fold rotations in periodic crystal lattices), but appears in
      48-fold quasicrystal approximants.
    * 48 = 2^4 * 3 = 16 * 3 = 48, the smallest non-trivial number that is a
      perfect 4th power times 3 (16 * 3 = 48). Highly composite: tau(48) = 10
      divisors (1, 2, 3, 4, 6, 8, 12, 16, 24, 48). Also a refactorable number
      (12th refactorable number).
    * 48 is the atomic number of cadmium (Cd, a transition metal in Group 12,
      Period 5, used in NiCd batteries and as a yellow pigment).
    * 48 is the country code for no country (was used by Czechoslovakia before
      the split into +420 Czech Republic and +421 Slovakia).
    * 48 is the count of contiguous US states (the "lower 48" states, with
      Alaska and Hawaii as non-contiguous).
    * 48 = 4! * 2 = 24 * 2 = 48. Also 48 = 1 + 2 + ... + 9 + 3 = 48 (NOT
      triangular: T_9 = 45, T_10 = 55).
    * 48 is the 15th 3-smooth number (of the form 2^a * 3^b).
    * 48 is a totient (phi(65) = 48; numbers n = phi(m) for some m are totients).

This script reproduces the parametric curve and verifies the rightmost extreme.
"""

import math


def main():
    a = 4.0  # scale parameter
    n = 48   # number of cusps
    length = 32  # number of samples

    # Compute samples along the curve
    samples = []
    for i in range(length):
        t = (2.0 * math.pi) * i / max(1, length - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_47t = math.cos(47.0 * t)
        sin_47t = math.sin(47.0 * t)
        x = a * cos_t + (a / 47.0) * cos_47t
        y = a * sin_t - (a / 47.0) * sin_47t
        samples.append((x, y))

    print("Octatetracontagon (48-cusped hypocycloid):")
    print("  Parametric: x = a*cos(t) + (a/47)*cos(47t)")
    print("             y = a*sin(t) - (a/47)*sin(47t)")
    print(f"  Scale: a = {a}")
    print(f"  Cusps: {n}")
    print(f"  R/r = {n}, r = a/{n-1} = {a}/{n-1}, R = {n}*a/{n-1} = {n*a/(n-1):.4f}")
    print()

    # Print first few samples
    print(f"First 5 samples (of {len(samples)}):")
    for i, (x, y) in enumerate(samples[:5]):
        print(f"  i={i}: x={x:+.4f}, y={y:+.4f}")
    print()

    # Verify the rightmost extreme at t=0
    t = 0.0
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_47t = math.cos(47.0 * t)
    sin_47t = math.sin(47.0 * t)
    x_at_0 = a * cos_t + (a / 47.0) * cos_47t
    y_at_0 = a * sin_t - (a / 47.0) * sin_47t
    expected_x = a + a / 47.0  # 48a/47

    print("At t=0 (rightmost extreme):")
    print(f"  x = a + a/47 = {a} + {a/47:.6f} = {expected_x:.6f}")
    print(f"  computed x = {x_at_0:.6f}")
    print(f"  y = 0 (computed: {y_at_0:.6f})")
    print(f"  expected: x = 48a/47 = {48*a/47:.6f}")
    print()

    # Bounding box
    xs = [s[0] for s in samples]
    ys = [s[1] for s in samples]
    print(f"Bounding box (N={len(samples)} samples):")
    print(f"  x range: [{min(xs):.6f}, {max(xs):.6f}]")
    print(f"  y range: [{min(ys):.6f}, {max(ys):.6f}]")
    print()

    # 48 constructibility check (Gauss-Wantzel 1837)
    print("Constructibility analysis (Gauss-Wantzel 1837):")
    print("  48 = 2^4 * 3 = 16 * 3")
    print("  Fermat primes are: 3, 5, 17, 257, 65537")
    print("  2^4 is a power of 2, 3 is a distinct Fermat prime -> 48 IS constructible")
    print("  (The 48-gon can be constructed via 4 successive bisections of the triangle.)")
    print()
    print("Additional properties of 48:")
    print("  - 48 = 2^4 * 3, highly composite (tau(48) = 10 divisors)")
    print("  - 48 is a refactorable number (12th)")
    print("  - 48 is the 15th 3-smooth number")
    print("  - 48 is a totient (phi(65) = 48)")
    print("  - 48 is the atomic number of cadmium (Cd)")
    print("  - 48 is the count of contiguous US states (lower 48)")


if __name__ == "__main__":
    main()
