#!/usr/bin/env python3
"""Day 763: Add Pentadecagon (15-cusped) Notes feature to snugos/app."""
import sys

REPO = "/home/.z/automation-workspaces/app-repo"

# ===== CONSTANTS: read once =====
PENTADECAGON_BLOCK = """// Day 763: Pentadecagon (15-cusped Hypocycloid) Notes constants - 15-fold D15 symmetric hypocycloid (R/r=15)
// The 15-cusped hypocycloid in the 1-2-3-4-5-6-7-8-9-10-11-12-13-14-15 cusp hypocycloid sequence.
// Generated by a small circle of radius r = a/14 rolling inside a fixed circle of radius R = 15a/14.
// Parametric: x = a*cos(t) + (a/14)*cos(14t), y = a*sin(t) - (a/14)*sin(14t).
// At t=0: x = a + a/14 = 15a/14, y = 0 (the rightmost extreme).
// 15 = 3*5 is a product of two Fermat primes (3, 5) and a power of 2^0, so the regular 15-gon IS constructible by compass and straightedge (Gauss-Wantzel 1837).
export const PENTADECAGON_NOTES_MIN_LENGTH = 8;
export const PENTADECAGON_NOTES_MAX_LENGTH = 64;
export const PENTADECAGON_NOTES_DEFAULT_LENGTH = 32;
export const PENTADECAGON_NOTES_MIN_A = 1;
export const PENTADECAGON_NOTES_MAX_A = 8;
export const PENTADECAGON_NOTES_DEFAULT_A = 4;
export const PENTADECAGON_NOTES_MIN_VELOCITY_DECAY = 0.1;
export const PENTADECAGON_NOTES_MAX_VELOCITY_DECAY = 1.0;
export const PENTADECAGON_NOTES_DEFAULT_VELOCITY_DECAY = 0.95;
export const PENTADECAGON_NOTES_DEFAULT_T_MIN = 0;
export const PENTADECAGON_NOTES_DEFAULT_T_MAX = 2 * Math.PI;
export const PENTADECAGON_NOTES_INVERTED_T_MIN = 2 * Math.PI;
export const PENTADECAGON_NOTES_INVERTED_T_MAX = 0;
export const PENTADECAGON_NOTES_PENTADECAGON_T_MIN = 0;
export const PENTADECAGON_NOTES_PENTADECAGON_T_MAX = 2 * Math.PI / 15;
export const PENTADECAGON_NOTES_TIGHT_T_MIN = -Math.PI / 15;
export const PENTADECAGON_NOTES_TIGHT_T_MAX = Math.PI / 15;
export const PENTADECAGON_NOTES_SHAPE_STANDARD = 'standard';
export const PENTADECAGON_NOTES_SHAPE_INVERTED = 'inverted';
export const PENTADECAGON_NOTES_SHAPE_PENTADECAGON = 'pentadecagon';
export const PENTADECAGON_NOTES_SHAPE_TIGHT = 'tight';
export const PENTADECAGON_NOTES_SHAPES = [
    PENTADECAGON_NOTES_SHAPE_STANDARD,
    PENTADECAGON_NOTES_SHAPE_INVERTED,
    PENTADECAGON_NOTES_SHAPE_PENTADECAGON,
    PENTADECAGON_NOTES_SHAPE_TIGHT
];

"""

# ===== Track.js: pentadecagonNotes method =====
# The method body is identical in structure to tetradecagonNotes, with renames
# from "tetradecagon" -> "pentadecagon" and 13 -> 14 (the (n-1) parameter in cos(nt)/sin(nt)).
PENTADECAGON_METHOD = """    // Day 763: Pentadecagon (15-cusped Hypocycloid) Notes - 15-fold D15 symmetric hypocycloid (R/r=15)
    // The 15-cusped hypocycloid in the 1-2-3-4-5-6-7-8-9-10-11-12-13-14-15 cusp hypocycloid sequence.
    // Generated by a small circle of radius r = a/14 rolling inside a fixed circle of radius R = 15a/14.
    // Parametric: x = a*cos(t) + (a/14)*cos(14t), y = a*sin(t) - (a/14)*sin(14t).
    // At t=0: x = a + a/14 = 15a/14, y = 0 (the rightmost extreme).
    pentadecagonNotes(length = Constants.PENTADECAGON_NOTES_DEFAULT_LENGTH, scale = Constants.PENTADECAGON_NOTES_DEFAULT_A, velocityDecay = Constants.PENTADECAGON_NOTES_DEFAULT_VELOCITY_DECAY, shape = Constants.PENTADECAGON_NOTES_SHAPE_STANDARD, skipOccupied = true) {
        if (this.type === 'Audio') return 0;
        const activeSeq = this.getActiveSequence();
        if (!activeSeq || !activeSeq.data) {
            console.warn(`[Track ${this.id} pentadecagonNotes] No active sequence found.`);
            return 0;
        }

        const clampedLength = Math.max(Constants.PENTADECAGON_NOTES_MIN_LENGTH, Math.min(Constants.PENTADECAGON_NOTES_MAX_LENGTH, Math.floor(length)));
        const clampedA = Math.max(Constants.PENTADECAGON_NOTES_MIN_A, Math.min(Constants.PENTADECAGON_NOTES_MAX_A, Math.floor(scale)));
        const clampedDecay = Math.max(Constants.PENTADECAGON_NOTES_MIN_VELOCITY_DECAY, Math.min(Constants.PENTADECAGON_NOTES_MAX_VELOCITY_DECAY, velocityDecay));
        const useShape = Constants.PENTADECAGON_NOTES_SHAPES.includes(shape) ? shape : Constants.PENTADECAGON_NOTES_SHAPE_STANDARD;

        const tRangeMap = {
            [Constants.PENTADECAGON_NOTES_SHAPE_STANDARD]: [Constants.PENTADECAGON_NOTES_DEFAULT_T_MIN, Constants.PENTADECAGON_NOTES_DEFAULT_T_MAX],
            [Constants.PENTADECAGON_NOTES_SHAPE_INVERTED]: [Constants.PENTADECAGON_NOTES_INVERTED_T_MIN, Constants.PENTADECAGON_NOTES_INVERTED_T_MAX],
            [Constants.PENTADECAGON_NOTES_SHAPE_PENTADECAGON]: [Constants.PENTADECAGON_NOTES_PENTADECAGON_T_MIN, Constants.PENTADECAGON_NOTES_PENTADECAGON_T_MAX],
            [Constants.PENTADECAGON_NOTES_SHAPE_TIGHT]: [Constants.PENTADECAGON_NOTES_TIGHT_T_MIN, Constants.PENTADECAGON_NOTES_TIGHT_T_MAX]
        };
        const tRange = tRangeMap[useShape] || tRangeMap[Constants.PENTADECAGON_NOTES_SHAPE_STANDARD];
        const tMin = tRange[0];
        const tMax = tRange[1];

        this._captureUndoState(`Pentadecagon Notes (${useShape}, a=${clampedA}, N=${clampedLength}) on ${activeSeq.name}`);

        const numRows = activeSeq.data.length;
        const totalSteps = activeSeq.length;
        let pentadecagonCount = 0;
        const defaultVel = Constants.defaultVelocity || 0.7;
        const newNotes = [];

        const samples = [];
        const a = clampedA;
        const aOver14 = a / 14;
        for (let i = 0; i < clampedLength; i++) {
            const t = tMin + (tMax - tMin) * i / Math.max(1, clampedLength - 1);
            const cosT = Math.cos(t);
            const sinT = Math.sin(t);
            const cos14T = Math.cos(14 * t);
            const sin14T = Math.sin(14 * t);
            const x = a * cosT + aOver14 * cos14T;
            const y = a * sinT - aOver14 * sin14T;
            if (!isFinite(x) || !isFinite(y)) continue;
            samples.push({ x, y });
        }

        let xMin = Infinity, xMax = -Infinity, yMin = Infinity, yMax = -Infinity;
        for (const p of samples) {
            if (p.x < xMin) xMin = p.x;
            if (p.x > xMax) xMax = p.x;
            if (p.y < yMin) yMin = p.y;
            if (p.y > yMax) yMax = p.y;
        }
        if (!isFinite(xMin)) { xMin = -a; xMax = a; yMin = -a; yMax = a; }
        const xRange = Math.max(0.01, xMax - xMin);
        const yRange = Math.max(0.01, yMax - yMin);
        const colScale = (clampedLength - 1) / xRange;
        const rowScale = (clampedLength - 1) / (2 * yRange);

        for (let rowIndex = 0; rowIndex < numRows; rowIndex++) {
            const row = activeSeq.data[rowIndex];
            if (!row) continue;

            for (let col = 0; col < totalSteps; col++) {
                const stepData = row[col];
                if (!stepData || !stepData.active) continue;

                const origVel = (stepData.velocity !== undefined) ? stepData.velocity : defaultVel;

                for (let i = 0; i < samples.length; i++) {
                    const pt = samples[i];
                    const rowOffset = Math.max(-(clampedLength - 1) / 2, Math.min((clampedLength - 1) / 2, Math.round((pt.y - yMin) * rowScale - (clampedLength - 1) / 2)));
                    const colOffset = Math.max(0, Math.min(clampedLength - 1, Math.round((pt.x - xMin) * colScale)));
                    const targetRow = rowIndex + rowOffset;
                    const targetCol = col + colOffset;

                    if (targetRow < 0 || targetRow >= numRows) continue;
                    if (targetCol < 0 || targetCol >= totalSteps) continue;
                    if (skipOccupied && activeSeq.data[targetRow] && activeSeq.data[targetRow][targetCol] && activeSeq.data[targetRow][targetCol].active) continue;
                    if (targetRow === rowIndex && targetCol === col) continue;

                    const decayedVel = Math.max(0.05, Math.min(1.0, origVel * Math.pow(clampedDecay, i)));
                    newNotes.push({
                        rowIndex: targetRow,
                        col: targetCol,
                        velocity: Math.round(decayedVel * 100) / 100,
                        probability: stepData.probability
                    });
                }
            }
        }

        for (const note of newNotes) {
            if (!activeSeq.data[note.rowIndex]) {
                activeSeq.data[note.rowIndex] = Array(totalSteps).fill(null);
            }
            activeSeq.data[note.rowIndex][note.col] = {
                active: true,
                velocity: note.velocity,
                probability: note.probability
            };
            pentadecagonCount++;
        }

        return pentadecagonCount;
    }

"""

# ===== UI: 4 menu items for Pentadecagon Notes =====
UI_NEW_ITEMS = """                { label: `Pentadecagon Notes (Standard, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Pentadecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.pentadecagonNotes(32, 4, 0.95, 'standard', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Pentadecagon'd ${result} note(s) (standard, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to pentadecagon.", 2000); } } },
                { label: `Pentadecagon Notes (Inverted, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Pentadecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.pentadecagonNotes(32, 4, 0.95, 'inverted', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Pentadecagon'd ${result} note(s) (inverted, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to pentadecagon.", 2000); } } },
                { label: `Pentadecagon Notes (Pentadecagon, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Pentadecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.pentadecagonNotes(32, 4, 0.95, 'pentadecagon', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Pentadecagon'd ${result} note(s) (pentadecagon, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to pentadecagon.", 2000); } } },
                { label: `Pentadecagon Notes (Tight, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Pentadecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.pentadecagonNotes(32, 4, 0.95, 'tight', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Pentadecagon'd ${result} note(s) (tight, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to pentadecagon.", 2000); } } },

"""

# ===== 1. Update constants.js =====
constants_path = f"{REPO}/js/constants.js"
with open(constants_path) as f:
    constants = f.read()

old_app_version = "export const APP_VERSION = '2.411.0';\n"
new_app_version = "export const APP_VERSION = '2.412.0';\n"
if old_app_version not in constants:
    print("ERROR: APP_VERSION marker not found in constants.js", file=sys.stderr)
    sys.exit(1)
constants = constants.replace(old_app_version, PENTADECAGON_BLOCK + new_app_version)
with open(constants_path, "w") as f:
    f.write(constants)
print("constants.js: added PENTADECAGON_NOTES_* block, bumped APP_VERSION to 2.412.0")

# ===== 2. Update Track.js =====
track_path = f"{REPO}/js/Track.js"
with open(track_path) as f:
    track = f.read()

# Anchor: the end of tetradecagonNotes method. Use the unique final pattern.
anchor = """            tetradecagonCount++;
        }

        return tetradecagonCount;
    }

}
"""
if anchor not in track:
    print("ERROR: tetradecagonNotes closing anchor not found in Track.js", file=sys.stderr)
    sys.exit(1)
new_track = track.replace(anchor, """            tetradecagonCount++;
        }

        return tetradecagonCount;
    }

""" + PENTADECAGON_METHOD + "}\n", 1)
with open(track_path, "w") as f:
    f.write(new_track)
print("Track.js: added pentadecagonNotes method")

# ===== 3. Update ui.js =====
ui_path = f"{REPO}/js/ui.js"
with open(ui_path) as f:
    ui = f.read()

# Anchor: end of the Tetradecagon Notes (Tight, 32) menu item line.
ui_anchor = """                { label: `Tetradecagon Notes (Tight, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Tetradecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.tetradecagonNotes(32, 4, 0.95, 'tight', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Tetradecagon'd ${result} note(s) (tight, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to tetradecagon.", 2000); } } },

                { label: `Deltoid Notes (Standard, 32)`, action: () =>"""
if ui_anchor not in ui:
    print("ERROR: Tetradecagon menu anchor not found in ui.js", file=sys.stderr)
    sys.exit(1)
new_ui = ui.replace(ui_anchor, """                { label: `Tetradecagon Notes (Tight, 32)`, action: () => { if (localAppServices.captureStateForUndo) localAppServices.captureStateForUndo(`Tetradecagon Notes on ${currentTrackForMenu.name} (${currentActiveSeq.name})`); const result = currentTrackForMenu.tetradecagonNotes(32, 4, 0.95, 'tight', true); if (result > 0) { currentTrackForMenu.recreateToneSequence(true); showNotification(`Tetradecagon'd ${result} note(s) (tight, 32).`, 2000); if(localAppServices.updateTrackUI) localAppServices.updateTrackUI(track.id, 'sequencerContentChanged'); } else { showNotification("No notes to tetradecagon.", 2000); } } },
""" + UI_NEW_ITEMS + """                { label: `Deltoid Notes (Standard, 32)`, action: () =>""", 1)
with open(ui_path, "w") as f:
    f.write(new_ui)
print("ui.js: added 4 Pentadecagon Notes menu items")

print("DONE")
