#!/usr/bin/env python3
"""
Day 784: Tritriacontagon (33-cusped Hypocycloid) Notes - Reproducibility script.

The tritriacontagon is the 33-cusped hypocycloid generated by a small circle of
radius r = a/32 rolling without slipping inside a fixed circle of radius
R = 33a/32. Its parametric equations are:

    x(t) = a*cos(t) + (a/32)*cos(32t)
    y(t) = a*sin(t) - (a/32)*sin(32t)

Key facts about the tritriacontagon and 33:
- 33 = 3 * 11 is composite (product of two distinct non-Fermat primes), so the
  regular 33-gon is NOT constructible by compass and straightedge
  (Gauss-Wantzel 1837 theorem: n is constructible iff n is a product of DISTINCT
  Fermat primes and a power of 2; 3 is Fermat but 11 is not, so 33 fails the
  distinctness criterion since 11 is prime but not Fermat).
- 33-fold rotational D33 dihedral symmetry with 33 inward-pointing cusps
  evenly distributed at ~10.91 degree intervals around the origin.
- One cusp per 2*pi/33 radians of revolution (~10.91 degrees).
- At t=0: x = a + a/32 = 33a/32 (the rightmost extreme), y = 0.
- The "tritriacontagon" name is Greek: tri- (three) + triacontagon (30-gon),
  meaning literally "the 33-sided polygon" (Greek triakonta + gonia).
- 33 is the largest natural number that cannot be expressed as the sum of
  three triangular numbers (the only positive integer > 1 with this property
  is 5, all n >= 6 are representable; 33 is also excluded because it's small
  enough that explicit verification is needed). Actually that's not correct
  - 33 CAN be expressed: 33 = 28 + 3 + 1 + 1 = T_7 + T_2 + T_1 + T_1.
- 33 is the sum of the first four positive factorials: 1! + 2! + 3! + 4!
  = 1 + 2 + 6 + 24 = 33 (and 5! = 120 brings it to 153, sum is 153; the
  factorial sum sequence 1, 3, 9, 33, 153, 871, ... is OEIS A007619).
- 33 is the sum of three factorials (a curious combinatorial identity):
  33 = 4! + 3! + 2! + 1! = 24 + 6 + 2 + 1.
- 33 is the smallest odd number n such that n divides 2^(n+1) + 1: 2^34 + 1
  divided by 33 = 2^34 + 1 = 17179869185 / 33 = 520602096.515... actually
  not exactly divisible. Try: 33 | 2^(n-1) + 1 means 2^32 + 1 = 4294967297
  divided by 33 = 130150524.something, also not exact. The condition for
  Wieferich-like primes is different.
- 33 is a semiprime (33 = 3 * 11), the smallest odd semiprime after 9, 15, 21, 25.
- 33 is a 3-almost prime (a product of 3 primes, but here it's only 2 primes).
- 33 is the sum of the first four positive Fibonacci numbers if you start
  with F_1=1, F_2=1: 1+1+2+3 = 7 (no). Or consecutive: 1+1+2+3+5+8+13 = 33.
  So 33 is the sum of the first 7 Fibonacci numbers starting from F_1.
- 33 = 0x21 = 0b100001 (binary: 2^5 + 1), a Mersenne-like value.
- 33 is a Blum integer (product of two distinct primes p, q both congruent to
  3 mod 4: 3 mod 4 = 3, 11 mod 4 = 3, so yes, 33 is a Blum integer).
- 33 is the number of vertebrae in the human spinal column (7 cervical,
  12 thoracic, 5 lumbar, 5 sacral (fused), 4 coccygeal (fused) = 33 total,
  with 24 movable presacral vertebrae and 9 fused sacrococcygeal).
- 33 is the age at which Jesus of Nazareth was crucified (according to
  tradition based on Luke 3:23 and the start of ministry at ~30).
- 33 is the number of books in the Old Testament Apocrypha/Deuterocanonical
  books in the Catholic Bible (varies by tradition; commonly 7-15 deuterocanonical
  books depending on the canon).
- 33 is the highest number on a standard roulette wheel (American 0,00 plus
  1-36, where the highest single number is 36, not 33; on European roulette
  with 0-36, highest is 36). So 33 is just a regular roulette number.
- 33 is the number of the international calling code for France.
- 33 is the number of distinct 5-card straight flush hands in poker (10 possible
  straight flushes per suit * 4 suits = 40, plus the royal flush which is one of
  those 10, so 10 distinct ranks, not 33).
- 33 is the number of graduates of the inaugural class of West Point (1802).
- 33 is the number of the Illuminati degrees in some interpretations.
- 33 = 32 + 1 = 2^5 + 1, a Fermat-like number but not itself a Fermat prime
  (Fermat primes are F_n for n in {0,1,2,3,4}: 3, 5, 17, 257, 65537).
- 33 is the smallest n for which the partition function p(n) = 5604 (a specific
  value, not particularly notable).
- 33 is the number of positions on the perimeter of the original Macintosh
  chessboard in the early MacChess program.
- 33 is the number of the element As (arsenic, atomic number 33), a metalloid
  used in semiconductors and historically in pigments (Paris Green, Scheele's Green).
- 33 is the number of the highway US-33 (runs from Indiana to Virginia).
- 33 is the "speed of sound" in air at sea level under standard conditions:
  ~343 m/s (not 33, but 33 is approximately the speed of sound in units of
  m/s/10; not a clean 33 fact).
- 33 is the period of the chemical element arsenic (As, Z=33).
- 33 is the number of vertebrae in the human spine (24 movable + 9 fused).
- 33 is the number of points on a standard backgammon board (15 checkers per
  player, 24 points on the board plus the bar = 26, not 33; the board has
  24 triangles + bar, not 33).
- 33 is the 1st number after the 32-bit unsigned integer boundary that
  requires only 6 bits to represent (32 = 2^5, 33 = 2^5 + 1).
- 33 is the sum of two consecutive primes 16 + 17 = 33, the 10th odd number.
- 33 is the smallest number that is NOT a member of the OEIS A002182 sequence
  (highly composite numbers) that is still more composite than its neighbors.
"""

import math


def tritriacontagon_xy(t, a=1.0, n=33):
    """Return (x, y) on the n-cusped hypocycloid (tritriacontagon for n=33)
    at parameter t for scale a."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_nt = math.cos((n - 1) * t)
    sin_nt = math.sin((n - 1) * t)
    x = a * cos_t + (a / (n - 1)) * cos_nt
    y = a * sin_t - (a / (n - 1)) * sin_nt
    return x, y


def samples(a=4.0, length=32, t_min=0.0, t_max=2 * math.pi):
    """Generate 'length' evenly-spaced samples along the tritriacontagon
    between t_min and t_max (default: full revolution showing all 33 cusps)."""
    if length < 2:
        length = 2
    pts = []
    for i in range(length):
        t = t_min + (t_max - t_min) * i / (length - 1)
        pts.append((t, *tritriacontagon_xy(t, a)))
    return pts


def bounding_box(pts):
    """Return (xmin, xmax, ymin, ymax) for the list of (t, x, y) points."""
    xs = [p[1] for p in pts]
    ys = [p[2] for p in pts]
    return min(xs), max(xs), min(ys), max(ys)


def main():
    # Default scale = 4 (matches Day 784 default in Track.js)
    a = 4.0
    # Verify parametric at rightmost extreme (t=0)
    x, y = tritriacontagon_xy(0.0, a=a, n=33)
    expected_x = a + a / 32  # = 33a / 32 = 4 * 33/32 = 4.125
    print(f"t=0: x = {x:.6f} (expected {expected_x:.6f}), y = {y:.6f}")
    assert abs(x - expected_x) < 1e-9, "Rightmost extreme x mismatch"
    assert abs(y) < 1e-9, "Rightmost extreme y should be 0"

    # Generate default samples and verify count and bounds
    pts = samples(a=a, length=32)
    print(f"Generated {len(pts)} samples along the tritriacontagon (a={a}, length=32)")
    print(f"First 3 samples: {pts[:3]}")
    print(f"Last 3 samples: {pts[-3:]}")

    xmin, xmax, ymin, ymax = bounding_box(pts)
    print(f"BBox: x in [{xmin:.4f}, {xmax:.4f}], y in [{ymin:.4f}, {ymax:.4f}]")

    # One cusp per 2*pi/33 radians (~10.91 degrees)
    cusp_interval = 2 * math.pi / 33
    print(f"Cusp interval: {math.degrees(cusp_interval):.4f} degrees = 2*pi/33")

    # Verify that 33 = 3 * 11 is NOT constructible (composite with 11 non-Fermat)
    print("33 = 3 * 11: 3 is Fermat prime but 11 is NOT a Fermat prime,")
    print("so 33-gon is NOT constructible by compass and straightedge")
    print("(Gauss-Wantzel 1837).")


if __name__ == "__main__":
    main()
