#!/usr/bin/env python3
"""
Day 783: Dotriacontagon (32-cusped Hypocycloid) Notes - Reproducibility script.

The dotriacontagon is the 32-cusped hypocycloid generated by a small circle of
radius r = a/31 rolling without slipping inside a fixed circle of radius
R = 32a/31. Its parametric equations are:

    x(t) = a*cos(t) + (a/31)*cos(31t)
    y(t) = a*sin(t) - (a/31)*sin(31t)

Key facts about the dotriacontagon and 32:
- 32 = 2^5 is a pure power of 2, so the regular 32-gon IS constructible
  by compass and straightedge (Gauss-Wantzel 1837 theorem).
- 32-fold rotational symmetry is forbidden in classical crystallography
  (Bravais 1850) but appears in 32-fold quasicrystal approximants.
- One cusp per 2*pi/32 = pi/16 radians = 11.25 degrees of revolution.
- At t=0: x = a + a/31 = 32a/31 (the rightmost extreme), y = 0.
- The "dotriacontagon" name combines "do-" (two) + "triacontagon" (30-gon)
  literally meaning "the 32-sided polygon" (Greek dotriakonta + gonia).
"""

import math


def dotriacontagon_xy(t, a=1.0, n=32):
    """Return (x, y) on the n-cusped hypocycloid (dotriacontagon for n=32)
    at parameter t for scale a."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_nt = math.cos((n - 1) * t)
    sin_nt = math.sin((n - 1) * t)
    x = a * cos_t + (a / (n - 1)) * cos_nt
    y = a * sin_t - (a / (n - 1)) * sin_nt
    return x, y


def samples(a=4.0, length=32, t_min=0.0, t_max=2 * math.pi):
    """Generate 'length' evenly-spaced samples along the dotriacontagon
    between t_min and t_max (default: full revolution showing all 32 cusps)."""
    if length < 2:
        length = 2
    pts = []
    for i in range(length):
        t = t_min + (t_max - t_min) * i / (length - 1)
        pts.append((t, *dotriacontagon_xy(t, a)))
    return pts


def bounding_box(pts):
    xs = [p[1] for p in pts]
    ys = [p[2] for p in pts]
    return min(xs), max(xs), min(ys), max(ys)


def cusp_extremes(a=4.0, n=32):
    """Compute the rightmost extreme of the dotriacontagon (at t=0)."""
    t = 0
    x, y = dotriacontagon_xy(t, a, n)
    return t, x, y


def is_constructible(n):
    """Return True if the regular n-gon is constructible by compass
    and straightedge (Gauss-Wantzel 1837 theorem)."""
    fprimes = {3, 5, 17, 257, 65537}
    m = n
    # Divide out powers of 2
    while m % 2 == 0:
        m //= 2
    # Remaining m must be a product of DISTINCT Fermat primes
    seen = set()
    for p in fprimes:
        while m % p == 0:
            if p in seen:
                return False  # Not distinct
            seen.add(p)
            m //= p
    return m == 1


def main():
    print("=== Day 783: Dotriacontagon (32-cusped Hypocycloid) ===")
    print()

    a = 4.0
    n = 32
    print(f"Scale a = {a}, n = {n} cusps")
    print(f"Rolling circle radius r = a/(n-1) = {a}/{n-1} = {a/(n-1):.6f}")
    print(f"Fixed circle radius  R = a*n/(n-1) = {a}*{n}/{n-1} = {a*n/(n-1):.6f}")
    print(f"R/r = {(a*n/(n-1))/(a/(n-1)):.6f} (= n = {n})")
    print(f"Cusp angular spacing: 2*pi/n = {2*math.pi/n:.6f} rad = {360/n:.4f} deg")
    print()

    t, x, y = cusp_extremes(a, n)
    print(f"t=0 (rightmost extreme): x = {x:.6f}, y = {y:.6f}")
    expected_x = a * n / (n - 1)
    print(f"  expected x = a + a/(n-1) = a*n/(n-1) = {expected_x:.6f}")
    print()

    pts = samples(a=a, length=8, t_min=0, t_max=2 * math.pi)
    print(f"8 samples around the full dotriacontagon (t in [0, 2*pi]):")
    for t, x, y in pts:
        print(f"  t = {t:.6f}  x = {x:+.6f}  y = {y:+.6f}")
    print()

    bb = bounding_box(pts)
    print(f"Bounding box: x in [{bb[0]:.4f}, {bb[1]:.4f}], y in [{bb[2]:.4f}, {bb[3]:.4f}]")
    print()

    print(f"Is the regular {n}-gon constructible by compass and straightedge?")
    print(f"  n = {n} = 2^5 (pure power of 2). {is_constructible(n)}")
    print(f"  Gauss-Wantzel 1837: n IS constructible since n is a power of 2.")
    print()

    print(f"Total points generated: {len(pts)}")
    print(f"32-fold rotational D32 dihedral symmetry.")
    print(f"32 inward-pointing cusps at 360/32 = 11.25 degree intervals.")
    print(f"Parametric: x = a*cos(t) + (a/31)*cos(31t), y = a*sin(t) - (a/31)*sin(31t).")


if __name__ == "__main__":
    main()
