#!/usr/bin/env python3
"""
Day 773: Tetracosagon (24-cusped Hypocycloid) Notes reproducibility script.

Plots samples along the tetracosagon (24-cusped hypocycloid) curve to verify the
parametric form x = a*cos(t) + (a/23)*cos(23t), y = a*sin(t) - (a/23)*sin(23t).

The tetracosagon is the natural 24-cusped hypocycloid in the classical
1-2-3-...-24 cusp sequence of hypocycloids. Generated by a small circle of radius
r = a/23 rolling inside a fixed circle of radius R = 24a/23.

24 = 2^3 * 3 is a product of the Fermat prime 3 (2^(2^0)+1 = 3) and a power of 2 (2^3 = 8).
The regular tetracosagon IS constructible by compass and straightedge
(Gauss-Wantzel 1837 theorem). 24-fold rotational symmetry is forbidden in
classical crystallography (Bravais 1850) but allowed in 24-fold quasicrystal
approximants.
"""

import math


def tetracosagon_sample(a, t):
    """Return (x, y) on the tetracosagon (24-cusped hypocycloid) at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_23t = math.cos(23 * t)
    sin_23t = math.sin(23 * t)
    x = a * cos_t + (a / 23) * cos_23t
    y = a * sin_t - (a / 23) * sin_23t
    return x, y


def main():
    a = 4.0
    length = 32
    # STANDARD shape: t in [0, 2*pi]
    samples = [tetracosagon_sample(a, 2 * math.pi * i / max(1, length - 1))
               for i in range(length)]
    print(f"Tetracosagon (R/r=24, a={a}, N={length}) samples:")
    for i, (x, y) in enumerate(samples):
        print(f"  i={i:2d}  x={x:+.4f}  y={y:+.4f}")

    # Verify the rightmost extreme at t=0: x = a + a/23 = 24a/23
    x0, y0 = tetracosagon_sample(a, 0)
    expected_x0 = a + a / 23
    print(f"\nAt t=0: x={x0:+.6f} (expected {expected_x0:+.6f} = 24a/23), y={y0:+.6f} (expected 0)")

    # Cusps: 24 cusps per revolution, one cusp per 2pi/24 radians = 15 degrees
    print(f"\n24 cusps per revolution (one cusp every 2pi/24 = {2*math.pi/24:.4f} rad = {360/24:.2f} deg)")


if __name__ == "__main__":
    main()