"""
Day 781: Triacontagon (30-cusped Hypocycloid) Notes - reproducibility script.

The triacontagon is the natural 30-cusped hypocycloid (R/r = 30) generated by a
small circle of radius r = a/29 rolling inside a fixed circle of radius R = 30a/29.
Parametric form (Day 781):

    x(t) = a * cos(t) + (a/29) * cos(29 * t)
    y(t) = a * sin(t) - (a/29) * sin(29 * t)

At t = 0:
    x = a + a/29 = 30a/29
    y = 0

This reproduces the same parametric equations used by the JS implementation
(`triacontagonNotes` in `js/Track.js`).
"""

import math


def triacontagon(t: float, a: float = 4.0) -> tuple[float, float]:
    """Sample the triacontagon at parametric angle `t` with scale `a`."""
    return (
        a * math.cos(t) + (a / 29.0) * math.cos(29.0 * t),
        a * math.sin(t) - (a / 29.0) * math.sin(29.0 * t),
    )


def main() -> None:
    a = 4.0
    # Rightmost extreme (t = 0): x = a + a/29 = 30a/29, y = 0.
    x0, y0 = triacontagon(0.0, a)
    assert math.isclose(x0, a + a / 29.0)
    assert math.isclose(y0, 0.0, abs_tol=1e-12)

    # Walk around the curve and verify 30 cusps land near the rightmost extreme.
    cusps = []
    for k in range(30):
        t = 2.0 * math.pi * k / 30.0
        x, y = triacontagon(t, a)
        cusps.append((round(x, 6), round(y, 6)))
    print(f"a = {a}")
    print(f"rightmost extreme at t=0: x={x0:.6f}, y={y0:.6f}")
    print("30 cusp extrema (rounded):")
    for k, (x, y) in enumerate(cusps):
        print(f"  cusp {k:2d}: x={x:.6f}, y={y:.6f}")


if __name__ == "__main__":
    main()