#!/usr/bin/env python3
"""
Day 797: Hexatetracontagon (46-cusped Hypocycloid) Notes Feature
Reproducibility script for the Day 797 feature.

The hexatetracontagon (46-cusped hypocycloid) parametric equations are:
    x(t) = a * cos(t) + (a/45) * cos(45*t)
    y(t) = a * sin(t) - (a/45) * sin(45*t)

Generated by a small circle of radius r = a/45 rolling without slipping INSIDE
a fixed circle of radius R = 46a/45 (R/r = 46, 46 cusps per revolution).

46 = 2 * 23. NOT constructible by compass and straightedge (Gauss-Wantzel
1837 theorem: n is constructible iff n is a product of DISTINCT Fermat primes
and a power of 2; 23 is prime but NOT a Fermat prime, so 46 fails the
distinctness criterion despite 2 being a power of 2).
"""

import math
import json
import sys

N = 46  # 46-cusped hexatetracontagon
A = 4   # scale parameter


def hexatetracontagon_point(t, a=A):
    """Compute (x, y) on the hexatetracontagon at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_nt = math.cos((N - 1) * t)
    sin_nt = math.sin((N - 1) * t)
    x = a * cos_t + (a / (N - 1)) * cos_nt
    y = a * sin_t - (a / (N - 1)) * sin_nt
    return x, y


def main():
    print("Day 797: Hexatetracontagon (46-cusped Hypocycloid) Notes - Reproducibility")
    print("=" * 80)
    print()

    # Sample at 8 evenly-spaced t values across a full revolution
    samples = []
    for i in range(8):
        t = 2 * math.pi * i / 8
        x, y = hexatetracontagon_point(t)
        samples.append({"t": t, "x": x, "y": y})
        print(f"  t={t:.4f}: ({x:+.4f}, {y:+.4f})")

    print()
    print(f"Verified at t=0: x = a + a/45 = {A + A/45:.4f} (rightmost extreme)")
    print(f"  46 * a / 45 = {46 * A / 45:.4f}")
    print()
    print(f"R/r ratio: {N} (46 cusps per revolution)")
    print(f"Cusp interval: 360/{N} = {360/N:.4f} degrees")
    print(f"Constructible: False (23 is prime but not Fermat)")
    print()
    print(json.dumps({
        "day": 797,
        "feature": "Hexatetracontagon (46-cusped Hypocycloid) Notes",
        "N": N,
        "A": A,
        "R_over_r": N,
        "cusp_interval_deg": 360 / N,
        "constructible": False,
        "samples": samples,
    }, indent=2))


if __name__ == "__main__":
    main()
