#!/usr/bin/env python3
"""
Day 796: Pentatetracontagon (45-cusped Hypocycloid) Notes Feature
Reproducibility script for the Day 796 feature.

The pentatetracontagon (45-cusped hypocycloid) parametric equations are:
    x(t) = a * cos(t) + (a/44) * cos(44*t)
    y(t) = a * sin(t) - (a/44) * sin(44*t)

Generated by a small circle of radius r = a/44 rolling without slipping INSIDE
a fixed circle of radius R = 45a/44 (R/r = 45, 45 cusps per revolution).

45 = 2^2 * 11 = 4 * 11. NOT constructible by compass and straightedge (Gauss-Wantzel
1837 theorem: n is constructible iff n is a product of DISTINCT Fermat primes and a
power of 2; 11 is prime but NOT a Fermat prime, so 45 fails the criterion despite
2^2 being a power of 2).
"""

import math
import json
import sys

N = 45  # 45-cusped pentatetracontagon
A = 4   # scale parameter


def pentatetracontagon_point(t, a=A):
    """Compute (x, y) on the pentatetracontagon at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_nt = math.cos((N - 1) * t)
    sin_nt = math.sin((N - 1) * t)
    x = a * cos_t + (a / (N - 1)) * cos_nt
    y = a * sin_t - (a / (N - 1)) * sin_nt
    return x, y


def main():
    print("Day 796: Pentatetracontagon (45-cusped Hypocycloid) Notes - Reproducibility")
    print("=" * 80)
    print()

    # Sample at 8 evenly-spaced t values across a full revolution
    samples = []
    for i in range(8):
        t = 2 * math.pi * i / 8
        x, y = pentatetracontagon_point(t)
        samples.append({"t": t, "x": x, "y": y})
        print(f"  t={t:.4f}: ({x:+.4f}, {y:+.4f})")

    print()

    # Verify cusp count via the rightmost extreme
    # At t=0: cos(0) = 1, cos(44*0) = 1, so x = a + a/44 = 45a/44
    x_extreme, y_extreme = pentatetracontagon_point(0)
    expected = 45 * A / 44
    print(f"  Rightmost extreme: x={x_extreme:.6f}, y={y_extreme:.6f}")
    print(f"  Expected:          x={expected:.6f}, y=0")
    assert abs(x_extreme - expected) < 1e-9
    assert abs(y_extreme) < 1e-9
    print("  [OK] Rightmost extreme at (45a/44, 0)")
    print()

    # Verify the cusp interval (each cusp ~ 2pi/45 rad apart)
    cusp_interval_deg = 360 / N
    print(f"  Cusp interval: {cusp_interval_deg:.4f} degrees = 2pi/{N}")
    print()

    # Number of cusps per revolution = N
    print(f"  Cusps per revolution: {N}")
    print(f"  Rotational symmetry: D{N} dihedral")
    print(f"  Small circle radius: r = a/{N-1} = {A}/{N-1}")
    print(f"  Large circle radius: R = {N}a/{N-1} = {N * A / (N - 1):.6f}")
    print(f"  R/r = {N}")
    print()

    # Constructibility check
    FermatPrimes = [3, 5, 17, 257, 65537]
    is_constructible = (11 in [3, 5, 17, 257, 65537])  # 11 is NOT Fermat, so NOT constructible
    print(f"  45 = 2^2 * 11")
    print(f"  11 is prime: True")
    print(f"  11 is a Fermat prime: False (Fermat primes are 3, 5, 17, 257, 65537)")
    print(f"  45 is constructible by compass and straightedge: {is_constructible}")
    print()

    # Output JSON for reproducibility
    out = {
        "day": 796,
        "feature": "Pentatetracontagon (45-cusped Hypocycloid) Notes",
        "n_cusps": N,
        "parametric": {
            "x": f"a*cos(t) + (a/{N-1})*cos({N-1}*t)",
            "y": f"a*sin(t) - (a/{N-1})*sin({N-1}*t)",
        },
        "samples": samples,
        "rightmost_extreme": {"x": x_extreme, "y": y_extreme, "expected": expected},
        "constructibility": {
            "factorization": "2^2 * 11",
            "is_fermat_prime_11": False,
            "is_constructible": is_constructible,
        },
        "version": "2.442.0",
    }
    print(json.dumps(out, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
