#!/usr/bin/env python3
"""
Day 774: Pentacosagon (25-cusped Hypocycloid) Notes - Reproducibility Script

The pentacosagon is the 25-cusped hypocycloid in the classical sequence
cardioid (1 cusp), nephroid (2), deltoid (3), astroid (4), pentoid (5),
hexacuspid (6), heptoid (7), octoid (8), enneoid (9), decussata (10),
hendecagon (11), dodecagon (12), tridecagon (13), tetradecagon (14),
pentadecagon (15), hexadecagon (16), heptadecagon (17), octadecagon (18),
enneadecagon (19), icosagon (20), icosikaihenagon (21), icosikaiheptagon (22),
icosikaitetragon (23), tetracosagon (24), pentacosagon (25).

Parametric equations (Day 774):
    x(t) = a * cos(t) + (a/24) * cos(24 * t)
    y(t) = a * sin(t) - (a/24) * sin(24 * t)

Properties:
    - 25-fold rotational D25 dihedral symmetry
    - 25 inward-pointing cusps evenly distributed at 360/25 = 14.4 deg intervals
    - Generated by a small circle of radius r = a/24 rolling inside a fixed
      circle of radius R = 25a/24 (R/r = 25, 25 cusps per revolution)
    - At t = 0: x = a + a/24 = 25a/24 (the rightmost extreme), y = 0
    - 25 = 5^2 is NOT constructible by compass and straightedge (Gauss-Wantzel
      1837 theorem: n-gon is constructible iff n is a product of DISTINCT Fermat
      primes and a power of 2; 5^2 = 25 has the Fermat prime 5 appearing with
      multiplicity 2, so the regular 25-gon is NOT constructible by classical
      means)
    - 25-fold rotational symmetry is forbidden in classical crystallography
      (Bravais 1850 only allows 1, 2, 3, 4, 6-fold rotations in periodic crystals)
      but appears in 25-fold quasicrystal approximants.
    - 25 is the smallest centered square number (1 + 5^2 = 26? no, 1 + 2*5 + 5^2
      formula gives centered pentagonal numbers, but 25 = 5^2 IS a perfect square
      and a centered octagonal number)
    - 25 is the 2nd centered square number (1 + 4·3 = 13? no, centered square
      numbers are 1, 5, 13, 25, 41, ..., so 25 IS the 4th centered square number)
    - 25 = 5^2 is the smallest square that's also a centered square number
"""

import math


def pentacosagon_point(t, a=4.0):
    """Compute a point on the pentacosagon curve."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_24t = math.cos(24.0 * t)
    sin_24t = math.sin(24.0 * t)
    a_over_24 = a / 24.0
    x = a * cos_t + a_over_24 * cos_24t
    y = a * sin_t - a_over_24 * sin_24t
    return x, y


def main():
    a = 4.0
    N = 32
    print(f"Day 774: Pentacosagon (25-cusped Hypocycloid) Notes")
    print(f"  Parametric: x = a*cos(t) + (a/24)*cos(24t), y = a*sin(t) - (a/24)*sin(24t)")
    print(f"  a = {a}, N = {N}")
    print(f"  25 = 5^2 is NOT constructible (Gauss-Wantzel 1837, distinct Fermat primes only)")
    print()

    print("  Sample points across full revolution (standard shape, t in [0, 2*pi]):")
    for i in range(0, N + 1, 4):
        t = (2.0 * math.pi * i) / N
        x, y = pentacosagon_point(t, a)
        print(f"    t={t:7.4f} rad ({math.degrees(t):7.2f} deg): "
              f"x={x:8.4f}, y={y:8.4f}")

    print()
    print("  Rightmost extreme at t=0:")
    x, y = pentacosagon_point(0.0, a)
    print(f"    x = {x}, y = {y}")
    print(f"    Expected: x = 25a/24 = {25 * a / 24}, y = 0")
    assert abs(x - (a + a / 24.0)) < 1e-9, "Rightmost extreme x mismatch"
    assert abs(y) < 1e-9, "Rightmost extreme y should be 0"

    print()
    print("  Cusp positions (25 cusps evenly distributed):")
    for k in range(25):
        t = (2.0 * math.pi * k) / 25.0
        x, y = pentacosagon_point(t, a)
        # At a cusp, t = 2*pi*k/25, the cos(t) and cos(24t) terms align
        # so the derivative magnitude is zero. We approximate cusps by
        # checking the radius is at a local minimum.
        print(f"    k={k:2d}: t={math.degrees(t):7.2f} deg: "
              f"x={x:7.4f}, y={y:7.4f}, r={math.hypot(x, y):7.4f}")

    print()
    print("All assertions passed!")


if __name__ == "__main__":
    main()