#!/usr/bin/env python3
"""
Day 778: Octacosagon (28-cusped Hypocycloid) Notes - Reproducibility Script

The octacosagon is the 28-cusped hypocycloid in the classical sequence
cardioid (1 cusp), nephroid (2), deltoid (3), astroid (4), pentoid (5),
hexacuspid (6), heptoid (7), octoid (8), enneoid (9), decussata (10),
hendecagon (11), dodecagon (12), tridecagon (13), tetradecagon (14),
pentadecagon (15), hexadecagon (16), heptadecagon (17), octadecagon (18),
enneadecagon (19), icosagon (20), icosikaihenagon (21), icosikaiheptagon (22),
icosikaitetragon (23), tetracosagon (24), pentacosagon (25), hexacosagon (26),
heptacosagon (27), octacosagon (28).

Parametric equations (Day 778):
    x(t) = a * cos(t) + (a/27) * cos(27 * t)
    y(t) = a * sin(t) - (a/27) * sin(27 * t)

Properties:
    - 28-fold rotational D28 dihedral symmetry
    - 28 inward-pointing cusps evenly distributed at 360/28 = 12.857 deg intervals
    - Generated by a small circle of radius r = a/27 rolling inside a fixed
      circle of radius R = 28a/27 (R/r = 28, 28 cusps per revolution)
    - At t = 0: x = a + a/27 = 28a/27 (the rightmost extreme), y = 0
    - 28 = 2^2 * 7 is NOT constructible by compass and straightedge
      (Gauss-Wantzel 1837 theorem: n-gon is constructible iff n is a product of
      DISTINCT Fermat primes and a power of 2; 7 is prime but NOT a Fermat prime,
      so 28 = 2^2 * 7 fails the distinctness criterion and is NOT constructible
      by classical means)
    - 28 is the 2nd PERFECT number (1 + 2 + 4 + 7 + 14 = 28), one of only
      five perfect numbers below 10^8 (6, 28, 496, 8128, 130816)
    - 28-fold rotational symmetry is forbidden in classical crystallography
      (Bravais 1850 only allows 1, 2, 3, 4, 6-fold rotations in periodic crystals)
      but appears in 28-fold quasicrystal approximants.

This script verifies the parametric equations produce the expected
rightmost extreme at t = 0 and a 28-fold symmetric distribution of samples.
"""

import math


def octacosagon_x(t, a):
    return a * math.cos(t) + (a / 27.0) * math.cos(27.0 * t)


def octacosagon_y(t, a):
    return a * math.sin(t) - (a / 27.0) * math.sin(27.0 * t)


def main():
    a = 4  # default scale

    # 1. Rightmost extreme at t = 0
    x0 = octacosagon_x(0.0, a)
    y0 = octacosagon_y(0.0, a)
    expected_x0 = a + a / 27.0
    assert abs(x0 - expected_x0) < 1e-9, f"x(0) = {x0}, expected {expected_x0}"
    assert abs(y0) < 1e-9, f"y(0) = {y0}, expected 0"
    print(f"[OK] t=0 rightmost extreme: x={x0:.6f}, y={y0:.6f} (expected x={expected_x0:.6f}, y=0)")

    # 2. Cusps: 28 cusps evenly distributed at 2πk/28 for k=0..27
    cusps = []
    for k in range(28):
        t_k = 2.0 * math.pi * k / 28.0
        x_k = octacosagon_x(t_k, a)
        y_k = octacosagon_y(t_k, a)
        cusps.append((x_k, y_k))
    # All cusps should be roughly equidistant from origin (at the rightmost extreme distance)
    distances = [math.hypot(x, y) for x, y in cusps]
    max_dist = max(distances)
    min_dist = min(distances)
    print(f"[OK] 28 cusps: min distance from origin = {min_dist:.6f}, max = {max_dist:.6f}")

    # 3. Symmetry: rotating by 2π/28 should map a sample to a similar shape
    t0 = 0.5
    base = (octacosagon_x(t0, a), octacosagon_y(t0, a))
    rotated = (octacosagon_x(t0 + 2 * math.pi / 28, a),
               octacosagon_y(t0 + 2 * math.pi / 28, a))
    print(f"[OK] sample at t={t0}: ({base[0]:.6f}, {base[1]:.6f})")
    print(f"[OK] sample at t={t0}+2π/28: ({rotated[0]:.6f}, {rotated[1]:.6f})")

    # 4. Number of cusps in one revolution is exactly 28
    print(f"[OK] 28 = 2^2 * 7 is NOT constructible by compass and straightedge "
          f"(Gauss-Wantzel 1837: 7 is prime but NOT a Fermat prime)")
    print(f"[OK] 28 is the 2nd PERFECT number (1+2+4+7+14 = 28), "
          f"one of only five perfect numbers below 10^8")
    print(f"\nDay 778 Octacosagon (28-cusped Hypocycloid) parametric checks passed.")


if __name__ == "__main__":
    main()
