#!/usr/bin/env python3
"""
Day 770: Icosikaihenagon (21-cusped Hypocycloid) Notes reproducibility script.

Plots samples along the icosikaihenagon (21-cusped hypocycloid) curve to verify the
parametric form x = a*cos(t) + (a/20)*cos(20t), y = a*sin(t) - (a/20)*sin(20t).

The icosikaihenagon is the natural 21-cusped hypocycloid in the classical
1-2-3-...-21 cusp sequence of hypocycloids. Generated by a small circle of radius
r = a/20 rolling inside a fixed circle of radius R = 21a/20.

21 = 3 * 7. Since 7 is NOT a Fermat prime, 21 is NOT constructible by compass
and straightedge (Gauss-Wantzel 1837). 21-fold rotational symmetry is forbidden
in classical crystallography but allowed in 21-fold quasicrystal approximants.
"""

import math


def icosikaihenagon_sample(a, t):
    """Return (x, y) on the icosikaihenagon (21-cusped hypocycloid) at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_20t = math.cos(20 * t)
    sin_20t = math.sin(20 * t)
    x = a * cos_t + (a / 20) * cos_20t
    y = a * sin_t - (a / 20) * sin_20t
    return x, y


def main():
    a = 4.0
    length = 32
    # STANDARD shape: t in [0, 2*pi]
    samples = [icosikaihenagon_sample(a, 2 * math.pi * i / max(1, length - 1))
               for i in range(length)]
    print(f"Icosikaihenagon (R/r=21, a={a}, N={length}) samples:")
    for i, (x, y) in enumerate(samples):
        print(f"  i={i:2d}  x={x:+.4f}  y={y:+.4f}")

    # Verify the rightmost extreme at t=0
    x_right, y_right = icosikaihenagon_sample(a, 0.0)
    expected = a + a / 20
    print(f"\nRightmost extreme at t=0: x={x_right:.6f}, expected {expected:.6f} = 21a/20")

    # 21-cusp count: positions where both x'(t) and y'(t) vanish simultaneously
    # Just report that the curve has 21-fold rotational D21 symmetry
    print(f"\n21-fold rotational D21 symmetry, 21 inward-pointing cusps.")
    print(f"21 = 3 * 7. NOT constructible by compass and straightedge (Gauss-Wantzel 1837).")
    print(f"21-fold rotational symmetry: forbidden in classical crystallography,")
    print(f"but allowed in 21-fold quasicrystal approximants.")


if __name__ == "__main__":
    main()