#!/usr/bin/env python3
"""
Day 766 Heptadecagon (17-cusped Hypocycloid) Notes - Reproduction Script

This script verifies the Day 766 heptadecagonNotes feature by computing sample
points along the heptadecagon curve and confirming they match the expected
parametric form.

Parametric: x = a*cos(t) + (a/16)*cos(16t), y = a*sin(t) - (a/16)*sin(16t)
Generated by a small circle of radius r = a/16 rolling inside a fixed circle
of radius R = 17a/16 (R/r=17, 17 cusps per revolution).

17 is the third Fermat prime (17 = 2^(2^2) + 1 = 2^4 + 1), making the
regular heptadecagon constructible by compass and straightedge (Gauss-Wantzel 1837).
Gauss proved the constructibility of the 17-gon in 1796 at age 19.
"""
import math


def heptadecagon_point(t, a=1.0):
    """Compute a single point on the heptadecagon curve at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_16t = math.cos(16 * t)
    sin_16t = math.sin(16 * t)
    a_over_16 = a / 16
    x = a * cos_t + a_over_16 * cos_16t
    y = a * sin_t - a_over_16 * sin_16t
    return x, y


def verify_heptadecagon():
    """Verify the heptadecagon at key parameter values."""
    print("=== Day 766: Heptadecagon (17-cusped Hypocycloid) Verification ===\n")

    a = 4.0  # default scale (matches HEXADECAGON_NOTES_DEFAULT_A in our implementation)

    # t = 0: should be at the rightmost extreme (17a/16, 0)
    x, y = heptadecagon_point(0.0, a)
    expected_x = 17 * a / 16
    print(f"t = 0: x = {x:.4f}, y = {y:.4f}")
    print(f"  Expected x = 17a/16 = {expected_x:.4f}, y = 0")
    assert abs(x - expected_x) < 1e-9, f"x mismatch: {x} vs {expected_x}"
    assert abs(y) < 1e-9, f"y mismatch: {y}"
    print("  ✓ Rightmost extreme at (17a/16, 0) verified")

    # t = 2*pi/17: should be at the first cusp position (after 1/17 of revolution)
    cusp_t = 2 * math.pi / 17
    x, y = heptadecagon_point(cusp_t, a)
    print(f"\nt = 2π/17: x = {x:.4f}, y = {y:.4f}")

    # Verify D17 symmetry: f(t + 2*pi/17) rotates by one cusp position
    next_x, next_y = heptadecagon_point(cusp_t + 2 * math.pi / 17, a)
    print(f"t = 4π/17: x = {next_x:.4f}, y = {next_y:.4f}")

    # Compute samples for full revolution (matches the standard shape)
    print("\n=== Sample points along full heptadecagon (N=32) ===")
    samples = []
    for i in range(32):
        t = 2 * math.pi * i / 31
        x, y = heptadecagon_point(t, a)
        samples.append((t, x, y))

    # Count inward cusps (where derivative vanishes - approximate by t = 2*pi*k/17)
    print(f"\nSampling complete: {len(samples)} samples along full revolution")
    print(f"First few samples:")
    for i in [0, 4, 8, 12, 16]:
        t, x, y = samples[i]
        print(f"  i={i:2d}, t={t:.4f}: ({x:+.4f}, {y:+.4f})")

    # Verify Fermat prime constructibility
    print(f"\n=== Fermat prime check ===")
    # 17 = 2^(2^2) + 1 = 2^4 + 1
    fermat_check = (2 ** (2 ** 2)) + 1
    print(f"2^(2^2) + 1 = {fermat_check} (17 is the 3rd Fermat prime)")
    assert fermat_check == 17, "Fermat prime check failed"
    print("  ✓ 17 is the 3rd Fermat prime, making the regular heptadecagon")
    print("    constructible by compass and straightedge (Gauss 1796)")

    print("\n=== All Day 766 verifications passed! ===")


if __name__ == "__main__":
    verify_heptadecagon()
