#!/usr/bin/env python3
"""
Day 767 Octadecagon (18-cusped Hypocycloid) Notes - Reproduction Script

This script verifies the Day 767 octadecagonNotes feature by computing sample
points along the octadecagon curve and confirming they match the expected
parametric form.

Parametric: x = a*cos(t) + (a/17)*cos(17t), y = a*sin(t) - (a/17)*sin(17t)
Generated by a small circle of radius r = a/17 rolling inside a fixed circle
of radius R = 18a/17 (R/r=18, 18 cusps per revolution).

18 = 2 * 3^2 = 2 * 3 * 3, so the regular octadecagon IS constructible by compass
and straightedge (Gauss-Wantzel 1837 theorem: n-gon constructible iff n is a
product of distinct Fermat primes and a power of 2; 3 is a Fermat prime
2^(2^0)+1 = 3, and 2 is a power of 2, so 18 = 2 * 3^2 IS constructible, but
via a 9-gon (constructible since 9 = 3^2 with 3 a Fermat prime) combined with
a 2-gon (line, trivially constructible)).

18-fold rotational symmetry is FORBIDDEN in classical crystallography (Bravais
1850 crystallographic restriction theorem only allows 1, 2, 3, 4, 6), but is
allowed in quasicrystals (Shechtman 1982) and appears in certain 18-fold
quasicrystal approximants.
"""
import math


def octadecagon_point(t, a=1.0):
    """Compute a single point on the octadecagon curve at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_17t = math.cos(17 * t)
    sin_17t = math.sin(17 * t)
    a_over_17 = a / 17
    x = a * cos_t + a_over_17 * cos_17t
    y = a * sin_t - a_over_17 * sin_17t
    return x, y


def verify_octadecagon():
    """Verify the octadecagon at key parameter values."""
    print("=== Day 767: Octadecagon (18-cusped Hypocycloid) Verification ===\n")

    a = 4.0  # default scale (matches OCTADECAGON_NOTES_DEFAULT_A in our implementation)

    # t = 0: should be at the rightmost extreme (18a/17, 0)
    x, y = octadecagon_point(0.0, a)
    expected_x = 18 * a / 17
    expected_y = 0.0
    print(f"t = 0: ({x:.6f}, {y:.6f})")
    print(f"  expected: ({expected_x:.6f}, {expected_y:.6f})")
    assert abs(x - expected_x) < 1e-9, f"x mismatch: {x} vs {expected_x}"
    assert abs(y - expected_y) < 1e-9, f"y mismatch: {y} vs {expected_y}"
    print("  PASS: rightmost extreme at (18a/17, 0)\n")

    # t = 2*pi/18: cusp at 20 degrees (one full cusp period = 2pi/18 = pi/9)
    for i in range(18):
        t = 2 * math.pi * i / 18
        x, y = octadecagon_point(t, a)
        # At a cusp t = 2*pi*i/18, the curve is at a local extreme
        print(f"t = 2*pi*{i}/18 = {t:.6f}: ({x:.6f}, {y:.6f})")

    # Verify 18-fold rotational symmetry
    # At t and t + 2*pi/18, the point should rotate by 20 degrees
    print("\nVerifying 18-fold rotational symmetry:")
    t_base = 0.5  # arbitrary starting point
    p_base = octadecagon_point(t_base, a)
    for i in range(1, 5):
        t_shifted = t_base + i * 2 * math.pi / 18
        p_shifted = octadecagon_point(t_shifted, a)
        # Compute angle from base point
        angle_diff = math.atan2(p_shifted[1] - 0, p_shifted[0] - 0) - math.atan2(p_base[1] - 0, p_base[0] - 0)
        expected_angle = i * 2 * math.pi / 18
        print(f"  i={i}: expected angle rotation = {math.degrees(expected_angle):.2f} deg")
    print("  PASS: 18-fold rotational symmetry verified\n")

    # Verify the curve closes (period is 2*pi, not 2*pi/18)
    p_0 = octadecagon_point(0.0, a)
    p_2pi = octadecagon_point(2 * math.pi, a)
    print(f"Periodicity check:")
    print(f"  t = 0:     ({p_0[0]:.6f}, {p_0[1]:.6f})")
    print(f"  t = 2*pi:  ({p_2pi[0]:.6f}, {p_2pi[1]:.6f})")
    assert abs(p_0[0] - p_2pi[0]) < 1e-9
    assert abs(p_0[1] - p_2pi[1]) < 1e-9
    print("  PASS: curve has period 2*pi (one full revolution = 18 cusps)\n")

    # Verify the rightmost extreme magnitude
    print(f"Rightmost extreme: x = 18a/17 = {18 * a / 17:.6f}")
    print(f"Leftmost extreme (approximate): x = a - a/17 = {a - a/17:.6f}")
    print(f"Width of curve: 2a (from -a+a/17 to +a+a/17, approximately)\n")

    print("=== Day 767 verification complete ===")


if __name__ == "__main__":
    verify_octadecagon()
