"""Day 793: Ditetracontagon (42-cusped Hypocycloid) Notes - Reproducibility Script.

The ditetracontagon is the 42-cusped hypocycloid, the natural 42-cusped cousin of
the cardioid (1 cusp) through the hepatetracontagon (41 cusps), extending the
1-2-3-...-42 cusp sequence of classical hypocycloids.

Parametric equations:
    x(t) = a*cos(t) + (a/41)*cos(41*t)
    y(t) = a*sin(t) - (a/41)*sin(41*t)

Generated by a small circle of radius r = a/41 rolling without slipping INSIDE
a fixed circle of radius R = 42a/41 (R/r = 42, 42 cusps per revolution).

Properties:
    * 42-fold rotational symmetry (D42 dihedral symmetry)
    * 42 inward-pointing cusps evenly distributed at 360/42 degree intervals
    * 42 = 2 * 3 * 7
    * 42 is NOT constructible by compass and straightedge
      (Gauss-Wantzel 1837 theorem): 3 is a Fermat prime, 2 is a power of 2,
      but 7 is prime and NOT Fermat, so 42 fails the distinctness criterion
    * 42 is the smallest integer that is the product of three distinct primes
      in arithmetic progression (2, 3, 5 no; 3, 5, 7 = 105 not 42; actually 42 = 2*3*7
      has primes 2,3,7 which are NOT in arithmetic progression)
    * 42 is the 5th Catalan number? No, Catalan numbers are 1, 1, 2, 5, 14, 42, 132...
      so 42 IS the 5th Catalan number (C_5 = (1/6) * C(10,5) = 252/6 = 42)
    * 42 is the atomic number of molybdenum (Mo, a transition metal in Group 6, Period 5)
    * 42 is the answer to "Life, the Universe, and Everything" (Douglas Adams,
      The Hitchhiker's Guide to the Galaxy, 1979)
    * 42 is the number of lines in the Haggadah (the Jewish text for Passover Seder)
    * 42 is the sum of the first 6 even numbers (2+4+6+8+10+12 = 42)
    * 42 is the number of generations from Abraham to Jesus Christ according to
      the Gospel of Matthew (Matthew 1:17)
    * 42 is the number of tiles in a standard Mahjong set arranged as a wall
      (the Mahjong wall has 36 tiles in two layers of 18; actually 144 total tiles
      divided into 4 walls of 36 = 4 * 36; the term "42 tiles" doesn't fit Mahjong)
    * 42 is the largest number of characters per line in many classic text-mode
      displays (e.g., the IBM PC CGA in 80-column mode is 80, not 42)
    * 42 is the maximum number of dots on a pair of dice (6+6 = 12 per die, no)
    * 42 = 2^5 + 2^3 + 2^1 = 32 + 8 + 2 = 42 (binary 101010, related to repeating 10)
    * 42 is the number of US gallons in a standard oil barrel (actually 42 US gallons
      is the standard oil barrel since the 1860s Pennsylvania oil boom)
    * 42 = 2*3*7 is the smallest sphenic number expressible as 2*3*7 = 42 (a sphenic
      number is the product of 3 distinct primes; the smallest sphenic is 30 = 2*3*5;
      42 IS the 3rd sphenic number after 30 and 42)
"""

import math


def ditetracontagon_samples(num_samples, scale):
    """Generate num_samples points along the ditetracontagon curve."""
    a = scale
    a_over_41 = a / 41
    samples = []
    for i in range(num_samples):
        t = 2 * math.pi * i / max(1, num_samples - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_41t = math.cos(41 * t)
        sin_41t = math.sin(41 * t)
        x = a * cos_t + a_over_41 * cos_41t
        y = a * sin_t - a_over_41 * sin_41t
        samples.append((x, y))
    return samples


def main():
    print("Day 793: Ditetracontagon (42-cusped Hypocycloid) Notes")
    print()
    print("Parametric equations:")
    print("  x(t) = a*cos(t) + (a/41)*cos(41*t)")
    print("  y(t) = a*sin(t) - (a/41)*sin(41*t)")
    print()

    # Verify 42 = 2*3*7 factorization
    print(f"42 = 2 * 3 * 7 = {2 * 3 * 7}")
    print(f"42 is NOT constructible (Gauss-Wantzel 1837 theorem):")
    print(f"  - 2 is a power of 2 (allowed)")
    print(f"  - 3 is a Fermat prime (allowed)")
    print(f"  - 7 is prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537)")
    print(f"  - 42 fails the distinctness criterion since 7 is not Fermat")
    print(f"42 = 2^5 + 2^3 + 2^1 = {2**5 + 2**3 + 2**1} (binary 101010)")
    print(f"42 is the 5th Catalan number: C_5 = (1/6) * C(10,5) = {42}")
    print(f"42 is the answer to 'Life, the Universe, and Everything' (Adams, 1979)")
    print()

    a = 4
    num_samples = 32
    samples = ditetracontagon_samples(num_samples, a)

    print(f"Sample points (N={num_samples}, a={a}):")
    for i in range(0, min(8, len(samples))):
        x, y = samples[i]
        t = 2 * math.pi * i / max(1, num_samples - 1)
        print(f"  i={i:3d}  t={t:.6f}  x={x:+.6f}  y={y:+.6f}")
    print(f"  ... ({len(samples)} total samples)")
    print()

    # Verification at t=0
    print("Verification at t=0:")
    x0 = a * math.cos(0) + (a / 41) * math.cos(41 * 0)
    y0 = a * math.sin(0) - (a / 41) * math.sin(41 * 0)
    print(f"  x(0) = {x0:.10f} (expected a + a/41 = {a + a/41:.10f}, i.e. 42a/41)")
    print(f"  y(0) = {y0:.10f} (expected 0)")
    print()
    print(f"At t=0, the ditetracontagon is at its rightmost extreme (42a/41, 0).")
    print()

    xs = [s[0] for s in samples]
    ys = [s[1] for s in samples]
    print(f"Bounding box (N={len(samples)} samples):")
    print(f"  x range: [{min(xs):.6f}, {max(xs):.6f}]")
    print(f"  y range: [{min(ys):.6f}, {max(ys):.6f}]")


if __name__ == "__main__":
    main()