#!/usr/bin/env python3
"""Day 779 Enneacosagon (29-cusped Hypocycloid) Notes reproducibility script.

The enneacosagon is the natural 29-cusped hypocycloid in the classical
1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-18-19-20-21-22-23-24-25-26-27-28-29
cusp sequence of classical hypocycloids.

Parametric equations:
    x(t) = a * cos(t) + (a/28) * cos(28*t)
    y(t) = a * sin(t) - (a/28) * sin(28*t)

Generated by a small circle of radius r = a/28 rolling inside a fixed circle
of radius R = 29a/28. 29-fold rotational D29 dihedral symmetry with 29 inward-
pointing cusps evenly distributed at 360/29 ≈ 12.41 degree intervals.

29 is a prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537),
so the regular enneacosagon is NOT constructible by compass and straightedge
(Gauss-Wantzel 1837).

Reference: track.enneacosagonNotes(length, scale, velocityDecay, shape, skipOccupied)
in js/Track.js — a SnugOS feature added 2026-06-25.
"""

import math


def enneacosagon_samples(a, length, t_min=0.0, t_max=2 * math.pi):
    """Return list of (x, y) samples along the enneacosagon curve."""
    if length < 1:
        return []
    samples = []
    a_over_28 = a / 28
    for i in range(length):
        t = t_min + (t_max - t_min) * i / max(1, length - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_28t = math.cos(28 * t)
        sin_28t = math.sin(28 * t)
        x = a * cos_t + a_over_28 * cos_28t
        y = a * sin_t - a_over_28 * sin_28t
        samples.append((x, y))
    return samples


def rightmost_extreme(a):
    """The rightmost extreme of the enneacosagon is at t=0: (29a/28, 0)."""
    return (a + a / 28, 0.0)


if __name__ == "__main__":
    a = 4
    pts = enneacosagon_samples(a, 32)
    rx, ry = rightmost_extreme(a)
    print(f"Day 779 Enneacosagon (29-cusped Hypocycloid) — a={a}, 32 samples")
    print(f"  Rightmost extreme: ({rx:.4f}, {ry:.4f})  [expected: (29a/28, 0) = ({29*a/28:.4f}, 0.0)]")
    print(f"  First 3 samples: {pts[:3]}")
    print(f"  Last 3 samples: {pts[-3:]}")
    print(f"  29 is prime but NOT a Fermat prime, so NOT constructible by compass and straightedge.")
    print(f"  29 is the 10th prime, a Sophie Germain prime (2*29+1=59 is also prime).")
