#!/usr/bin/env python3
"""
Day 771: Icosikaiheptagon (22-cusped Hypocycloid) Notes reproducibility script.

Plots samples along the icosikaiheptagon (22-cusped hypocycloid) curve to verify the
parametric form x = a*cos(t) + (a/21)*cos(21t), y = a*sin(t) - (a/21)*sin(21t).

The icosikaiheptagon is the natural 22-cusped hypocycloid in the classical
1-2-3-...-22 cusp sequence of hypocycloids. Generated by a small circle of radius
r = a/21 rolling inside a fixed circle of radius R = 22a/21.

22 = 2 * 11. Since 11 is NOT a Fermat prime, 22 is NOT constructible by compass
and straightedge (Gauss-Wantzel 1837). 22-fold rotational symmetry is forbidden
in classical crystallography but allowed in 22-fold quasicrystal approximants.
"""

import math


def icosikaiheptagon_sample(a, t):
    """Return (x, y) on the icosikaiheptagon (22-cusped hypocycloid) at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_21t = math.cos(21 * t)
    sin_21t = math.sin(21 * t)
    x = a * cos_t + (a / 21) * cos_21t
    y = a * sin_t - (a / 21) * sin_21t
    return x, y


def main():
    a = 4.0
    length = 32
    # STANDARD shape: t in [0, 2*pi]
    samples = [icosikaiheptagon_sample(a, 2 * math.pi * i / max(1, length - 1))
               for i in range(length)]
    print(f"Icosikaiheptagon (R/r=22, a={a}, N={length}) samples:")
    for i, (x, y) in enumerate(samples):
        print(f"  i={i:2d}  x={x:+.4f}  y={y:+.4f}")

    # Verify the rightmost extreme at t=0: x = a + a/21 = 22a/21
    x0, y0 = icosikaiheptagon_sample(a, 0)
    expected_x0 = a + a / 21
    print(f"\nAt t=0: x={x0:+.6f} (expected {expected_x0:+.6f} = 22a/21), y={y0:+.6f} (expected 0)")

    # Cusps: 22 cusps per revolution, one cusp per 2pi/22 radians
    print(f"\n22 cusps per revolution (one cusp every 2pi/22 = {2*math.pi/22:.4f} rad = {360/22:.2f} deg)")


if __name__ == "__main__":
    main()