#!/usr/bin/env python3
"""Day 811: Hexacontagon (60-cusped Hypocycloid) Notes — reproducibility script.

60-cusped hypocycloid parametric:
  x(t) = a*cos(t) + (a/59)*cos(59*t)
  y(t) = a*sin(t) - (a/59)*sin(59*t)

The hexacontagon (also called the 60-cusped hypocycloid or 60-pointed-star
hypocycloid) is generated by a small circle of radius r = a/59 rolling
without slipping inside a fixed circle of radius R = 60a/59 (R/r = 60).
The hexacontagon has 60-fold rotational D60 dihedral symmetry, with 60
inward-pointing cusps evenly distributed at exactly 6° intervals.

60 = 2² × 3 × 5 IS constructible by compass and straightedge (Gauss-Wantzel
1837 theorem: n is constructible iff n is a product of DISTINCT Fermat primes
and a power of 2; 60 = 4·3·5 satisfies the criterion since 3 and 5 are
distinct Fermat primes and 4 = 2² is a power of 2).
"""

import math

def hexacontagon_samples(a=4.0, n=32, t_min=0.0, t_max=2 * math.pi):
    """Compute n samples along the hexacontagon curve."""
    samples = []
    for i in range(n):
        t = t_min + (t_max - t_min) * i / max(1, n - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_59t = math.cos(59 * t)
        sin_59t = math.sin(59 * t)
        x = a * cos_t + (a / 59) * cos_59t
        y = a * sin_t - (a / 59) * sin_59t
        samples.append((x, y))
    return samples

if __name__ == "__main__":
    samples = hexacontagon_samples(a=4.0, n=32)
    print(f"Generated {len(samples)} samples for hexacontagon (a=4.0, n=32)")
    print(f"First sample (t=0): x={samples[0][0]:.6f}, y={samples[0][1]:.6f}")
    print(f"Last sample (t=2pi): x={samples[-1][0]:.6f}, y={samples[-1][1]:.6f}")
    print(f"x range: [{min(s[0] for s in samples):.4f}, {max(s[0] for s in samples):.4f}]")
    print(f"y range: [{min(s[1] for s in samples):.4f}, {max(s[1] for s in samples):.4f}]")
    # Verify cusp count: 60 cusps at 6° intervals
    # At t = 2pi/60 = pi/30, the curve should pass through a cusp
    cusp_t = 2 * math.pi / 60
    cusp_sample = (4.0 * math.cos(cusp_t) + (4.0 / 59) * math.cos(59 * cusp_t),
                   4.0 * math.sin(cusp_t) - (4.0 / 59) * math.sin(59 * cusp_t))
    print(f"Sample at t=2pi/60 (~6°): x={cusp_sample[0]:.6f}, y={cusp_sample[1]:.6f}")