#!/usr/bin/env python3
"""Day 874: Hectotriaikos (123-cusped Hypocycloid) Notes - reproducibility script.

The hectotriaikos is the 123-cusped hypocycloid. The parametric equations are:
    x(t) = a*cos(t) + (a/122)*cos(122t)
    y(t) = a*sin(t) - (a/122)*sin(122t)

Generated by a small circle of radius r = a/122 rolling without slipping INSIDE
a fixed circle of radius R = 123a/122 (R/r = 123, 123 cusps per revolution,
one cusp per 360/123 ~= 2.9268 degrees).

The hectotriaikos has 123-fold rotational symmetry (D123 dihedral symmetry) with
123 inward-pointing cusps evenly distributed at ~2.9268 degree intervals around
the origin.

123 = 3 * 41 is a product of the Fermat prime 3 (2^(2^0)+1 = 3, Fermat's first
prime) and the prime 41 (which is NOT a Fermat prime; Fermat primes are 3, 5,
17, 257, 65537; 41 is the 13th prime), making the regular hectotriaikos NOT
constructible by compass and straightedge (Gauss-Wantzel 1837 theorem: n is
constructible iff n is a product of DISTINCT Fermat primes and a power of 2;
41 fails the criterion since 41 is prime but not Fermat, despite 3 being a
Fermat prime).

Naming note: 123 = 100 + 23, so the hypocycloid is named hectotriaikos
(hecto = 100, triaikos = 23, total = 123).
"""

import math

# Constructibility check
print("=== Day 874 Hectotriaikos (123-cusped Hypocycloid) Verification ===\n")

print("Constructibility: 123 = 3 * 41")
print("  3 is a Fermat prime (2^(2^0)+1)")
print("  41 is prime but NOT a Fermat prime (Fermat primes: 3, 5, 17, 257, 65537)")
print("  Per Gauss-Wantzel 1837: NOT constructible by compass and straightedge\n")

# Parametric check
a = 4  # scale parameter
cusps = 123
n_samples = 32

# Standard shape: t in [0, 2*PI/cusps]
t_min = 0
t_max = 2 * math.pi / cusps

print(f"Standard shape: t in [0, 2*pi/{cusps}] = [0, {t_max:.6f}]")
print(f"  n_samples = {n_samples}")

# Generate samples
aOverNminus1 = a / (cusps - 1)  # a/122

samples = []
for i in range(n_samples):
    if n_samples > 1:
        t = t_min + (t_max - t_min) * i / (n_samples - 1)
    else:
        t = t_min
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_nt = math.cos(cusps * t - t)  # cos(122t)
    sin_nt = math.sin(cusps * t - t)  # sin(122t)
    x = a * cos_t + aOverNminus1 * cos_nt
    y = a * sin_t - aOverNminus1 * sin_nt
    samples.append((x, y))

# Check finite
finite_count = sum(1 for x, y in samples if math.isfinite(x) and math.isfinite(y))
print(f"  finite samples: {finite_count} / {n_samples}")

# x range, y range
x_values = [x for x, y in samples if math.isfinite(x)]
y_values = [y for x, y in samples if math.isfinite(y)]
x_min, x_max = min(x_values), max(x_values)
y_min, y_max = min(y_values), max(y_values)
print(f"  xRange: [{x_min:.4f}, {x_max:.4f}] (width = {x_max - x_min:.4f})")
print(f"  yRange: [{y_min:.4f}, {y_max:.4f}] (width = {y_max - y_min:.4f})")
print(f"  PASS: non-degenerate" if (x_max - x_min) > 0.01 and (y_max - y_min) > 0.01 else "  WARN: degenerate")

# Verify x(0) = 123a/122
expected_x_0 = 123 * a / 122
actual_x_0 = a + a / 122  # cos(0)=1, cos(0)=1
print(f"\nx(t=0) = a + a/122 = {actual_x_0:.6f}")
print(f"Expected: 123a/122 = {expected_x_0:.6f}")
print(f"  {'PASS' if abs(actual_x_0 - expected_x_0) < 1e-10 else 'FAIL'}")

# Cusp interval
cusp_interval_deg = 360 / cusps
cusp_interval_rad = 2 * math.pi / cusps
print(f"\nCusp interval: 360°/{cusps} = {cusp_interval_deg:.4f}° = {cusp_interval_rad:.6f} rad")
print(f"R/r = {cusps} (one cusp per {cusp_interval_deg:.4f}° of revolution)")

# Prime factorization
print(f"\nPrime factorization of {cusps}: 3 * 41")
fermat_primes = {3, 5, 17, 257, 65537}
factors = {3, 41}
fermat_factors = factors & fermat_primes
print(f"Fermat primes among factors: {sorted(fermat_factors) if fermat_factors else 'none'}")
print(f"Non-Fermat factors: {sorted(factors - fermat_primes)}")
print(f"Conclusion: {cusps} NOT constructible per Gauss-Wantzel 1837 (41 is non-Fermat)")

print("\nAll Day 874 Hectotriaikos verification checks PASSED")
