#!/usr/bin/env python3
"""Day 819: Hexacontaoctagon (68-cusped Hypocycloid) Notes Reproducibility Script.

Parametric hypocycloid equations for n=68 cusps:
    x(t) = a*cos(t) + (a/67)*cos(67*t)
    y(t) = a*sin(t) - (a/67)*sin(67*t)

Generated by a small circle of radius r=a/67 rolling inside a fixed circle of
radius R=68a/67 (R/r=68, 68 cusps per revolution, one cusp per 360/68 = 5.294 deg).

68 = 2^2 * 17 IS constructible by compass and straightedge (Gauss-Wantzel 1837):
    17 IS a Fermat prime (F_2 = 2^(2^2)+1) and 4 IS a power of 2, so
    68 = 4 * 17 satisfies the criterion.
"""
import math


def hexacontaoctagon(t, a=4):
    """Parametric form for a 68-cusped hypocycloid."""
    return (
        a * math.cos(t) + (a / 67) * math.cos(67 * t),
        a * math.sin(t) - (a / 67) * math.sin(67 * t),
    )


def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True


def prime_factorization(n):
    factors = {}
    d = 2
    while d * d <= n:
        while n % d == 0:
            factors[d] = factors.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        factors[n] = factors.get(n, 0) + 1
    return factors


# Test 1: at t=0, x = a + a/67 = 68a/67 and y = 0
x0, y0 = hexacontaoctagon(0, 4)
expected_x0 = 4 * 68 / 67
print("Test 1: x at t=0 = %.6f, expected = %.6f (= 68a/67)" % (x0, expected_x0))
assert abs(x0 - expected_x0) < 1e-9
assert abs(y0) < 1e-9

# Test 2: at t=pi, x = -68a/67, y = 0
xp, yp = hexacontaoctagon(math.pi, 4)
print("Test 2: x at t=pi = %.6f, expected = -68a/67 = %.6f" % (xp, -expected_x0))
assert abs(xp + expected_x0) < 1e-9
assert abs(yp) < 1e-9

# Test 3: 32-sample curve range
samples = [hexacontaoctagon(2 * math.pi * i / 31) for i in range(32)]
xs = [p[0] for p in samples]
ys = [p[1] for p in samples]
print("Test 3: x range = [%.4f, %.4f], y range = [%.4f, %.4f]"
      % (min(xs), max(xs), min(ys), max(ys)))

# Test 4: prime factorization of 68 = 2^2 * 17
factors = prime_factorization(68)
print("Test 4: 68 = %s" % factors)
assert factors == {2: 2, 17: 1}

# Test 5: 68 IS constructible (Gauss-Wantzel 1837)
FermatPrimes = {3, 5, 17, 257, 65537}
all_good = all(
    p in FermatPrimes or p == 2 for p, e in factors.items() if e == 1
)
for p, e in factors.items():
    if e > 1 and p in FermatPrimes:
        all_good = False  # Fermat primes must appear with multiplicity 1
print("Test 5: 68 = 2^2 * 17; 17 IS a Fermat prime, 4 IS power of 2 -> 68 IS constructible")
assert all_good

# Test 6: shape variations
t_hexacontaoctagon = [2 * math.pi / 68 * i / 31 for i in range(32)]
xs_h = [hexacontaoctagon(t, 4)[0] for t in t_hexacontaoctagon]
print("Test 6: hexacontaoctagon shape x range = [%.4f, %.4f]" % (min(xs_h), max(xs_h)))

t_tight = [(-math.pi / 68) + (2 * math.pi / 68) * i / 31 for i in range(32)]
xs_t = [hexacontaoctagon(t, 4)[0] for t in t_tight]
print("Test 7: tight shape x range = [%.4f, %.4f]" % (min(xs_t), max(xs_t)))

t_inverted = [2 * math.pi - 2 * math.pi * i / 31 for i in range(32)]
xs_i = [hexacontaoctagon(t, 4)[0] for t in t_inverted]
print("Test 8: inverted shape x range = [%.4f, %.4f]" % (min(xs_i), max(xs_i)))

print("\nAll Day 819 hexacontaoctagon verification tests passed.")