#!/usr/bin/env python3
"""Day 858 Hectoheptagon (107-cusped Hypocycloid) reproducibility script.

The hectoheptagon is the 107-cusped hypocycloid, generated by a small circle
of radius r = a/106 rolling inside a fixed circle of radius R = 107a/106
(R/r = 107, 107 cusps per revolution, one cusp per 360°/107 ~= 3.3645°).

Parametric equations:
  x(t) = a*cos(t) + (a/106)*cos(106*t)
  y(t) = a*sin(t) - (a/106)*sin(106*t)

Constructibility: 107 IS a prime (the 28th prime) but NOT a Fermat prime.
Per the Gauss-Wantzel 1837 theorem, n is constructible iff n is a product
of DISTINCT Fermat primes and a power of 2; 107 is prime but not Fermat, so
the regular 107-gon is NOT constructible by classical means.

Naming: 107 = 100 + 7, so the hypocycloid is named hectoheptagon
(hecto = 100, hepta = 7, gon = sides, total = 107).
"""
import math

N = 107           # number of cusps
N_MINUS_1 = N - 1 # 106 (interior param)
a = 4             # scale
aOver = a / N_MINUS_1

print(f"Hectoheptagon (N={N}-cusped hypocycloid) - Day 858")
print(f"  R/r = {N}, ~{360.0/N:.6f} degrees per cusp")
print(f"  Constructibility: {N} IS prime (28th prime) but NOT a Fermat prime")
print(f"  (Fermat primes are 3, 5, 17, 257, 65537; 107 fails the Gauss-Wantzel 1837 criterion)")
print(f"  Per Gauss-Wantzel 1837: NOT constructible by compass and straightedge")
print(f"  Parametric: x(t) = a*cos(t) + (a/{N_MINUS_1})*cos({N_MINUS_1}t),")
print(f"              y(t) = a*sin(t) - (a/{N_MINUS_1})*sin({N_MINUS_1}t)")
print()

# x at t=0: a*1 + (a/106)*1 = a + a/106 = a * (1 + 1/106) = a * 107/106
x0 = a * math.cos(0) + aOver * math.cos(N_MINUS_1 * 0)
y0 = a * math.sin(0) - aOver * math.sin(N_MINUS_1 * 0)
print(f"  At t=0: x = {x0:.6f} (= a * 107/106 = {a * 107/106:.6f}), y = {y0:.6f}")
print(f"  HECTOHEPTAGON_T_MAX = 2*PI/{N} = {2*math.pi/N:.6f} rad")
print(f"  TIGHT_T_MIN/MAX = +/-PI/{N} = +/-{math.pi/N:.6f} rad")
print()

# Verify 32 finite samples for all 4 shapes
LENGTH = 32
shapes = {
    "standard":      (0.0, 2*math.pi),
    "inverted":      (2*math.pi, 0.0),
    "hectoheptagon": (0.0, 2*math.pi / N),
    "tight":         (-math.pi / N, math.pi / N),
}
print(f"  Verifying {LENGTH}-length samples for all 4 shapes:")
all_pass = True
for name, (tMin, tMax) in shapes.items():
    n_finite = 0
    x_min, x_max = math.inf, -math.inf
    y_min, y_max = math.inf, -math.inf
    for i in range(LENGTH):
        t = tMin + (tMax - tMin) * i / max(1, LENGTH - 1)
        cosT, sinT = math.cos(t), math.sin(t)
        cosN1, sinN1 = math.cos(N_MINUS_1 * t), math.sin(N_MINUS_1 * t)
        x = a * cosT + aOver * cosN1
        y = a * sinT - aOver * sinN1
        if math.isfinite(x) and math.isfinite(y):
            n_finite += 1
            x_min, x_max = min(x_min, x), max(x_max, x)
            y_min, y_max = min(y_min, y), max(y_max, y)
    xr = x_max - x_min
    yr = y_max - y_min
    ok = n_finite == LENGTH and xr > 0.01 and yr > 0.01
    all_pass = all_pass and ok
    print(f"    {name:15s}: {n_finite}/{LENGTH} finite, xRange={xr:.4f}, yRange={yr:.4f} {'OK' if ok else 'FAIL'}")

print()
print(f"  Overall: {'ALL CHECKS PASS' if all_pass else 'FAILURE'}")
