#!/usr/bin/env python3
"""
Day 888: Hectoheptatriacontagon (137-cusped Hypocycloid) — reproducibility script.

Parametric: x(t) = a*cos(t) + (a/136)*cos(136t), y(t) = a*sin(t) - (a/136)*sin(136t).
Generated by a small circle of radius r = a/136 rolling inside a fixed circle of
radius R = 137a/136 (R/r=137, 137 cusps per revolution, one cusp per 360/137 deg).

137 IS prime (the 33rd prime) but NOT a Fermat prime (Fermat primes are
3, 5, 17, 257, 65537), so 137-gon is NOT constructible per Gauss-Wantzel 1837.
"""

import math

N = 137
a = 4.0
N_SAMPLES = 32
T_MIN = 0.0
T_MAX = 2.0 * math.pi


def trace_samples(shape='standard'):
    if shape == 'standard':
        tmin, tmax = T_MIN, T_MAX
    elif shape == 'inverted':
        tmin, tmax = T_MAX, T_MIN
    elif shape == 'hectoheptatriacontagon':
        tmin, tmax = 0.0, 2.0 * math.pi / N
    elif shape == 'tight':
        tmin, tmax = -math.pi / N, math.pi / N
    else:
        raise ValueError(shape)
    a_over = a / (N - 1)
    samples = []
    for i in range(N_SAMPLES):
        t = tmin + (tmax - tmin) * i / max(1, N_SAMPLES - 1)
        x = a * math.cos(t) + a_over * math.cos((N - 1) * t)
        y = a * math.sin(t) - a_over * math.sin((N - 1) * t)
        if not (math.isfinite(x) and math.isfinite(y)):
            continue
        samples.append((x, y))
    return samples


def stats(samples):
    xs = [p[0] for p in samples]
    ys = [p[1] for p in samples]
    return (min(xs), max(xs), min(ys), max(ys))


def main():
    print(f"Day 888: Hectoheptatriacontagon (137-cusped Hypocycloid)")
    print(f"  137 = prime (33rd prime), NOT Fermat (Fermat primes 3,5,17,257,65537)")
    print(f"  137 NOT constructible per Gauss-Wantzel 1837 (prime but not Fermat)")
    print(f"  R/r = 137; small circle r = a/136 inside fixed R = 137a/136")
    print(f"  Parametric: x = a*cos(t) + (a/136)*cos(136t), y = a*sin(t) - (a/136)*sin(136t)")
    print(f"  Cusp interval: 360/137 = {360.0/137:.6f} degrees")
    print()

    a_over = a / (N - 1)
    t0_x = a * math.cos(0) + a_over * math.cos(0)
    t0_y = a * math.sin(0) - a_over * math.sin(0)
    print(f"  At t=0: x = a + a/136 = {t0_x:.6f} (should be 137a/136 = {137*a/136:.6f})")
    print(f"          y = 0 - 0 = 0")
    print()

    for shape in ['standard', 'inverted', 'hectoheptatriacontagon', 'tight']:
        samples = trace_samples(shape)
        if samples:
            xmn, xmx, ymn, ymx = stats(samples)
            print(f"  shape={shape:30s}  N={len(samples):3d}  x[{xmn:+.4f}, {xmx:+.4f}]  y[{ymn:+.4f}, {ymx:+.4f}]")
        else:
            print(f"  shape={shape:30s}  NO FINITE SAMPLES")
    print()

    print(f"  2*PI/137 = {2*math.pi/137:.9f} (HECTOHEPTATRIACONTAGON_NOTES_HECTOHEPTATRIACONTAGON_T_MAX)")


if __name__ == "__main__":
    main()
