#!/usr/bin/env python3
"""Day 865: Hectotetradecagon (114-cusped Hypocycloid) Notes - reproducibility script.

Parametric: x = a*cos(t) + (a/113)*cos(113t), y = a*sin(t) - (a/113)*sin(113t).
Generated by a small circle of radius r = a/113 rolling inside a fixed circle
of radius R = 114a/113 (R/r=114, 114 cusps per revolution, one cusp per
360/114 ~= 3.15789 degrees).

114 = 2 * 3 * 19 is NOT constructible by compass and straightedge per
Gauss-Wantzel 1837 since 19 is prime but NOT a Fermat prime, despite
2 being a power of 2 and 3 being a Fermat prime.
"""
import math

N = 114
a = 4
divisor = N - 1  # 113

shapes = ['standard', 'inverted', 'hectotetradecagon', 'tight']
shape_params = {
    'standard': (0, 2 * math.pi),
    'inverted': (2 * math.pi, 0),
    'hectotetradecagon': (0, 2 * math.pi / N),
    'tight': (-math.pi / N, math.pi / N),
}

length = 32
all_ok = True

print(f"Day 865: Hectotetradecagon ({N}-cusped Hypocycloid) Notes")
print(f"114 = 2 * 3 * 19; 19 is prime but NOT a Fermat prime")
print(f"R/r={N}, ~{360/N:.4f} degree cusp intervals, NOT constructible per Gauss-Wantzel 1837")
print(f"x(t) = a*cos(t) + (a/{divisor})*cos({divisor}*t), y(t) = a*sin(t) - (a/{divisor})*sin({divisor}*t)")
print()

for shape in shapes:
    t_min, t_max = shape_params[shape]
    samples = []
    for i in range(length):
        t = t_min + (t_max - t_min) * i / max(1, length - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_nt = math.cos(divisor * t)
        sin_nt = math.sin(divisor * t)
        aOver = a / divisor
        x = a * cos_t + aOver * cos_nt
        y = a * sin_t - aOver * sin_nt
        if not (math.isfinite(x) and math.isfinite(y)):
            continue
        samples.append((x, y))

    n_finite = len(samples)
    if samples:
        xs = [p[0] for p in samples]
        ys = [p[1] for p in samples]
        x_min, x_max = min(xs), max(xs)
        y_min, y_max = min(ys), max(ys)
    else:
        x_min = x_max = y_min = y_max = float('nan')

    ok = n_finite == length
    all_ok = all_ok and ok
    print(f"shape={shape}: {n_finite}/{length} finite samples, "
          f"xRange=[{x_min:.4f},{x_max:.4f}] yRange=[{y_min:.4f},{y_max:.4f}], "
          f"OK={ok}")

# Sanity check on t=0 for standard
t = 0
aOver = a / divisor
x_at_0 = a * math.cos(0) + aOver * math.cos(0)
y_at_0 = a * math.sin(0) - aOver * math.sin(0)
print(f"\nx at t=0 (standard) = {x_at_0:.6f} = {N}*a/{divisor} = {N*a/divisor:.6f}")
print(f"y at t=0 (standard) = {y_at_0:.6f} (expected 0)")

# cusp interval
print(f"\ncusp interval = 360/{N} = {360/N:.6f} degrees = 2*pi/{N} = {2*math.pi/N:.6f} rad")

print(f"\nAll shapes produce 32/32 finite samples: {all_ok}")
print(f"\nHECTOTETRADECAGON_NOTES_HECTOTETRADECAGON_T_MAX = 2 * Math.PI / {N} = {2*math.pi/N:.6f}")
print(f"HECTOTETRADECAGON_NOTES_TIGHT_T_MIN/MAX = +-Math.PI / {N} = +-{math.pi/N:.6f}")
