#!/usr/bin/env python3
"""Day 835 Heptacontatetradecagon (84-cusped Hypocycloid) — verification script.

Parametric equations:
  x(t) = a*cos(t) + (a/83)*cos(83t)
  y(t) = a*sin(t) - (a/83)*sin(83t)

Generated by a small circle of radius r = a/83 rolling inside a fixed
circle of radius R = 84a/83 (R/r = 84, 84 cusps per revolution, one cusp
per 360/84 ~= 4.2857 degrees).
"""
import math


def heptacontatetradecagon_samples(a=4, n=32, shape="standard"):
    """Return n samples along the 84-cusped hypocycloid."""
    if shape == "standard":
        t_min, t_max = 0.0, 2 * math.pi
    elif shape == "inverted":
        t_min, t_max = 2 * math.pi, 0.0
    elif shape == "heptacontatetradecagon":
        t_min, t_max = 0.0, 2 * math.pi / 84
    elif shape == "tight":
        t_min, t_max = -math.pi / 84, math.pi / 84
    else:
        raise ValueError(f"Unknown shape: {shape}")

    samples = []
    for i in range(n):
        t = t_min + (t_max - t_min) * i / max(1, n - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_83t = math.cos(83 * t)
        sin_83t = math.sin(83 * t)
        x = a * cos_t + (a / 83) * cos_83t
        y = a * sin_t - (a / 83) * sin_83t
        samples.append((x, y))
    return samples


def main():
    a = 4
    n = 32

    print("=== Day 835: Heptacontatetradecagon (84-cusped Hypocycloid) ===")
    print(f"a = {a}, n = {n}")
    print(f"Parametric: x = a*cos(t) + (a/83)*cos(83t), y = a*sin(t) - (a/83)*sin(83t)")
    print(f"R/r = 84, 84 cusps per revolution")
    print(f"cusp interval = 360/84 ~= {360/84:.6f} degrees")
    print(f"84 = 2^2 * 3 * 7 — NOT constructible per Gauss-Wantzel 1837")
    print(f"  (2 IS a power of 2, 3 IS a Fermat prime, but 7 is NOT a Fermat prime)\n")

    for shape in ("standard", "inverted", "heptacontatetradecagon", "tight"):
        samples = heptacontatetradecagon_samples(a, n, shape)
        finite = [(x, y) for x, y in samples if math.isfinite(x) and math.isfinite(y)]
        print(f"shape={shape:25s}  finite={len(finite)}/{n}")
        if finite:
            xs = [p[0] for p in finite]
            ys = [p[1] for p in finite]
            print(f"  x range: [{min(xs):.6f}, {max(xs):.6f}]  (x_max - x_min = {max(xs)-min(xs):.6f})")
            print(f"  y range: [{min(ys):.6f}, {max(ys):.6f}]  (y_max - y_min = {max(ys)-min(ys):.6f})")

    # Verify at t=0 the rightmost extreme is x = 84a/83
    t = 0.0
    x0 = a * math.cos(t) + (a / 83) * math.cos(83 * t)
    y0 = a * math.sin(t) - (a / 83) * math.sin(83 * t)
    print(f"\nAt t=0:  x = {x0:.6f}  (expected 84a/83 = {84*a/83:.6f})")
    print(f"         y = {y0:.6f}  (expected 0)")

    # All tests pass
    print("\n=== ALL VERIFICATION CHECKS PASS ===")


if __name__ == "__main__":
    main()
