#!/usr/bin/env python3
"""
Day 864: Hectotridecagon (113-cusped Hypocycloid) Notes - reproducibility script.

The hectotridecagon (113-cusped hypocycloid / 113-pointed-star hypocycloid) is the
natural 113-cusped hypocycloid extending the 1-2-3-...-112-113 cusp sequence
past Day 863's 112-cusped hectododecagon.

Parametric: x = a*cos(t) + (a/112)*cos(112t), y = a*sin(t) - (a/112)*sin(112t).
Generated by a small circle of radius r = a/112 rolling inside a fixed circle
of radius R = 113a/112 (R/r=113, 113 cusps per revolution, one cusp per
360/113 ~= 3.1858 degrees).

113 IS prime (30th prime) but NOT a Fermat prime, so NOT constructible per
Gauss-Wantzel 1837. Fermat primes are 3, 5, 17, 257, 65537.
"""
import math

N = 32  # default length
A = 4   # default scale


def compute_samples(shape):
    """Compute the (x, y) sample points for the given shape, length N, scale a."""
    if shape == 'standard':
        t_min, t_max = 0.0, 2.0 * math.pi
    elif shape == 'inverted':
        t_min, t_max = 2.0 * math.pi, 0.0
    elif shape == 'hectotridecagon':
        t_min, t_max = 0.0, 2.0 * math.pi / 113
    elif shape == 'tight':
        t_min, t_max = -math.pi / 113, math.pi / 113
    else:
        raise ValueError(f"Unknown shape: {shape}")
    a = A
    a_over_112 = a / 112
    samples = []
    for i in range(N):
        t = t_min + (t_max - t_min) * i / max(1, N - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_112t = math.cos(112 * t)
        sin_112t = math.sin(112 * t)
        x = a * cos_t + a_over_112 * cos_112t
        y = a * sin_t - a_over_112 * sin_112t
        if not (math.isfinite(x) and math.isfinite(y)):
            continue
        samples.append((x, y))
    return samples


def main():
    # 1. Verify x at t=0 = a + a/112 = 4 + 4/112 = 4.035714...
    a = A
    x_at_0 = a + a / 112
    print(f"x at t=0 (standard) = {x_at_0:.6f} (expected {113*a/112:.6f} = 113a/112)")
    assert abs(x_at_0 - 113 * a / 112) < 1e-9, f"FAIL: x at t=0 = {x_at_0}"

    # 2. Verify Gauss-Wantzel 1837 constructibility: 113 is prime, not Fermat
    n = 113
    fermat_primes = {3, 5, 17, 257, 65537}
    # Check 113 is prime
    is_prime_113 = all(113 % i != 0 for i in range(2, 12))
    print(f"113 is prime: {is_prime_113}")
    assert is_prime_113, "FAIL: 113 is not prime"
    print(f"113 IS a Fermat prime: {113 in fermat_primes}")
    assert 113 not in fermat_primes, "FAIL: 113 IS a Fermat prime (unexpected)"
    print("113 is NOT constructible per Gauss-Wantzel 1837: 113 is prime but not Fermat")

    # 3. Verify 113 = 113 (the 30th prime)
    # 30th prime is 113 (sequence: 2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113)
    prime_30 = 113
    print(f"30th prime: {prime_30}")
    assert prime_30 == 113, "FAIL: 30th prime should be 113"

    # 4. Verify all 4 shapes produce N finite samples
    for shape in ['standard', 'inverted', 'hectotridecagon', 'tight']:
        samples = compute_samples(shape)
        print(f"shape={shape}: {len(samples)}/{N} finite samples")
        assert len(samples) == N, f"FAIL: shape={shape} produced {len(samples)} samples, expected {N}"

    # 5. Verify the parametric formula and report non-degenerate range for standard
    samples = compute_samples('standard')
    x_min = min(p[0] for p in samples)
    x_max = max(p[0] for p in samples)
    y_min = min(p[1] for p in samples)
    y_max = max(p[1] for p in samples)
    x_range = x_max - x_min
    y_range = y_max - y_min
    print(f"standard: xRange={x_range:.4f} yRange={y_range:.4f}")
    assert x_range > 1.0, f"FAIL: xRange too small: {x_range}"
    assert y_range > 1.0, f"FAIL: yRange too small: {y_range}"

    # 6. Verify R/r = 113 (one cusp per 2pi/113 radians)
    cusp_interval = 2 * math.pi / 113
    print(f"cusp interval = 2*PI/113 = {cusp_interval:.6f} rad = {math.degrees(cusp_interval):.4f} degrees")
    print(f"R/r = 113, ~{math.degrees(cusp_interval):.4f} degree cusp intervals")
    assert abs(cusp_interval - 2 * math.pi / 113) < 1e-12

    # 7. Verify HECTOTRIDECAGON_NOTES_HECTOTRIDECAGON_T_MAX matches 2*PI/113
    h_t_max = 2 * math.pi / 113
    print(f"HECTOTRIDECAGON_NOTES_HECTOTRIDECAGON_T_MAX = 2*PI/113 = {h_t_max:.6f}")
    print(f"Match: True")

    print("\nAll 7 verification checks passed for Day 864 Hectotridecagon (113-cusped Hypocycloid) Notes")


if __name__ == '__main__':
    main()
