#!/usr/bin/env python3
"""Day 834 - Heptacontatridecagon (83-cusped Hypocycloid) Notes - Reproducibility verification.

The heptacontatridecagon (also called the 83-cusped hypocycloid or 83-pointed-star hypocycloid)
is the natural 83-cusped hypocycloid extending the 1-2-3-...-82-83 cusp sequence of classical
hypocycloids. Parametric equations:
    x(t) = a*cos(t) + (a/82)*cos(82t)
    y(t) = a*sin(t) - (a/82)*sin(82t)
Generated by a small circle of radius r = a/82 rolling without slipping INSIDE a fixed circle
of radius R = 83a/82 (R/r=83, 83 cusps per revolution, one cusp per 360/83 ~= 4.3373 degrees).

83 IS prime (23rd prime) but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537),
so NOT constructible by compass and straightedge (Gauss-Wantzel 1837 theorem).
"""

import math

A = 4  # scale parameter (matches DEFAULT_A)
N = 83  # 83-cusped hypocycloid
FREQ = N - 1  # 82 (the inner-frequency multiplier in cos(82t))


def sample(t_min, t_max, length):
    """Generate `length` samples along the 83-cusped hypocycloid curve."""
    samples = []
    a_over_freq = A / FREQ
    for i in range(length):
        t = t_min + (t_max - t_min) * i / max(1, length - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_freq_t = math.cos(FREQ * t)
        sin_freq_t = math.sin(FREQ * t)
        x = A * cos_t + a_over_freq * cos_freq_t
        y = A * sin_t - a_over_freq * sin_freq_t
        if not (math.isfinite(x) and math.isfinite(y)):
            continue
        samples.append((x, y))
    return samples


def range_extents(samples):
    xs = [p[0] for p in samples]
    ys = [p[1] for p in samples]
    return min(xs), max(xs), min(ys), max(ys)


print(f"=== Day 834: Heptacontatridecagon (83-cusped Hypocycloid) Notes ===\n")
print(f"Parametric: x = a*cos(t) + (a/82)*cos(82t), y = a*sin(t) - (a/82)*sin(82t)")
print(f"a = {A}, R/r = {N} ({N - 1} = 82 inner freq)")
print(f"83 IS prime (23rd prime) but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537)")
print(f"83 = prime but not Fermat, so NOT constructible per Gauss-Wantzel 1837\n")

# Verify at t=0: x = a + a/82 = 83a/82 (rightmost extreme)
t0_x_expected = N * A / FREQ  # 83a/82
t0_x_actual = A * math.cos(0) + (A / FREQ) * math.cos(FREQ * 0)
t0_y_actual = A * math.sin(0) - (A / FREQ) * math.sin(FREQ * 0)
print(f"At t=0 (rightmost extreme):")
print(f"  x = a + a/82 = {N}*a/{FREQ} = {t0_x_expected:.6f} (expected)")
print(f"  x (computed) = {t0_x_actual:.6f}")
print(f"  y (computed) = {t0_y_actual:.6f} (expected 0)")
print(f"  Match: {abs(t0_x_actual - t0_x_expected) < 1e-9 and abs(t0_y_actual) < 1e-9}\n")

# Cusp interval
cusp_interval = 360.0 / N  # degrees
print(f"Cusp interval: 360°/{N} = {cusp_interval:.6f}°\n")

# Generate samples for each shape
LENGTH = 32  # DEFAULT_LENGTH

shapes = {
    "Standard": (0.0, 2 * math.pi),
    "Inverted": (2 * math.pi, 0.0),
    "Heptacontatridecagon": (0.0, 2 * math.pi / N),  # 1 cusp region
    "Tight": (-math.pi / N, math.pi / N),
}

for name, (t_min, t_max) in shapes.items():
    samples = sample(t_min, t_max, LENGTH)
    x_min, x_max, y_min, y_max = range_extents(samples)
    print(f"Shape '{name}': t in [{t_min:.6f}, {t_max:.6f}]")
    print(f"  finite samples: {len(samples)} (target: {LENGTH})")
    print(f"  x range: [{x_min:.4f}, {x_max:.4f}], width = {x_max - x_min:.4f}")
    print(f"  y range: [{y_min:.4f}, {y_max:.4f}], height = {y_max - y_min:.4f}")
    print(f"  non-degenerate: {(x_max - x_min) > 0.01 and (y_max - y_min) > 0.01}")
    print()

# Mathematical properties
print(f"=== Mathematical Properties ===")
print(f"83 = prime (23rd prime: 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83)")
print(f"83 IS NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537)")
print(f"83 IS NOT a Mersenne prime (2^7 - 1 = 127, not 83)")
print(f"83 IS the 23rd prime number")
print(f"83 IS a Sophie Germain prime (since 2*83+1 = 167 IS prime)")
print(f"83-fold rotational symmetry (D83 dihedral symmetry)")
print(f"R/r = 83, 83 cusps per revolution")
print(f"Cusp interval = 360°/83 = {cusp_interval:.6f}° ≈ 4.3373°")
print(f"Gauss-Wantzel 1837: NOT constructible by compass and straightedge")
print(f"  (83 is prime but NOT Fermat, so fails the DISTINCT Fermat primes criterion)")
