"""Day 805: Pentacontapentagon (54-cusped Hypocycloid) Notes reproducibility script.

Pentacontapentagon: 54-cusped hypocycloid.
Parametric form:
    x(t) = a*cos(t) + (a/53)*cos(53t)
    y(t) = a*sin(t) - (a/53)*sin(53t)

Generated by a small circle of radius r = a/53 rolling without slipping
inside a fixed circle of radius R = 54a/53 (R/r = 54, 54 cusps per revolution,
one cusp per 360/54 = 6.667 degrees = 2*pi/54 = pi/27 of revolution).

54 = 2 * 3^3 = 2 * 27 is NOT constructible by compass and straightedge
(Gauss-Wantzel 1837 theorem: n is constructible iff n is a product of
DISTINCT Fermat primes and a power of 2; 3 is a Fermat prime but 3^3 has
3 with multiplicity 3, failing the distinctness criterion despite 2 being
a power of 2).

54-fold rotational D54 dihedral symmetry, 54 inward-pointing cusps at
~6.667 degree intervals around the origin.
"""

import math

A = 4  # scale parameter
N = 32  # number of samples
CUSPS = 54
DENOM = CUSPS - 1  # 53
TWO_PI = 2 * math.pi


def pentacontapentagon(t, a=A):
    """Return (x, y) for a pentacontapentagon (54-cusped hypocycloid) at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_nt = math.cos(DENOM * t)
    sin_nt = math.sin(DENOM * t)
    a_over_denom = a / DENOM
    x = a * cos_t + a_over_denom * cos_nt
    y = a * sin_t - a_over_denom * sin_nt
    return x, y


def main():
    print(f"Day 805: Pentacontapentagon (54-cusped hypocycloid), a={A}, N={N}")
    print(f"  x(t) = a*cos(t) + (a/{DENOM})*cos({DENOM}t)")
    print(f"  y(t) = a*sin(t) - (a/{DENOM})*sin({DENOM}t)")
    print()

    # Sample at t = 0: should be the rightmost extreme (54a/53, 0)
    x0, y0 = pentacontapentagon(0)
    print(f"  At t = 0:  x = {x0:.4f}, y = {y0:.4f}  (expected: {CUSPS * A / DENOM:.4f}, 0.0000)")

    # Sample at t = 2*pi / 54
    x1, y1 = pentacontapentagon(TWO_PI / CUSPS)
    print(f"  At t = 2*pi/{CUSPS}:  x = {x1:.4f}, y = {y1:.4f}")

    # Generate N samples for the full standard shape
    print(f"\n  Full pentacontapentagon (Standard shape) with {N} samples:")
    print(f"  {'i':>3}  {'t':>10}  {'x':>12}  {'y':>12}")
    for i in range(N):
        t = TWO_PI * i / max(1, N - 1)
        x, y = pentacontapentagon(t)
        print(f"  {i:3d}  {t:10.6f}  {x:12.6f}  {y:12.6f}")

    # Constructibility check
    print(f"\n  54 = 2 * 3^3 = 2 * 27")
    print(f"  3 is a Fermat prime (F_0 = 2^(2^0)+1 = 3)")
    print(f"  But 3^3 has 3 with multiplicity 3, failing the distinctness criterion")
    print(f"  -> Regular 54-gon is NOT constructible by compass and straightedge (Gauss-Wantzel 1837)")


if __name__ == "__main__":
    main()
