#!/usr/bin/env python3
"""
Day 801: Pentacontagon (50-cusped Hypocycloid) - Reproducibility Script

This script renders the pentacontagon (50-cusped hypocycloid) curve for visual inspection.

Parametric equations (SnugOS Day 801):
  x(t) = a*cos(t) + (a/49)*cos(49*t)
  y(t) = a*sin(t) - (a/49)*sin(49*t)

Generated by a small circle of radius r = a/49 rolling without slipping inside a fixed circle
of radius R = 50a/49 (R/r = 50, 50 cusps per revolution).

The pentacontagon has 50-fold rotational symmetry (D50 dihedral symmetry) with 50 inward-pointing
cusps evenly distributed at 360°/50 = 7.2° intervals around the origin.

50 = 2 * 5^2. 5 is a Fermat prime (2^(2^1) + 1 = 5), but appears with multiplicity 2 in 5^2,
so 50 is NOT constructible by compass and straightedge (Gauss-Wantzel 1837 theorem).
"""

import math
import sys

try:
    import matplotlib.pyplot as plt
    HAS_MPL = True
except ImportError:
    HAS_MPL = False


def pentacontagon_points(a=4.0, n_samples=1000):
    """Generate n_samples points along the pentacontagon curve."""
    aOver49 = a / 49.0
    points = []
    for i in range(n_samples):
        t = 2.0 * math.pi * i / max(1, n_samples - 1)
        cosT = math.cos(t)
        sinT = math.sin(t)
        cos49T = math.cos(49.0 * t)
        sin49T = math.sin(49.0 * t)
        x = a * cosT + aOver49 * cos49T
        y = a * sinT - aOver49 * sin49T
        points.append((x, y))
    return points


def main():
    a = 4.0
    n = 1000
    points = pentacontagon_points(a, n)
    print(f"Day 801: Pentacontagon (50-cusped hypocycloid) - {n} samples")
    print(f"  Parametric: x = a*cos(t) + (a/49)*cos(49t), y = a*sin(t) - (a/49)*sin(49t)")
    print(f"  R/r = 50, 50 cusps per revolution")
    print(f"  Symmetry: D50 dihedral (50-fold rotational)")
    print(f"  Cusps at: 360/50 = 7.2 degree intervals")
    print(f"  50 = 2 * 5^2, NOT constructible (Gauss-Wantzel 1837)")
    print(f"  a = {a}")
    print(f"  First few sample points:")
    for i in [0, n // 100, 2 * n // 100, 3 * n // 100]:
        if i < n:
            x, y = points[i]
            print(f"    t = {2.0 * math.pi * i / (n - 1):.4f}: ({x:.4f}, {y:.4f})")
    print(f"  Verify at t=0: x = a + a/49 = {a + a / 49.0:.4f}, y = 0")

    if HAS_MPL:
        xs = [p[0] for p in points]
        ys = [p[1] for p in points]
        plt.figure(figsize=(8, 8))
        plt.plot(xs, ys, 'b-', linewidth=0.5)
        plt.axis('equal')
        plt.title('Day 801: Pentacontagon (50-cusped Hypocycloid)')
        plt.xlabel('x')
        plt.ylabel('y')
        plt.grid(True)
        out_path = '/home/workspace/app/scripts/day801_pentacontagon.png'
        plt.savefig(out_path, dpi=100)
        print(f"  Saved plot to: {out_path}")
    else:
        print("  matplotlib not available, skipping plot")


if __name__ == '__main__':
    main()