#!/usr/bin/env python3
"""
Day 884 reproducibility script for the Hectotritriacontagon (133-cusped Hypocycloid) Notes feature.

Verifies the parametric formula:
  x(t) = a*cos(t) + (a/132)*cos(132t)
  y(t) = a*sin(t) - (a/132)*sin(132t)

133 = 100 + 33 = hecto-100 + tri-3 + triaconta-30 (hectotritriacontagon = 133 sides).
R/r = 133, generated by a small circle of radius r = a/132 rolling inside
a fixed circle of radius R = 133a/132. 133 cusps per revolution, one cusp
per 360°/133 ≈ 2.7068° = 2*PI/133 of revolution.

133 = 7 × 19. Both 7 and 19 are prime but NEITHER is a Fermat prime
(Fermat primes are 3, 5, 17, 257, 65537). So 133 is NOT constructible
per Gauss-Wantzel 1837 (n is constructible iff n is a product of DISTINCT
Fermat primes and a power of 2; both 7 and 19 fail the Fermat-prime test,
so 133 fails on both factors).
"""
import math

N = 133  # number of cusps
A = 4  # scale parameter
R_OVER_R = N  # 133 cusps per revolution
A_OVER_R_FACTOR = N - 1  # 132 (small circle radius divisor)

x_at_zero = A + A / A_OVER_R_FACTOR
y_at_zero = 0
t_max = 2 * math.pi / N  # T_MAX
tight_t_max = math.pi / N  # TIGHT_T_MAX
print(f"x at t=0 = {x_at_zero:.6f} = {N}a/{A_OVER_R_FACTOR} (expected {N}*{A}/{A_OVER_R_FACTOR} = {N*A/A_OVER_R_FACTOR:.6f})")
print(f"HECTOTRITRIACONTAGON_NOTES_HECTOTRITRIACONTAGON_T_MAX = 2*PI/{N} = {t_max:.6f}")
print(f"HECTOTRITRIACONTAGON_NOTES_TIGHT_T_MAX = PI/{N} = {tight_t_max:.6f}")

shapes = ['standard', 'inverted', 'hectotritriacontagon', 'tight']
for shape in shapes:
    finite_count = 0
    for i in range(32):
        t = t_max * i / max(1, 31)
        cosT = math.cos(t)
        sinT = math.sin(t)
        cos132T = math.cos(132 * t)
        sin132T = math.sin(132 * t)
        x = A * cosT + (A / 132) * cos132T
        y = A * sinT - (A / 132) * sin132T
        if math.isfinite(x) and math.isfinite(y):
            finite_count += 1
    print(f"  Shape {shape}: {finite_count}/32 finite samples for 32-sided sample sweep")

# Verify the cusp interval
cusp_deg = 360.0 / N
print(f"\nCusp interval: 360/{N} = {cusp_deg:.4f}° = 2*PI/{N} = {2*math.pi/N:.6f} rad")

# Check constructibility
print(f"\n133 = 7 × 19")
print(f"7 is prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537): FAILS")
print(f"19 is prime but NOT a Fermat prime: FAILS")
print(f"Therefore 133 is NOT constructible per Gauss-Wantzel 1837")
print(f"R/r ratio: 133 (R = 133a/132, r = a/132)")

# Sweep t from 0 to T_MAX and report non-degenerate x/y range
xs, ys = [], []
for i in range(64):
    t = t_max * i / 63
    cosT = math.cos(t)
    sinT = math.sin(t)
    cos132T = math.cos(132 * t)
    sin132T = math.sin(132 * t)
    x = A * cosT + (A / 132) * cos132T
    y = A * sinT - (A / 132) * sin132T
    if math.isfinite(x) and math.isfinite(y):
        xs.append(x)
        ys.append(y)
if xs:
    print(f"\n64-sample sweep x range: [{min(xs):.4f}, {max(xs):.4f}]")
    print(f"64-sample sweep y range: [{min(ys):.4f}, {max(ys):.4f}]")
