#!/usr/bin/env python3
"""Day 812: Hexacontahenagon (61-cusped Hypocycloid) Notes — reproducibility script.

61-cusped hypocycloid parametric:
  x(t) = a*cos(t) + (a/60)*cos(60*t)
  y(t) = a*sin(t) - (a/60)*sin(60*t)

The hexacontahenagon (also called the 61-cusped hypocycloid or
61-pointed-star hypocycloid) is generated by a small circle of radius
r = a/60 rolling without slipping inside a fixed circle of radius
R = 61a/60 (R/r = 61). The hexacontahenagon has 61-fold rotational
D61 dihedral symmetry, with 61 inward-pointing cusps evenly distributed
at approximately 5.9° intervals (360°/61).

61 is a prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257,
65537), making the regular hexacontahenagon NOT constructible by
compass and straightedge (Gauss-Wantzel 1837 theorem: n is constructible
iff n is a product of distinct Fermat primes and a power of 2; 61 fails
the criterion since 61 is prime but not Fermat).
"""

import math

def hexacontahenagon_samples(a=4.0, n=32, t_min=0.0, t_max=2 * math.pi):
    """Compute n samples along the hexacontahenagon curve."""
    samples = []
    for i in range(n):
        t = t_min + (t_max - t_min) * i / max(1, n - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_60t = math.cos(60 * t)
        sin_60t = math.sin(60 * t)
        x = a * cos_t + (a / 60) * cos_60t
        y = a * sin_t - (a / 60) * sin_60t
        samples.append((x, y))
    return samples

if __name__ == "__main__":
    samples = hexacontahenagon_samples(a=4.0, n=32)
    print(f"Generated {len(samples)} samples for hexacontahenagon (a=4.0, n=32)")
    print(f"First sample (t=0): x={samples[0][0]:.6f}, y={samples[0][1]:.6f}")
    print(f"Last sample (t=2pi): x={samples[-1][0]:.6f}, y={samples[-1][1]:.6f}")
    print(f"x range: [{min(s[0] for s in samples):.4f}, {max(s[0] for s in samples):.4f}]")
    print(f"y range: [{min(s[1] for s in samples):.4f}, {max(s[1] for s in samples):.4f}]")
    # Verify cusp count: 61 cusps at ~5.9° intervals
    # At t = 2pi/61, the curve should pass through a cusp
    cusp_t = 2 * math.pi / 61
    cusp_sample = (4.0 * math.cos(cusp_t) + (4.0 / 60) * math.cos(60 * cusp_t),
                   4.0 * math.sin(cusp_t) - (4.0 / 60) * math.sin(60 * cusp_t))
    print(f"Sample at t=2pi/61 (~5.9°): x={cusp_sample[0]:.6f}, y={cusp_sample[1]:.6f}")
    # At t=0, x = a + a/60 = 61a/60 (the rightmost extreme)
    print(f"Expected x at t=0: {4.0 + 4.0/60:.6f} = 61a/60 = {61*4.0/60:.6f}")
