#!/usr/bin/env python3
"""Day 868: Hectoheptadecagon (117-cusped Hypocycloid) Notes - reproducibility script.

Parametric:
  x(t) = a*cos(t) + (a/116)*cos(116t)
  y(t) = a*sin(t) - (a/116)*sin(116t)

Generated by a small circle of radius r=a/116 rolling inside a fixed circle of
radius R=117a/116 (R/r=117, 117 cusps per revolution, one cusp per 360/117 ≈ 3.0769°).

117 = 3^2 * 13:
  - 3 appears with multiplicity 2, failing the distinctness criterion
  - 13 is prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537)
  - So per Gauss-Wantzel 1837, 117 is NOT constructible by compass and straightedge.
"""

import math

PI = math.pi
N = 117  # number of cusps
N_MINUS_1 = N - 1  # 116


def sample_curve(a, length, t_min, t_max):
    """Return list of (x, y) sample points for the standard shape."""
    pts = []
    aOver = a / N_MINUS_1
    for i in range(length):
        t = t_min + (t_max - t_min) * i / max(1, length - 1)
        cosT = math.cos(t)
        sinT = math.sin(t)
        cosNM1T = math.cos(N_MINUS_1 * t)
        sinNM1T = math.sin(N_MINUS_1 * t)
        x = a * cosT + aOver * cosNM1T
        y = a * sinT - aOver * sinNM1T
        if not (math.isfinite(x) and math.isfinite(y)):
            continue
        pts.append((x, y))
    return pts


def main():
    print("=== Day 868: Hectoheptadecagon (117-cusped Hypocycloid) Notes ===")
    print()

    # x at t=0 = a + a/116
    a = 4
    aOver = a / N_MINUS_1
    xAt0 = a * math.cos(0) + aOver * math.cos(0)
    print(f"x at t=0 = a + a/116 = {a} + {aOver:.6f} = {xAt0:.6f}")
    print()

    # Standard shape sweep
    print("Standard shape (t = 0 to 2*PI):")
    pts = sample_curve(a, 32, 0, 2 * PI)
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    xMin, xMax = min(xs), max(xs)
    yMin, yMax = min(ys), max(ys)
    xRange = xMax - xMin
    yRange = yMax - yMin
    print(f"  32/32 samples finite: {len(pts) == 32}")
    print(f"  xRange: {xRange:.4f}")
    print(f"  yRange: {yRange:.4f}")
    print(f"  xMin: {xMin:.4f}  xMax: {xMax:.4f}")
    print(f"  yMin: {yMin:.4f}  yMax: {yMax:.4f}")
    print()

    # Hectoheptadecagon shape sweep
    print("Hectoheptadecagon shape (t = 0 to 2*PI/117):")
    pts = sample_curve(a, 32, 0, 2 * PI / N)
    print(f"  32/32 samples finite: {len(pts) == 32}")
    print()

    # Cusp interval
    cusp_interval = 360.0 / N
    print(f"Cusp interval: 360°/{N} = {cusp_interval:.4f}°")
    print()

    # 117 factorization
    print("117 = 3^2 * 13")
    print("  3 has multiplicity 2 (Fermat prime but fails distinctness criterion)")
    print("  13 is prime but NOT a Fermat prime")
    print("  Per Gauss-Wantzel 1837: NOT constructible by compass and straightedge")
    print()

    # T constants
    print(f"HECTOHEPTADECAGON_NOTES_HECTOHEPTADECAGON_T_MAX = 2*PI/117 = {2*PI/N:.15f}")
    print(f"HECTOHEPTADECAGON_NOTES_TIGHT_T_MIN = -PI/117 = {-PI/N:.15f}")
    print(f"HECTOHEPTADECAGON_NOTES_TIGHT_T_MAX = +PI/117 = {PI/N:.15f}")


if __name__ == "__main__":
    main()
