#!/usr/bin/env python3
"""Day 881 Hectotriacontagon (130-cusped Hypocycloid) verification script.

130-cusped hypocycloid: x = a*cos(t) + (a/129)*cos(129t), y = a*sin(t) - (a/129)*sin(129t).
Generated by a small circle of radius r = a/129 rolling inside a fixed circle of radius R = 130a/129.
130 = 2 * 5 * 13. 5 is Fermat, but 13 is prime but NOT Fermat -> NOT constructible per Gauss-Wantzel 1837.
"""
import math

N = 130
N_MINUS_1 = 129
R_RATIO = N
ANGLE_T_MAX = 2 * math.pi / N
TIGHT_HALF = math.pi / N
CUSP_INTERVAL_DEG = 360.0 / N


def parametric(t, a):
    return (
        a * math.cos(t) + (a / N_MINUS_1) * math.cos(N_MINUS_1 * t),
        a * math.sin(t) - (a / N_MINUS_1) * math.sin(N_MINUS_1 * t),
    )


def collect_samples(a, length, t_min, t_max):
    samples = []
    for i in range(length):
        t = t_min + (t_max - t_min) * i / max(1, length - 1)
        x, y = parametric(t, a)
        if not (math.isfinite(x) and math.isfinite(y)):
            continue
        samples.append((x, y))
    return samples


def range_of(samples):
    if not samples:
        return None
    xs = [p[0] for p in samples]
    ys = [p[1] for p in samples]
    return min(xs), max(xs), min(ys), max(ys)


def verify_shape(label, a, length, t_min, t_max):
    samples = collect_samples(a, length, t_min, t_max)
    if not samples:
        return f"{label}: NO FINITE SAMPLES"
    xmin, xmax, ymin, ymax = range_of(samples)
    nondeg = (xmax - xmin) > 0.5 and (ymax - ymin) > 0.5
    return f"{label}: N={length} samples, xRange=[{xmin:.4f},{xmax:.4f}] yRange=[{ymin:.4f},{ymax:.4f}] nondegenerate={nondeg}"


def main():
    A = 4
    LEN = 32
    print(f"=== Day 881 Hectotriacontagon (130-cusped Hypocycloid) Verification ===")
    print(f"N = {N} = 2 * 5 * 13 (5 is Fermat, 13 is prime but NOT Fermat)")
    print(f"R/r = {R_RATIO}")
    print(f"Cusp interval = {CUSP_INTERVAL_DEG:.4f} degrees = 2*PI/{N} = {ANGLE_T_MAX:.6f}")
    print(f"x at t=0 = a*(1 + 1/129) = a*130/129 = {A * N / N_MINUS_1:.6f} = 130a/129")
    print()
    print("Hectotriacontagon parametric formula:")
    print(f"  x(t) = a*cos(t) + (a/{N_MINUS_1})*cos({N_MINUS_1}*t)")
    print(f"  y(t) = a*sin(t) - (a/{N_MINUS_1})*sin({N_MINUS_1}*t)")
    print()
    print(f"HECTOTRIACONTAGON_NOTES_HECTOTRIACONTAGON_T_MAX = 2*PI/{N} = {ANGLE_T_MAX:.6f}")
    print(f"HECTOTRIACONTAGON_NOTES_TIGHT_T_MIN/MAX = +/-PI/{N} = +/-{TIGHT_HALF:.6f}")
    print()
    print("Gauss-Wantzel 1837 constructibility check:")
    print(f"  130 = 2 * 5 * 13. 2 is a power of 2, 5 is a Fermat prime, but 13 is prime but NOT Fermat.")
    print(f"  Therefore 130 is NOT constructible per Gauss-Wantzel 1837 (the distinct Fermat-prime criterion fails).")
    print()
    print("Sample shape tests (a=4, length=32):")
    print(f"  {verify_shape('standard (full 2*PI sweep)', A, LEN, 0, 2 * math.pi)}")
    print(f"  {verify_shape('inverted (full 2*PI sweep reverse)', A, LEN, 2 * math.pi, 0)}")
    print(f"  {verify_shape('hectotriacontagon (one cusp 2*PI/130 sweep)', A, LEN, 0, ANGLE_T_MAX)}")
    print(f"  {verify_shape('tight (+/-PI/130 sweep)', A, LEN, -TIGHT_HALF, TIGHT_HALF)}")
    print()
    print(f"=== 130 NOT constructible per Gauss-Wantzel 1837 (5 IS Fermat but 13 is NOT) ===")
    print(f"=== Day 881 verification complete ===")


if __name__ == "__main__":
    main()
