#!/usr/bin/env python3
"""Day 856 Hectopentagon (105-cusped Hypocycloid) reproducibility script.

The hectopentagon is the 105-cusped hypocycloid, generated by a small circle
of radius r = a/104 rolling inside a fixed circle of radius R = 105a/104
(R/r = 105, 105 cusps per revolution, one cusp per 360°/105 ~= 3.4286°).

Parametric equations:
  x(t) = a*cos(t) + (a/104)*cos(104*t)
  y(t) = a*sin(t) - (a/104)*sin(104*t)

Constructibility: 105 = 3 * 5 * 7. 3 and 5 are Fermat primes (3 = 2^1+1,
5 = 2^2+1) but 7 is NOT a Fermat prime. Per the Gauss-Wantzel 1837 theorem,
n is constructible iff n is a product of DISTINCT Fermat primes and a power
of 2; 105 = 3*5*7 fails the distinctness criterion because 7 is prime but
not Fermat, even though 3 and 5 are Fermat primes.

Naming: 105 = 100 + 5, so the hypocycloid is named hectopentagon
(hecto = 100, penta = 5, gon = sides, total = 105).
"""
import math

N = 105           # number of cusps
N_MINUS_1 = N - 1 # 104 (interior param)
a = 4             # scale
aOver = a / N_MINUS_1

print(f"Hectopentagon (N={N}-cusped hypocycloid) — Day 856")
print(f"  R/r = {N}, ~{360.0/N:.6f} degrees per cusp")
print(f"  Constructibility: {N} = 3 * 5 * 7 NOT CONSTRUCTIBLE per Gauss-Wantzel 1837")
print(f"  (3, 5 are Fermat primes but 7 is not)")
print(f"  Parametric: x(t) = a*cos(t) + (a/{N_MINUS_1})*cos({N_MINUS_1}t),")
print(f"              y(t) = a*sin(t) - (a/{N_MINUS_1})*sin({N_MINUS_1}t)")
print()

# x at t=0: a*1 + (a/104)*1 = a + a/104 = a * (1 + 1/104) = a * 105/104
x0 = a * math.cos(0) + aOver * math.cos(N_MINUS_1 * 0)
y0 = a * math.sin(0) - aOver * math.sin(N_MINUS_1 * 0)
print(f"  At t=0: x = {x0:.6f} (= a * 105/104 = {a * 105/104:.6f}), y = {y0:.6f}")
print(f"  HECTOPENTAGON_T_MAX = 2*PI/{N} = {2*math.pi/N:.6f} rad")
print(f"  TIGHT_T_MIN/MAX = +/-PI/{N} = +/-{math.pi/N:.6f} rad")
print()

# Verify 32 finite samples for all 4 shapes
LENGTH = 32
shapes = {
    "standard":     (0.0, 2*math.pi),
    "inverted":     (2*math.pi, 0.0),
    "hectopentagon": (0.0, 2*math.pi / N),
    "tight":        (-math.pi / N, math.pi / N),
}
print(f"  Verifying {LENGTH}-length samples for all 4 shapes:")
all_pass = True
for name, (tMin, tMax) in shapes.items():
    n_finite = 0
    x_min, x_max = math.inf, -math.inf
    y_min, y_max = math.inf, -math.inf
    for i in range(LENGTH):
        t = tMin + (tMax - tMin) * i / max(1, LENGTH - 1)
        cosT, sinT = math.cos(t), math.sin(t)
        cosN1, sinN1 = math.cos(N_MINUS_1 * t), math.sin(N_MINUS_1 * t)
        x = a * cosT + aOver * cosN1
        y = a * sinT - aOver * sinN1
        if math.isfinite(x) and math.isfinite(y):
            n_finite += 1
            x_min, x_max = min(x_min, x), max(x_max, x)
            y_min, y_max = min(y_min, y), max(y_max, y)
    xr = x_max - x_min
    yr = y_max - y_min
    ok = n_finite == LENGTH and xr > 0.01 and yr > 0.01
    all_pass = all_pass and ok
    print(f"    {name:15s}: {n_finite}/{LENGTH} finite, xRange={xr:.4f}, yRange={yr:.4f} {'OK' if ok else 'FAIL'}")

print()
print(f"  Overall: {'ALL CHECKS PASS' if all_pass else 'FAILURE'}")
