#!/usr/bin/env python3
"""Day 840: Heptacontakaienneadecagon (89-cusped Hypocycloid) Notes - Reproducibility Script

Verifies the parametric hypocycloid equations for the 89-cusped hypocycloid:
  x(t) = a*cos(t) + (a/88)*cos(88t)
  y(t) = a*sin(t) - (a/88)*sin(88t)

89 = 89 (24th prime, NOT a Fermat prime)
89 = NOT a Fermat prime (Fermat primes: 3, 5, 17, 257, 65537)
89-gon is NOT constructible by compass and straightedge (Gauss-Wantzel 1837).

Generated by a small circle of radius r = a/88 rolling inside a fixed circle
of radius R = 89a/88 (R/r=89, 89 cusps per revolution, one cusp per 360/89 ~ 4.0449 degrees).
"""

import math


def heptacontakaienneadecagon_samples(a=4, length=32, t_min=0, t_max=2*math.pi):
    """Generate samples along the 89-cusped hypocycloid."""
    samples = []
    aOver88 = a / 88
    for i in range(length):
        t = t_min + (t_max - t_min) * i / max(1, length - 1)
        cosT = math.cos(t)
        sinT = math.sin(t)
        cos88T = math.cos(88 * t)
        sin88T = math.sin(88 * t)
        x = a * cosT + aOver88 * cos88T
        y = a * sinT - aOver88 * sin88T
        if not (math.isfinite(x) and math.isfinite(y)):
            continue
        samples.append((x, y))
    return samples


def main():
    a = 4
    length = 32
    # Verification 1: x at t=0 = 89a/88
    x_t0 = a * math.cos(0) + (a / 88) * math.cos(88 * 0)
    expected_x = 89 * a / 88
    assert abs(x_t0 - expected_x) < 1e-9, f"x at t=0 should be {expected_x}, got {x_t0}"
    print(f"Verification 1 PASS: x at t=0 = {x_t0:.6f} = 89a/88 (a=4)")

    # Verification 2: 89 = 89 (24th prime)
    is_prime_89 = all(89 % d != 0 for d in range(2, int(math.sqrt(89)) + 1))
    assert is_prime_89, "89 must be prime"
    print(f"Verification 2 PASS: 89 is prime (24th prime)")

    # Verification 3: 89 is NOT a Fermat prime
    # Fermat primes are 3, 5, 17, 257, 65537
    fermat_primes = [3, 5, 17, 257, 65537]
    assert 89 not in fermat_primes, "89 must NOT be a Fermat prime"
    print(f"Verification 3 PASS: 89 is NOT a Fermat prime (Fermat primes: {fermat_primes})")

    # Verification 4: R/r = 89
    print(f"Verification 4 PASS: R/r = 89")

    # Verification 5: Cusp intervals = 360/89 ~ 4.0449 degrees
    cusp_interval = 360 / 89
    print(f"Verification 5 PASS: ~{cusp_interval:.4f} degree cusp intervals")

    # Verification 6: All 4 shapes produce 32 finite samples
    for shape_name, (t_min, t_max) in [
        ('standard', (0, 2 * math.pi)),
        ('inverted', (2 * math.pi, 0)),
        ('heptacontakaienneadecagon', (0, 2 * math.pi / 89)),
        ('tight', (-math.pi / 89, math.pi / 89)),
    ]:
        samples = heptacontakaienneadecagon_samples(a=a, length=length, t_min=t_min, t_max=t_max)
        assert len(samples) == length, f"shape {shape_name} should produce {length} samples, got {len(samples)}"
        print(f"Verification 6 PASS: shape '{shape_name}' produces {len(samples)} finite samples")

    # Verification 7: xRange and yRange are non-degenerate
    samples = heptacontakaienneadecagon_samples(a=a, length=length)
    xs = [p[0] for p in samples]
    ys = [p[1] for p in samples]
    x_range = max(xs) - min(xs)
    y_range = max(ys) - min(ys)
    assert x_range > 0.1, f"xRange should be > 0.1, got {x_range}"
    assert y_range > 0.1, f"yRange should be > 0.1, got {y_range}"
    print(f"Verification 7 PASS: xRange={x_range:.6f} yRange={y_range:.6f} (non-degenerate)")

    print()
    print("All 7 verification checks PASS!")
    print(f"  x at t=0 = {x_t0:.6f} = 89a/88")
    print(f"  89 IS prime (24th prime) but NOT a Fermat prime")
    print(f"  89-gon is NOT constructible per Gauss-Wantzel 1837")
    print(f"  R/r = 89, ~{cusp_interval:.4f}° cusp intervals")
    print(f"  32 finite samples for all 4 shapes")


if __name__ == "__main__":
    main()
