#!/usr/bin/env python3
"""Day 854: Hectotrigon (103-cusped Hypocycloid) Notes - Reproducibility Script.

Parametric: x(t) = a*cos(t) + (a/102)*cos(102t), y(t) = a*sin(t) - (a/102)*sin(102t)
For N cusps, the offset divisor is N-1 = 102 and the harmonic is 102.
Generated by a small circle of radius r = a/102 rolling inside a fixed
circle of radius R = 103a/102 (R/r = 103, 103 cusps per revolution).
One cusp every 360/103 ~= 3.4951 degrees.

103 IS the 27th prime but NOT a Fermat prime (Fermat primes are
3, 5, 17, 257, 65537), so 103 IS NOT constructible by compass and
straightedge per Gauss-Wantzel 1837.

Naming note: 103 = 100 + 3, so the hypocycloid is named hectotrigon
(hecto = 100, tri = 3, gon = sides, total = 103).
"""
import math
import sys

A = 4  # scale parameter (matches UI default)
N_CUSPS = 103
DIVISOR = N_CUSPS - 1  # 102
SHAPES = ["standard", "inverted", "hectotrigon", "tight"]
LENGTH = 32  # samples per curve


def t_range_for(shape: str):
    if shape == "standard":
        return (0.0, 2 * math.pi)
    if shape == "inverted":
        return (2 * math.pi, 0.0)
    if shape == "hectotrigon":
        return (0.0, 2 * math.pi / N_CUSPS)
    if shape == "tight":
        return (-math.pi / N_CUSPS, math.pi / N_CUSPS)
    raise ValueError(shape)


def compute_samples(shape: str, length: int = LENGTH):
    t_min, t_max = t_range_for(shape)
    a = A
    a_over = a / DIVISOR
    pts = []
    for i in range(length):
        t = t_min + (t_max - t_min) * i / max(1, length - 1)
        ct = math.cos(t)
        st = math.sin(t)
        cN = math.cos(DIVISOR * t)
        sN = math.sin(DIVISOR * t)
        x = a * ct + a_over * cN
        y = a * st - a_over * sN
        if not (math.isfinite(x) and math.isfinite(y)):
            continue
        pts.append((x, y, t))
    return pts


def main() -> int:
    print(f"=== Day 854: Hectotrigon (N={N_CUSPS} cusps, divisor={DIVISOR}) ===")
    print(f"a = {A}, length = {LENGTH}")
    print(f"x(t) = {A}*cos(t) + ({A}/{DIVISOR})*cos({DIVISOR}*t)")
    print(f"y(t) = {A}*sin(t) - ({A}/{DIVISOR})*sin({DIVISOR}*t)")
    print(f"R/r = {N_CUSPS}, ~{360 / N_CUSPS:.4f} degrees per cusp")
    print()

    # Verifications
    prime_check = N_CUSPS
    is_prime = all(prime_check % d != 0 for d in range(2, int(math.sqrt(prime_check)) + 1))
    print(f"  103 IS prime: {is_prime} (103 is the 27th prime)")
    print(f"  103 IS Fermat prime: False (Fermat primes = 3, 5, 17, 257, 65537)")
    print(f"  103 constructible by compass/straightedge: False (Gauss-Wantzel 1837)")
    print(f"  103 is the 27th prime number")
    print()

    all_pass = True
    for shape in SHAPES:
        pts = compute_samples(shape)
        finite_count = len(pts)
        ok = finite_count == LENGTH
        all_pass = all_pass and ok
        if not pts:
            print(f"  [{shape}] NO FINITE SAMPLES")
            continue
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        xrange = max(xs) - min(xs)
        yrange = max(ys) - min(ys)
        print(
            f"  [{shape:12s}] {finite_count}/{LENGTH} finite samples, "
            f"xRange={xrange:.4f}, yRange={yrange:.4f}, "
            f"x@t=0 = {pts[0][0]:.6f}"
        )

    # Check t=0 cusp value: x = a + a/102 = a*(103/102) = 4*1.0098 = 4.039216
    expected_x_at_0 = A * N_CUSPS / DIVISOR
    pts0 = compute_samples("standard")
    actual_x_at_0 = pts0[0][0] if pts0 else float("nan")
    print()
    print(f"  x at t=0 expected: {expected_x_at_0:.6f} = {N_CUSPS}a/{DIVISOR}")
    print(f"  x at t=0 actual:   {actual_x_at_0:.6f}")
    if abs(actual_x_at_0 - expected_x_at_0) < 1e-9:
        print("  PASS: x at t=0 matches formula")
    else:
        print("  FAIL: x at t=0 mismatch")
        all_pass = False

    print()
    print(f"=== Overall: {'PASS' if all_pass else 'FAIL'} ===")
    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main())
