#!/usr/bin/env python3
"""Day 831: Heptacontadecagon (80-cusped Hypocycloid) Notes reproducibility script.

The heptacontadecagon is the 80-cusped hypocycloid generated by a small circle of radius
r = a/79 rolling without slipping INSIDE a fixed circle of radius R = 80a/79 (R/r = 80,
80 cusps per revolution, one cusp per 360/80 = 4.5 degrees exactly).

Parametric equations:
    x(t) = a*cos(t) + (a/79)*cos(79t)
    y(t) = a*sin(t) - (a/79)*sin(79t)

At t=0: x = a + a/79 = 80a/79 (the rightmost extreme).

80 = 2^4 * 5 IS constructible by compass and straightedge (Gauss-Wantzel 1837):
16 is a power of 2 and 5 IS a Fermat prime (2^(2^1)+1 = 5, the second Fermat prime).
The regular 80-gon can be constructed as a bisected regular 40-gon (the 40-gon can be
constructed as 8-gon-of-5 since 40 = 8*5 with both being constructible).
"""

import math


def heptacontadecagon(t, a):
    """Compute (x, y) on the 80-cusped hypocycloid curve at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_79t = math.cos(79 * t)
    sin_79t = math.sin(79 * t)
    a_over_79 = a / 79
    x = a * cos_t + a_over_79 * cos_79t
    y = a * sin_t - a_over_79 * sin_79t
    return x, y


def main():
    a = 4  # scale parameter

    # Verification 1: at t=0, x = 80a/79 and y = 0
    x0, y0 = heptacontadecagon(0, a)
    expected_x0 = 80 * a / 79
    print(f"x at t=0 = {x0:.6f} (expected {expected_x0:.6f} = 80a/79)")
    assert abs(x0 - expected_x0) < 1e-9, f"x at t=0 should be {expected_x0}"
    assert abs(y0) < 1e-9, f"y at t=0 should be 0"
    print(f"y at t=0 = {y0:.6f}")
    print("Verification 1 PASSED: x at t=0 = 80a/79, y at t=0 = 0\n")

    # Verification 2: 80 = 2^4 * 5 = 16 * 5
    assert 80 == 16 * 5, "80 = 16 * 5"
    assert 80 == (2 ** 4) * 5, "80 = 2^4 * 5"
    print("Verification 2 PASSED: 80 = 2^4 * 5\n")

    # Verification 3: 16 is a power of 2, 5 IS a Fermat prime
    fermat_primes = {3, 5, 17, 257, 65537}
    assert 5 in fermat_primes, "5 IS a Fermat prime"
    assert 16 == 2 ** 4, "16 is a power of 2"
    print("Verification 3 PASSED: 16 is power of 2 and 5 IS Fermat prime\n")

    # Verification 4: R/r = 80 cusps per revolution
    R_over_r = 80
    print(f"Verification 4: R/r = {R_over_r}, cusps per revolution = {R_over_r}")
    assert R_over_r == 80
    print("Verification 4 PASSED\n")

    # Verification 5: cusp interval = 360/80 = 4.5 degrees EXACT
    cusp_interval = 360.0 / 80
    print(f"Cusp interval = {cusp_interval:.6f} degrees = {2 * math.pi / 80:.6f} radians")
    assert cusp_interval == 4.5, "360/80 = 4.5 exact"
    print("Verification 5 PASSED: 360/80 = 4.5 degrees EXACT\n")

    # Verification 6: 32 finite samples for all 4 shapes
    clamped_length = 32
    t_max_full = 2 * math.pi
    t_min_tight = -math.pi / 80
    t_max_tight = math.pi / 80
    t_max_partial = 2 * math.pi / 80

    shapes = [
        ('STANDARD', 0, t_max_full),
        ('INVERTED', t_max_full, 0),
        ('HEPTACONTADECAGON', 0, t_max_partial),
        ('TIGHT', t_min_tight, t_max_tight),
    ]
    for shape_name, t_min, t_max in shapes:
        finite_count = 0
        for i in range(clamped_length):
            t = t_min + (t_max - t_min) * i / max(1, clamped_length - 1)
            x, y = heptacontadecagon(t, a)
            if math.isfinite(x) and math.isfinite(y):
                finite_count += 1
        print(f"Shape {shape_name}: {finite_count}/{clamped_length} finite samples")
        assert finite_count == clamped_length, f"All samples should be finite for {shape_name}"
    print("Verification 6 PASSED: 32 finite samples for all 4 shapes\n")

    # Verification 7: xRange, yRange are non-degenerate
    samples = []
    for i in range(clamped_length):
        t = (2 * math.pi) * i / max(1, clamped_length - 1)
        samples.append(heptacontadecagon(t, a))
    x_min = min(p[0] for p in samples)
    x_max = max(p[0] for p in samples)
    y_min = min(p[1] for p in samples)
    y_max = max(p[1] for p in samples)
    x_range = max(0.01, x_max - x_min)
    y_range = max(0.01, y_max - y_min)
    print(f"x range: [{x_min:.4f}, {x_max:.4f}], xRange = {x_range:.4f}")
    print(f"y range: [{y_min:.4f}, {y_max:.4f}], yRange = {y_range:.4f}")
    assert x_range > 0.01
    assert y_range > 0.01
    print("Verification 7 PASSED: non-degenerate x/y ranges\n")

    print("All Day 831 verifications PASSED.")
    print(f"80-cusped hypocycloid (heptacontadecagon) verified:")
    print(f"  parametric: x = a*cos(t) + (a/79)*cos(79t), y = a*sin(t) - (a/79)*sin(79t)")
    print(f"  R/r = 80, 80 cusps per revolution, 4.5 degrees per cusp EXACT")
    print(f"  x at t=0 = {x0:.6f} = 80a/79")
    print(f"  80 = 2^4 * 5 IS constructible per Gauss-Wantzel 1837")


if __name__ == '__main__':
    main()
