#!/usr/bin/env python3
"""Day 873: Hectodiikos (122-cusped Hypocycloid) Notes - reproducibility script.

The hectodiikos is the 122-cusped hypocycloid. The parametric equations are:
    x(t) = a*cos(t) + (a/121)*cos(121t)
    y(t) = a*sin(t) - (a/121)*sin(121t)

Generated by a small circle of radius r = a/121 rolling without slipping INSIDE
a fixed circle of radius R = 122a/121 (R/r = 122, 122 cusps per revolution,
one cusp per 360/122 ~= 2.9508 degrees).

The hectodiikos has 122-fold rotational symmetry (D122 dihedral symmetry) with
122 inward-pointing cusps evenly distributed at ~2.9508 degree intervals around
the origin.

122 = 2 * 61 is a product of a power of 2 (2) and the prime 61 (which is NOT a
Fermat prime; Fermat primes are 3, 5, 17, 257, 65537), making the regular
hectodiikos NOT constructible by compass and straightedge (Gauss-Wantzel 1837
theorem: n is constructible iff n is a product of DISTINCT Fermat primes and a
power of 2; 61 fails the criterion since 61 is prime but not Fermat, despite
2 being a power of 2).
"""

import math

# Verify the parametric equations
def hectodiikos(t, a=4):
    a_over_121 = a / 121
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_121t = math.cos(121 * t)
    sin_121t = math.sin(121 * t)
    x = a * cos_t + a_over_121 * cos_121t
    y = a * sin_t - a_over_121 * sin_121t
    return x, y


def main():
    a = 4

    # At t=0: x = a*1 + (a/121)*1 = a + a/121 = 122a/121
    #         y = a*0 - (a/121)*0 = 0
    x_at_0, y_at_0 = hectodiikos(0, a)
    print(f"x at t=0 = {x_at_0:.6f} (expected {122*a/121:.6f} = 122a/121)")
    print(f"y at t=0 = {y_at_0:.6f} (expected 0.000000)")

    # Verify cusp count: R/r = 122 means 122 cusps per revolution
    R_over_r = 122
    cusp_interval_deg = 360.0 / R_over_r
    print(f"R/r = {R_over_r}")
    print(f"cusp interval = {cusp_interval_deg:.4f} degrees (~{cusp_interval_deg:.4f})")

    # Verify constructibility per Gauss-Wantzel 1837
    # 122 = 2 * 61, where 2 is a power of 2 but 61 is prime but not Fermat
    # So 122 is NOT constructible.
    fermat_primes = {3, 5, 17, 257, 65537}
    n = 122
    factors = []
    temp = n
    for p in [2, 3, 5, 7, 11, 13]:
        while temp % p == 0:
            factors.append(p)
            temp //= p
    if temp > 1:
        factors.append(temp)
    distinct_factors = set(factors)
    powers_of_2 = factors.count(2)
    other_primes = [f for f in distinct_factors if f != 2]
    is_constructible = (
        all(p in fermat_primes for p in other_primes) and
        powers_of_2 >= 1 and
        all(factors.count(p) == 1 for p in other_primes)
    )
    print(f"122 factors = {factors} (distinct: {sorted(distinct_factors)})")
    print(f"122 = 2 * 61, where 61 is prime but NOT Fermat")
    print(f"122 is constructible? {is_constructible} (expected False)")

    # Verify T_MAX and TIGHT_T_MIN/MAX
    t_max = 2 * math.pi / 122
    tight_t_min = -math.pi / 122
    tight_t_max = math.pi / 122
    print(f"HECTODIIKOS_NOTES_HECTODIIKOS_T_MAX = 2*PI/122 = {t_max:.6f}")
    print(f"HECTODIIKOS_NOTES_TIGHT_T_MIN = -PI/122 = {tight_t_min:.6f}")
    print(f"HECTODIIKOS_NOTES_TIGHT_T_MAX = +PI/122 = {tight_t_max:.6f}")

    # Verify 32 samples are all finite
    for shape in ('standard', 'inverted', 'hectodiikos', 'tight'):
        if shape == 'standard':
            t_min, t_max = 0, 2 * math.pi
        elif shape == 'inverted':
            t_min, t_max = 2 * math.pi, 0
        elif shape == 'hectodiikos':
            t_min, t_max = 0, 2 * math.pi / 122
        else:  # tight
            t_min, t_max = -math.pi / 122, math.pi / 122
        finite_count = 0
        for i in range(32):
            t = t_min + (t_max - t_min) * i / max(1, 32 - 1)
            x, y = hectodiikos(t, a)
            if math.isfinite(x) and math.isfinite(y):
                finite_count += 1
        print(f"shape={shape}: {finite_count}/32 finite samples")

    # Verify x/y ranges for standard shape
    samples = []
    for i in range(32):
        t = 0 + (2 * math.pi) * i / max(1, 32 - 1)
        x, y = hectodiikos(t, a)
        samples.append((x, y))
    xs = [s[0] for s in samples]
    ys = [s[1] for s in samples]
    print(f"xRange = [{min(xs):.4f}, {max(xs):.4f}], yRange = [{min(ys):.4f}, {max(ys):.4f}]")


if __name__ == '__main__':
    main()
