#!/usr/bin/env python3
"""
Day 886 reproducibility script for the Hectopentatriacontagon (135-cusped Hypocycloid) Notes feature.

Verifies the parametric formula:
  x(t) = a*cos(t) + (a/134)*cos(134t)
  y(t) = a*sin(t) - (a/134)*sin(134t)

135 = 100 + 35 = hecto-100 + penta-5 + triaconta-30 (hectopentatriacontagon = 135 sides).
R/r = 135, generated by a small circle of radius r = a/134 rolling inside
a fixed circle of radius R = 135a/134. 135 cusps per revolution, one cusp
per 360°/135 = 2.6667° = 2*PI/135 of revolution.

135 = 3^3 × 5. 3 IS a Fermat prime but appears with multiplicity 3 in 3^3 = 27
(failing the Gauss-Wantzel 1837 distinctness criterion). 5 IS also a Fermat prime.
So 135 = 3^3 * 5 has TWO non-distinct prime factors (3 has multiplicity 3) plus
a distinct Fermat prime (5), and the multiplicity violation is enough to fail
Gauss-Wantzel. 135 is NOT constructible.
"""
import math

N = 135  # number of cusps
A = 4  # scale parameter
R_OVER_R = N  # 135 cusps per revolution
A_OVER_R_FACTOR = N - 1  # 134 (small circle radius divisor)

x_at_zero = A + A / A_OVER_R_FACTOR
y_at_zero = 0
t_max = 2 * math.pi / N  # T_MAX
tight_t_max = math.pi / N  # TIGHT_T_MAX
print(f"x at t=0 = {x_at_zero:.6f} = {N}a/{A_OVER_R_FACTOR} (expected {N}*{A}/{A_OVER_R_FACTOR} = {N*A/A_OVER_R_FACTOR:.6f})")
print(f"HECTOPENTATRIACONTAGON_NOTES_HECTOPENTATRIACONTAGON_T_MAX = 2*PI/{N} = {t_max:.6f}")
print(f"HECTOPENTATRIACONTAGON_NOTES_TIGHT_T_MAX = PI/{N} = {tight_t_max:.6f}")

shapes = ['standard', 'inverted', 'hectopentatriacontagon', 'tight']
for shape in shapes:
    finite_count = 0
    for i in range(32):
        t = t_max * i / max(1, 31)
        cosT = math.cos(t)
        sinT = math.sin(t)
        cos134T = math.cos(134 * t)
        sin134T = math.sin(134 * t)
        x = A * cosT + (A / 134) * cos134T
        y = A * sinT - (A / 134) * sin134T
        if math.isfinite(x) and math.isfinite(y):
            finite_count += 1
    print(f"  Shape {shape}: {finite_count}/32 finite samples for 32-sided sample sweep")

cusp_deg = 360.0 / N
print(f"\nCusp interval: 360/{N} = {cusp_deg:.4f}° = 2*PI/{N} = {2*math.pi/N:.6f} rad")
print(f"\n135 = 3^3 × 5")
print(f"3 IS a Fermat prime but appears with multiplicity 3 in 27, failing distinctness (Gauss-Wantzel 1837)")
print(f"5 IS a Fermat prime")
print(f"Therefore 135 is NOT constructible per Gauss-Wantzel 1837")
print(f"R/r ratio: 135 (R = 135a/134, r = a/134)")

xs, ys = [], []
for i in range(64):
    t = t_max * i / 63
    cosT = math.cos(t)
    sinT = math.sin(t)
    cos134T = math.cos(134 * t)
    sin134T = math.sin(134 * t)
    x = A * cosT + (A / 134) * cos134T
    y = A * sinT - (A / 134) * sin134T
    if math.isfinite(x) and math.isfinite(y):
        xs.append(x)
        ys.append(y)
if xs:
    print(f"\n64-sample sweep x range: [{min(xs):.4f}, {max(xs):.4f}]")
    print(f"64-sample sweep y range: [{min(ys):.4f}, {max(ys):.4f}]")

print(f"\nDay 885 was the 34th value in the 100+ post-100 hypocycloid series (134 cusps).")
print(f"Day 886 is the 35th value in the 100+ post-100 hypocycloid series (135 cusps).")
