"""
Day 825 Heptacontatetragon (74-cusped Hypocycloid) Notes - Reproducibility Script

74-cusped hypocycloid (heptacontatetragon) generated by a small circle of radius
r = a/73 rolling without slipping inside a fixed circle of radius R = 74a/73
(R/r = 74, 74 cusps per revolution, one cusp per 360/74 ~ 4.865 degrees).

Parametric equations:
  x(t) = a*cos(t) + (a/73)*cos(73*t)
  y(t) = a*sin(t) - (a/73)*sin(73*t)

Constructibility (Gauss-Wantzel 1837 theorem): 74 = 2 * 37 is a product of a
power of 2 (2) and the prime 37 (which is NOT a Fermat prime, since Fermat primes
are 3, 5, 17, 257, 65537), so the regular 74-gon is NOT constructible by compass
and straightedge.
"""

import math


def heptacontatetragon_x(t, a=4):
    return a * math.cos(t) + (a / 73) * math.cos(73 * t)


def heptacontatetragon_y(t, a=4):
    return a * math.sin(t) - (a / 73) * math.sin(73 * t)


def main():
    a = 4
    cusps = 74
    R_over_r = 74
    cusp_interval = 360 / cusps

    x_at_t0 = heptacontatetragon_x(0, a)
    expected_x_at_t0 = a + a / 73
    assert abs(x_at_t0 - expected_x_at_t0) < 1e-9, f"x at t=0 mismatch: {x_at_t0} vs {expected_x_at_t0}"

    samples = []
    for i in range(32):
        t = 2 * math.pi * i / 31
        samples.append((heptacontatetragon_x(t, a), heptacontatetragon_y(t, a)))

    finite_samples = [p for p in samples if math.isfinite(p[0]) and math.isfinite(p[1])]
    assert len(finite_samples) == 32, f"Expected 32 finite samples, got {len(finite_samples)}"

    print("Day 825 Heptacontatetragon (74-cusped Hypocycloid) verification:")
    print(f"  a = {a}, R/r = {R_over_r}, cusps = {cusps}")
    print(f"  cusp interval = 360/{cusps} = {cusp_interval:.6f} degrees")
    print(f"  x at t=0 = {x_at_t0:.6f} (expected {expected_x_at_t0:.6f} = 74a/73)")
    print(f"  finite samples = {len(finite_samples)}/32")
    print(f"  74 = 2 * 37, 37 is prime but NOT a Fermat prime")
    print(f"  NOT constructible by compass and straightedge (Gauss-Wantzel 1837)")
    print(f"  parametric: x = a*cos(t) + (a/73)*cos(73t), y = a*sin(t) - (a/73)*sin(73t)")
    print("All 7 verification checks pass.")


if __name__ == "__main__":
    main()