#!/usr/bin/env python3
"""
Day 813 reproducibility script for Hexacontadigon (62-cusped Hypocycloid) Notes.

The hexacontadigon is the 62-cusped hypocycloid generated by a small circle of
radius r = a/61 rolling without slipping INSIDE a fixed circle of radius R = 62a/61
(R/r = 62). The parametric equations are:

    x(t) = a*cos(t) + (a/61)*cos(61*t)
    y(t) = a*sin(t) - (a/61)*sin(61*t)

62-fold rotational D62 dihedral symmetry, 62 inward-pointing cusps evenly
distributed at 360/62 ≈ 5.8065 degrees intervals around the origin.

62 = 2 * 31 is a composite number; 31 is the 11th prime (a Mersenne prime,
2^5 - 1 = 31) but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537),
so the regular 62-gon is NOT constructible by compass and straightedge
(Gauss-Wantzel 1837 theorem: n is constructible iff n is a product of distinct
Fermat primes and a power of 2; 31 fails the Fermat criterion).

This script verifies:
1. The parametric equations evaluate correctly.
2. The rightmost extreme at t=0 is at (62a/61, 0).
3. The hexacontadigon has 62 cusps per revolution.
4. 62 = 2 * 31 with 31 prime and not a Fermat prime.

Usage: python3 scripts/day813_hexacontadigon.py
"""

import math


def hexacontadigon_parametric(t, a):
    """Compute (x, y) on the 62-cusped hypocycloid at parameter t."""
    cosT = math.cos(t)
    sinT = math.sin(t)
    cos61T = math.cos(61 * t)
    sin61T = math.sin(61 * t)
    x = a * cosT + (a / 61) * cos61T
    y = a * sinT - (a / 61) * sin61T
    return (x, y)


def cusp_count_check(N=1024, a=4.0):
    """Check that the curve has ~62 cusps per revolution."""
    cusp_count = 0
    prev_r = None
    sign = None
    for i in range(N):
        t = 2 * math.pi * i / N
        x, y = hexacontadigon_parametric(t, a)
        r = math.sqrt(x * x + y * y)
        if prev_r is not None and abs(r - prev_r) > 1e-6:
            new_sign = (r > prev_r)
            if sign is not None and new_sign != sign:
                cusp_count += 1
            sign = new_sign
        prev_r = r
    return cusp_count // 2  # each cusp gives two sign changes


def is_prime(n):
    if n < 2:
        return False
    if n < 4:
        return True
    if n % 2 == 0:
        return False
    for k in range(3, int(math.isqrt(n)) + 1, 2):
        if n % k == 0:
            return False
    return True


def is_fermat_prime(n):
    """A Fermat prime is a Fermat number F_k = 2^(2^k) + 1 that is prime."""
    if n < 3:
        return False
    # Check if n-1 is a power of 2, and that 2^(n-1) == 1 mod n
    if n - 1 & (n - 2) == 0:
        # n-1 is a power of 2 (no, actually n-1 must be of form 2^(2^k))
        # Check that log2(n-1) is itself a power of 2
        m = n - 1
        if m & (m - 1) == 0:  # power of 2
            # Check that log2(m) is a power of 2
            k = int(math.log2(m))
            if (1 << k) == m and (k & (k - 1)) == 0:
                return True
    return False


def main():
    a = 4.0
    print("=" * 60)
    print("Day 813: Hexacontadigon (62-cusped Hypocycloid) Notes")
    print("=" * 60)
    print(f"Scale parameter a = {a}")
    print(f"R/r ratio = 62 (62 cusps per revolution)")
    print(f"Cusp interval = 360/62 = {360 / 62:.6f} degrees")
    print()

    # Test 1: At t=0, x = a + a/61 = 62a/61
    x0, y0 = hexacontadigon_parametric(0, a)
    print(f"[Test 1] At t=0: x = {x0:.6f}, y = {y0:.6f}")
    print(f"  Expected: x = 62a/61 = {62 * a / 61:.6f}, y = 0")
    assert abs(x0 - 62 * a / 61) < 1e-9, f"x0 != 62a/61: {x0}"
    assert abs(y0) < 1e-9, f"y0 should be 0: {y0}"
    print("  PASS")

    # Test 2: Period is 2*pi
    x1, y1 = hexacontadigon_parametric(0, a)
    x2, y2 = hexacontadigon_parametric(2 * math.pi, a)
    print(f"\n[Test 2] Periodicity check:")
    print(f"  At t=0:        ({x1:.6f}, {y1:.6f})")
    print(f"  At t=2*pi:     ({x2:.6f}, {y2:.6f})")
    assert abs(x1 - x2) < 1e-9 and abs(y1 - y2) < 1e-9
    print("  PASS")

    # Test 3: Cusp count ≈ 62
    n_cusps = cusp_count_check(N=4096, a=a)
    print(f"\n[Test 3] Cusp count: {n_cusps} (expected ≈ 62)")
    assert 60 <= n_cusps <= 64, f"Cusp count out of range: {n_cusps}"
    print("  PASS")

    # Test 4: 62 = 2 * 31
    print(f"\n[Test 4] 62 = 2 * 31: {62 == 2 * 31}")
    assert 62 == 2 * 31
    print("  PASS")

    # Test 5: 31 is prime
    print(f"\n[Test 5] 31 is prime: {is_prime(31)}")
    assert is_prime(31)
    print("  PASS")

    # Test 6: 31 is NOT a Fermat prime
    print(f"\n[Test 6] 31 is a Fermat prime: {is_fermat_prime(31)}")
    assert not is_fermat_prime(31)
    print("  PASS (62-gon NOT constructible by compass and straightedge)")

    # Test 7: Sample shape variations
    print(f"\n[Test 7] Shape variations at sample points:")
    for shape_name, (t_min, t_max) in [
        ('STANDARD', (0, 2 * math.pi)),
        ('INVERTED', (2 * math.pi, 0)),
        ('HEXACONTADIGON', (0, 2 * math.pi / 62)),
        ('TIGHT', (-math.pi / 62, math.pi / 62)),
    ]:
        t_mid = (t_min + t_max) / 2
        x, y = hexacontadigon_parametric(t_mid, a)
        print(f"  {shape_name:20s} t_min={t_min:.4f} t_max={t_max:.4f} -> ({x:.4f}, {y:.4f})")
    print("  PASS")

    # Test 8: 31 = 2^5 - 1 (Mersenne prime)
    print(f"\n[Test 8] 31 = 2^5 - 1: {31 == 2**5 - 1}")
    assert 31 == 2**5 - 1
    print("  PASS (31 is a Mersenne prime)")

    print("\n" + "=" * 60)
    print("All Day 813 Hexacontadigon tests passed!")
    print("=" * 60)


if __name__ == '__main__':
    main()