#!/usr/bin/env python3
"""Day 875: Hectotessaraikos (124-cusped Hypocycloid) Notes — reproducibility script.

The hectotessaraikos is a 124-cusped hypocycloid generated by a small circle of
radius r = a/123 rolling without slipping inside a fixed circle of radius
R = 124a/123 (R/r = 124, 124 cusps per revolution).

Parametric equations:
    x(t) = a*cos(t) + (a/123)*cos(123t)
    y(t) = a*sin(t) - (a/123)*sin(123t)

124 = 2^2 * 31. Since 31 is prime but NOT a Fermat prime (Fermat primes are
3, 5, 17, 257, 65537), the regular 124-gon is NOT constructible by compass
and straightedge (Gauss-Wantzel 1837 theorem: n is constructible iff n is a
product of DISTINCT Fermat primes and a power of 2).
"""

import math
import sys

A = 4
N = 124  # number of cusps
SMALL_R_DIVISOR = 123  # 124 - 1, the parametric multiplier
SCALE = A
A_OVER = SCALE / SMALL_R_DIVISOR

# Verification 1: x at t=0 should equal a + a/123 = 124a/123
x_at_0 = SCALE * math.cos(0) + A_OVER * math.cos(0)
expected_x_0 = 124 * SCALE / 123
print(f"x at t=0 = {x_at_0:.6f} = 124a/123 = {expected_x_0:.6f}")
assert abs(x_at_0 - expected_x_0) < 1e-10, f"FAIL: x(0) = {x_at_0}, expected {expected_x_0}"
print("PASS: x(0) = 124a/123 verified")

# Verification 2: 124 = 2^2 * 31, NOT constructible per Gauss-Wantzel 1837
# (31 is prime but NOT a Fermat prime; 4 IS a power of 2 but 31 fails the criterion)
print(f"\n124 = 2^2 * 31 (4 is a power of 2, 31 is prime but NOT Fermat)")
print(f"NOT constructible per Gauss-Wantzel 1837 (31 fails the Fermat-prime criterion)")
assert 124 == 4 * 31
print("PASS: 124 = 4 * 31, NOT constructible")

# Verification 3: 32 finite samples for all 4 shapes
SAMPLES_LEN = 32

shape_ranges = {
    "standard": (0, 2 * math.pi),
    "inverted": (2 * math.pi, 0),
    "hectotessaraikos": (0, 2 * math.pi / 124),
    "tight": (-math.pi / 124, math.pi / 124),
}

print(f"\n=== {SAMPLES_LEN} sample test for all 4 shapes ===")
for shape, (t_min, t_max) in shape_ranges.items():
    finite_count = 0
    xs, ys = [], []
    for i in range(SAMPLES_LEN):
        t = t_min + (t_max - t_min) * i / max(1, SAMPLES_LEN - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_nt = math.cos(SMALL_R_DIVISOR * t)
        sin_nt = math.sin(SMALL_R_DIVISOR * t)
        x = SCALE * cos_t + A_OVER * cos_nt
        y = SCALE * sin_t - A_OVER * sin_nt
        if math.isfinite(x) and math.isfinite(y):
            finite_count += 1
            xs.append(x)
            ys.append(y)
    assert finite_count == SAMPLES_LEN, f"FAIL: shape={shape}, finite_count={finite_count}, expected {SAMPLES_LEN}"
    x_range = max(xs) - min(xs) if xs else 0
    y_range = max(ys) - min(ys) if ys else 0
    print(f"  shape={shape}: {finite_count}/{SAMPLES_LEN} finite samples, xRange={x_range:.4f}, yRange={y_range:.4f}")

print(f"\nPASS: All 4 shapes produce {SAMPLES_LEN}/{SAMPLES_LEN} finite samples")

# Verification 4: cusp interval ~2.9032 degrees (360/124)
cusp_interval_deg = 360.0 / 124
cusp_interval_rad = 2 * math.pi / 124
print(f"\nCusp interval: 360°/124 = {cusp_interval_deg:.4f}° = 2π/124 = {cusp_interval_rad:.6f} rad")
print(f"R/r = 124, parametric divisor = {SMALL_R_DIVISOR}")

# Verification 5: HECTOTESSARAIKOS_NOTES_HECTOTESSARAIKOS_T_MAX = 2*PI/124
T_MAX = 2 * math.pi / 124
print(f"\nHECTOTESSARAIKOS_NOTES_HECTOTESSARAIKOS_T_MAX = 2*PI/124 = {T_MAX:.12f}")

# Verification 6: TIGHT_T_MIN/MAX = ±PI/124
TIGHT_MAX = math.pi / 124
TIGHT_MIN = -math.pi / 124
print(f"HECTOTESSARAIKOS_NOTES_TIGHT_T_MIN/MAX = ±PI/124 = ±{TIGHT_MAX:.12f}")

print("\n=== ALL VERIFICATION CHECKS PASSED ===")
print("Day 875 Hectotessaraikos (124-cusped) feature complete.")
