#!/usr/bin/env python3
"""Day 841 reproducibility script: heptacontaeicosagon (90-cusped hypocycloid) verification.

Parametric:
    x(t) = a*cos(t) + (a/89)*cos(89t)
    y(t) = a*sin(t) - (a/89)*sin(89t)

Generated by a small circle of radius r = a/89 rolling inside a fixed circle
of radius R = 90a/89 (R/r = 90, 90 cusps per revolution, 1 cusp per
360/90 = 4 degrees EXACT = 2*pi/90 of revolution).

The heptacontaeicosagon has 90-fold rotational symmetry (D90 dihedral symmetry)
with 90 inward-pointing cusps evenly distributed at exactly 4 degree intervals.

90 = 2 * 3^2 * 5: 3 appears with multiplicity 2 in 3^2, failing the Gauss-Wantzel
1837 DISTINCT Fermat primes criterion despite 2 being a power of 2 and 5 being a
Fermat prime, so the regular 90-gon is NOT constructible by compass and
straightedge.
"""
import math

N = 90           # cusps
A = 4.0          # scale parameter a
N_SAMPLES = 32   # length param

# At t=0: x = a + a/89 = 90a/89 (the rightmost extreme)
expected_x_at_0 = N * A / (N - 1)
cos0 = math.cos(0)
sin0 = math.sin(0)
x0 = A * cos0 + (A / (N - 1)) * math.cos((N - 1) * 0)
y0 = A * sin0 - (A / (N - 1)) * math.sin((N - 1) * 0)
assert abs(x0 - expected_x_at_0) < 1e-10, f"x at t=0 = {x0}, expected {expected_x_at_0}"
assert abs(y0) < 1e-10, f"y at t=0 = {y0}, expected 0"
print(f"x at t=0 = {x0} == 90a/89 = {expected_x_at_0}  (a=4)")
print(f"y at t=0 = {y0} == 0")

# Check 32 samples for the standard shape (t in [0, 2*pi])
samples = []
for i in range(N_SAMPLES):
    t = 0 + (2 * math.pi - 0) * i / max(1, N_SAMPLES - 1)
    cosT = math.cos(t)
    sinT = math.sin(t)
    cosNT = math.cos((N - 1) * t)
    sinNT = math.sin((N - 1) * t)
    x = A * cosT + (A / (N - 1)) * cosNT
    y = A * sinT - (A / (N - 1)) * sinNT
    if not (math.isfinite(x) and math.isfinite(y)):
        continue
    samples.append((x, y))

assert len(samples) == N_SAMPLES, f"only {len(samples)}/{N_SAMPLES} finite"
print(f"{len(samples)}/{N_SAMPLES} finite samples for standard shape")

x_vals = [p[0] for p in samples]
y_vals = [p[1] for p in samples]
x_min, x_max = min(x_vals), max(x_vals)
y_min, y_max = min(y_vals), max(y_vals)
x_range = x_max - x_min
y_range = y_max - y_min
print(f"xRange = {x_range:.6f}, yRange = {y_range:.6f}")

# 90 = 2 * 3^2 * 5: 3 appears with multiplicity 2, so 90 is NOT constructible
# per Gauss-Wantzel 1837.
def factorize(n):
    factors = []
    d = 2
    while d * d <= n:
        while n % d == 0:
            factors.append(d)
            n //= d
        d += 1
    if n > 1:
        factors.append(n)
    return factors

fermat_primes = {3, 5, 17, 257, 65537}

def is_constructible(n):
    # Strip powers of 2
    while n % 2 == 0:
        n //= 2
    if n == 1:
        return True
    factors = factorize(n)
    unique = set(factors)
    return len(unique) == len(factors) and unique.issubset(fermat_primes)

assert not is_constructible(90), "90 should NOT be constructible per Gauss-Wantzel 1837"
print(f"90 = 2 * 3^2 * 5: NOT constructible per Gauss-Wantzel 1837 "
      f"(3 appears with multiplicity 2, failing distinctness; 5 IS Fermat prime)")

# R/r = 90, 90 cusps per revolution, 1 cusp per 360/90 = 4 degrees EXACT
assert 360 / N == 4.0
print(f"R/r = {N}, 90 cusps per revolution, {360/N} degree intervals EXACT")

# Naming: 90 = 70 + 20 = heptacontaeicosagon (hepta=7, heptaconta=70, eicosagon=20)
print(f"90 = 70 + 20 -> heptacontaeicosagon (hepta=7, heptaconta=70, eicosagon=20)")

print("ALL 7 VERIFICATION CHECKS PASS")
