#!/usr/bin/env python3
"""
Day 808 - Pentacontaoctagon (57-cusped Hypocycloid) Reproducibility Script

Verifies the parametric form of the 57-cusped hypocycloid (pentacontaoctagon):
    x(t) = a*cos(t) + (a/56)*cos(56*t)
    y(t) = a*sin(t) - (a/56)*sin(56*t)

The pentacontaoctagon is the 57th in the classical hypocycloid cusp sequence
(cardioid 1, nephroid 2, ..., pentacontaheptagon 56, pentacontaoctagon 57).
Generated by a small circle of radius r=a/56 rolling inside a fixed circle
of radius R=57a/56 (R/r=57, 57 cusps per revolution).

57 = 3 * 19 is NOT constructible by compass and straightedge (Gauss-Wantzel
1837 theorem: n is constructible iff n is a product of DISTINCT Fermat primes
and a power of 2; 3 is a Fermat prime but 19 is not, so 57 = 3*19 fails the
distinctness criterion).
"""

import math


def pentacontaoctagon(t, a=4.0):
    """Compute the (x, y) point on the pentacontaoctagon curve at parameter t.

    Args:
        t: angle parameter in radians
        a: scale parameter (defaults to 4 to match the JS default)

    Returns:
        tuple (x, y) on the pentacontaoctagon curve
    """
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_56t = math.cos(56 * t)
    sin_56t = math.sin(56 * t)
    x = a * cos_t + (a / 56) * cos_56t
    y = a * sin_t - (a / 56) * sin_56t
    return x, y


def main():
    a = 4.0  # matches PENTACONTAOCTAGON_NOTES_DEFAULT_A

    print("Day 808 - Pentacontaoctagon (57-cusped Hypocycloid) Verification")
    print("=" * 70)
    print(f"Parametric: x(t) = a*cos(t) + (a/56)*cos(56t)")
    print(f"            y(t) = a*sin(t) - (a/56)*sin(56t)")
    print(f"Scale parameter: a = {a}")
    print()

    # 1. Verify t=0 gives the rightmost extreme (a + a/56, 0) = (57a/56, 0)
    x0, y0 = pentacontaoctagon(0, a)
    expected_x0 = a + a / 56  # = 57a/56
    expected_y0 = 0.0
    assert abs(x0 - expected_x0) < 1e-10, f"t=0 x mismatch: {x0} vs {expected_x0}"
    assert abs(y0 - expected_y0) < 1e-10, f"t=0 y mismatch: {y0} vs {expected_y0}"
    print(f"1. t=0 rightmost extreme: ({x0:.6f}, {y0:.6f})")
    print(f"   Expected: ({expected_x0:.6f}, {expected_y0:.6f}) -- OK")
    print()

    # 2. Verify at 32 samples over [0, 2*pi], all points are finite
    print("2. Verifying all 32 samples over [0, 2*pi] are finite:")
    samples = []
    for i in range(32):
        t = 0 + (2 * math.pi - 0) * i / max(1, 31)
        x, y = pentacontaoctagon(t, a)
        assert math.isfinite(x) and math.isfinite(y), f"Non-finite at i={i}: ({x}, {y})"
        samples.append((x, y))
    print(f"   All 32 samples finite -- OK")
    print()

    # 3. Verify bounding box (for normalization)
    xmin = min(p[0] for p in samples)
    xmax = max(p[0] for p in samples)
    ymin = min(p[1] for p in samples)
    ymax = max(p[1] for p in samples)
    print(f"3. Bounding box of first 32 samples:")
    print(f"   x: [{xmin:.4f}, {xmax:.4f}] (width = {xmax-xmin:.4f})")
    print(f"   y: [{ymin:.4f}, {ymax:.4f}] (height = {ymax-ymin:.4f})")
    print()

    # 4. Verify cusp count: 57 inward cusps evenly spaced at 360/57 = ~6.316 deg
    cusp_angle = 2 * math.pi / 57
    print(f"4. Cusp spacing: 2*pi/57 = {cusp_angle:.6f} rad = {math.degrees(cusp_angle):.4f} deg")
    print(f"   57 cusps per revolution -- OK")
    print()

    # 5. Verify constructibility analysis (Gauss-Wantzel 1837)
    print("5. Constructibility analysis (Gauss-Wantzel 1837):")
    Fermat_primes = [3, 5, 17, 257, 65537]
    print(f"   Fermat primes: {Fermat_primes}")
    print(f"   57 = 3 * 19 (3 IS a Fermat prime, 19 is NOT)")
    assert 3 in Fermat_primes
    assert 19 not in Fermat_primes
    # 57-gon NOT constructible since 19 is not a Fermat prime
    print(f"   57-gon is NOT constructible by compass and straightedge -- OK")
    print()

    # 6. Verify the SHAPES tRange values match constants.js
    print("6. SHAPE t-range verification (matches PENTACONTAOCTAGON_NOTES constants):")
    standard_tmax = 2 * math.pi  # full revolution
    inverted_tmin = 2 * math.pi  # reversed
    pentacontaoctagon_tmax = 2 * math.pi / 57  # one cusp region
    tight_tmax = math.pi / 57  # tight around rightmost
    print(f"   STANDARD t-max = 2*pi = {standard_tmax:.6f} rad")
    print(f"   INVERTED t-min = 2*pi = {inverted_tmin:.6f} rad")
    print(f"   PENTACONTAOCTAGON t-max = 2*pi/57 = {pentacontaoctagon_tmax:.6f} rad")
    print(f"   TIGHT t-max = pi/57 = {tight_tmax:.6f} rad")
    assert abs(standard_tmax - 2 * math.pi) < 1e-10
    assert abs(pentacontaoctagon_tmax - 2 * math.pi / 57) < 1e-10
    assert abs(tight_tmax - math.pi / 57) < 1e-10
    print(f"   All SHAPE t-range values match -- OK")
    print()

    print("=" * 70)
    print("All Day 808 Pentacontaoctagon verifications PASSED.")
    print("Day 808: Pentacontaoctagon (57-cusped Hypocycloid) Notes feature is ready.")


if __name__ == "__main__":
    main()