#!/usr/bin/env python3
"""
Day 879 Hectoicosikaioctagon (128-cusped Hypocycloid) verification script.

The hectoicosikaioctagon is the 128-cusped hypocycloid extending the 1-127 cusp
sequence past Day 878's 127-cusped hectoicosikaiheptagon. It is the FIRST
hecto-100+ value that is a pure power of 2 (since 2^6 = 64 < 100 < 128 = 2^7).

Parametric:
  x(t) = a*cos(t) + (a/127)*cos(127t)
  y(t) = a*sin(t) - (a/127)*sin(127t)
generated by a small circle of radius r = a/127 rolling inside a fixed
circle of radius R = 128a/127 (R/r = 128).

128-fold D128 dihedral symmetry, 128 inward-pointing cusps at 360/128 = 2.8125°
intervals = 2*pi/128 rad.

128 = 2^7 is a pure power of 2, making the regular hectoicosikaioctagon
CONSTRUCTIBLE by compass and straightedge (Gauss-Wantzel 1837 theorem:
n is constructible iff n is a product of DISTINCT Fermat primes and a
power of 2; 2^7 satisfies the criterion).
"""
import math

N = 128
a = 4.0
length = 32
PI = math.pi

print(f"=== Day 879 Hectoicosikaioctagon (128-cusped Hypocycloid) ===\n")
print(f"N = {N}")
print(f"2^7 = {2**7}")
print(f"128 = 2^7 (pure power of 2): CONSTRUCTIBLE per Gauss-Wantzel 1837")
print(f"a/(N-1) = a/{N-1} = {a/(N-1):.16f}")
print(f"")
print(f"x at t=0 = a*cos(0) + (a/127)*cos(0) = {a + a/(N-1):.16f} = 128a/127 = {128*a/127}")
print(f"y at t=0 = a*sin(0) - (a/127)*sin(0) = 0.0")
print(f"")

shapes = {
    "standard":        [0.0, 2*PI],
    "inverted":         [2*PI, 0.0],
    "hectoicosikaioctagon": [0.0, 2*PI / N],
    "tight":           [-PI / N, PI / N],
}

for name, (t_min, t_max) in shapes.items():
    finite = 0
    xmin, xmax, ymin, ymax = math.inf, -math.inf, math.inf, -math.inf
    for i in range(length):
        t = t_min + (t_max - t_min) * i / max(1, length - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_Nt = math.cos(N * t)
        sin_Nt = math.sin(N * t)
        a_over = a / (N - 1)
        x = a * cos_t + a_over * cos_Nt
        y = a * sin_t - a_over * sin_Nt
        if not (math.isfinite(x) and math.isfinite(y)):
            continue
        finite += 1
        if x < xmin: xmin = x
        if x > xmax: xmax = x
        if y < ymin: ymin = y
        if y > ymax: ymax = y
    print(f"--- {name} ---")
    print(f"  samples: {finite}/{length} finite")
    print(f"  xRange: {xmax-xmin:.4f} [{xmin:.4f}, {xmax:.4f}]")
    print(f"  yRange: {ymax-ymin:.4f} [{ymin:.4f}, {ymax:.4f}]")

print(f"")
print(f"=== Key insights ===")
print(f"128 = 2^7 is a pure power of 2 (the FIRST 2^k >= 100 in the 2^k series)")
print(f"  (the previous 2^6 = 64 is below 100, so this is the first hecto-100+ value")
print(f"   that is a pure power of 2)")
print(f"")
print(f"T_MAX constants:")
print(f"  HECTOICOSIKAIOCTAGON_NOTES_HECTOICOSIKAIOCTAGON_T_MAX = 2*PI/128 = {2*PI/128}")
print(f"  HECTOICOSIKAIOCTAGON_NOTES_TIGHT_T_MIN = -PI/128 = {-PI/128}")
print(f"  HECTOICOSIKAIOCTAGON_NOTES_TIGHT_T_MAX =  PI/128 = {PI/128}")
print(f"")
print(f"Cusp interval: 360/128 = {360/128} degrees = 2*pi/128 rad = {2*PI/128} rad")
print(f"R/r = {N}/1 = {N}")
print(f"a/R = 1/{N}, r = a/{N-1}")
print(f"Generator: small circle of radius r = a/{N-1} rolling inside fixed circle of radius R = {N}*a/{N-1}")
print(f"")
print(f"128 = 2^7; Mersenne neighbor 2^7-1 = 127 (the 7th Mersenne prime = Day 878's hectoicosikaiheptagon)")
print(f"")
print(f"Gauss-Wantzel 1837 summary: 2^7 is constructible since it is a pure power of 2")
print(f"128-fold rotational symmetry is FORBIDDEN in classical crystallography (Bravais 1850")
print(f"  only allows 1, 2, 3, 4, 6-fold rotations in periodic crystals).")
