#!/usr/bin/env python3
"""Day 830: Heptacontanennegon (79-cusped Hypocycloid) Notes reproducibility script.

The heptacontanennegon is the 79-cusped hypocycloid generated by a small circle of radius
r = a/78 rolling without slipping INSIDE a fixed circle of radius R = 79a/78 (R/r = 79,
79 cusps per revolution, one cusp per 360/79 degrees).

Parametric equations:
    x(t) = a*cos(t) + (a/78)*cos(78t)
    y(t) = a*sin(t) - (a/78)*sin(78t)

At t=0: x = a + a/78 = 79a/78 (the rightmost extreme).

79 IS prime (22nd prime) but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537).
So per Gauss-Wantzel 1837, the regular 79-gon is NOT constructible by compass and straightedge.
"""

import math


def heptacontanennegon(t, a):
    """Compute (x, y) on the 79-cusped hypocycloid curve at parameter t."""
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_78t = math.cos(78 * t)
    sin_78t = math.sin(78 * t)
    a_over_78 = a / 78
    x = a * cos_t + a_over_78 * cos_78t
    y = a * sin_t - a_over_78 * sin_78t
    return x, y


def main():
    a = 4  # scale parameter

    # Verification 1: at t=0, x = 79a/78 and y = 0
    x0, y0 = heptacontanennegon(0, a)
    expected_x0 = 79 * a / 78
    print(f"x at t=0 = {x0:.6f} (expected {expected_x0:.6f} = 79a/78)")
    assert abs(x0 - expected_x0) < 1e-9, f"x at t=0 should be {expected_x0}"
    assert abs(y0) < 1e-9, f"y at t=0 should be 0"
    print(f"y at t=0 = {y0:.6f}")
    print("Verification 1 PASSED: x at t=0 = 79a/78, y at t=0 = 0\n")

    # Verification 2: 79 IS prime (22nd prime)
    def is_prime(n):
        if n < 2:
            return False
        if n == 2:
            return True
        if n % 2 == 0:
            return False
        for i in range(3, int(math.sqrt(n)) + 1, 2):
            if n % i == 0:
                return False
        return True
    assert is_prime(79), "79 must be prime"
    print("Verification 2 PASSED: 79 IS prime (22nd prime)\n")

    # Verification 3: 79 is NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537)
    fermat_primes = {3, 5, 17, 257, 65537}
    assert 79 not in fermat_primes, "79 must not be a Fermat prime"
    print("Verification 3 PASSED: 79 is NOT a Fermat prime (Gauss-Wantzel 1837)\n")

    # Verification 4: R/r = 79 cusps per revolution
    R_over_r = 79
    print(f"Verification 4: R/r = {R_over_r}, cusps per revolution = {R_over_r}")
    assert R_over_r == 79
    print("Verification 4 PASSED\n")

    # Verification 5: cusp interval ~4.5570 degrees
    cusp_interval = 360.0 / 79
    print(f"Cusp interval = {cusp_interval:.6f} degrees = {2 * math.pi / 79:.6f} radians")
    assert abs(cusp_interval - 360.0 / 79) < 1e-9
    print("Verification 5 PASSED: 360/79 cusp intervals\n")

    # Verification 6: 32 finite samples for all 4 shapes
    clamped_length = 32
    t_max_full = 2 * math.pi
    t_min_tight = -math.pi / 79
    t_max_tight = math.pi / 79
    t_max_partial = 2 * math.pi / 79

    shapes = [
        ('STANDARD', 0, t_max_full),
        ('INVERTED', t_max_full, 0),
        ('HEPTACONTANENNEGON', 0, t_max_partial),
        ('TIGHT', t_min_tight, t_max_tight),
    ]
    for shape_name, t_min, t_max in shapes:
        finite_count = 0
        for i in range(clamped_length):
            t = t_min + (t_max - t_min) * i / max(1, clamped_length - 1)
            x, y = heptacontanennegon(t, a)
            if math.isfinite(x) and math.isfinite(y):
                finite_count += 1
        print(f"Shape {shape_name}: {finite_count}/{clamped_length} finite samples")
        assert finite_count == clamped_length, f"All samples should be finite for {shape_name}"
    print("Verification 6 PASSED: 32 finite samples for all 4 shapes\n")

    # Verification 7: xRange, yRange are non-degenerate
    samples = []
    for i in range(clamped_length):
        t = (2 * math.pi) * i / max(1, clamped_length - 1)
        samples.append(heptacontanennegon(t, a))
    x_min = min(p[0] for p in samples)
    x_max = max(p[0] for p in samples)
    y_min = min(p[1] for p in samples)
    y_max = max(p[1] for p in samples)
    x_range = max(0.01, x_max - x_min)
    y_range = max(0.01, y_max - y_min)
    print(f"x range: [{x_min:.4f}, {x_max:.4f}], xRange = {x_range:.4f}")
    print(f"y range: [{y_min:.4f}, {y_max:.4f}], yRange = {y_range:.4f}")
    assert x_range > 0.01
    assert y_range > 0.01
    print("Verification 7 PASSED: non-degenerate x/y ranges\n")

    print("All Day 830 verifications PASSED.")
    print(f"79-cusped hypocycloid (heptacontanennegon) verified:")
    print(f"  parametric: x = a*cos(t) + (a/78)*cos(78t), y = a*sin(t) - (a/78)*sin(78t)")
    print(f"  R/r = 79, 79 cusps per revolution, ~{cusp_interval:.4f} degrees per cusp")
    print(f"  x at t=0 = {x0:.6f} = 79a/78")


if __name__ == '__main__':
    main()