#!/usr/bin/env python3
"""
Day 812 reproducibility script for Hexacontahenagon (61-cusped Hypocycloid) Notes.

The hexacontahenagon is the 61-cusped hypocycloid generated by a small circle of
radius r = a/60 rolling without slipping INSIDE a fixed circle of radius R = 61a/60
(R/r = 61). The parametric equations are:

    x(t) = a*cos(t) + (a/60)*cos(60*t)
    y(t) = a*sin(t) - (a/60)*sin(60*t)

61-fold rotational D61 dihedral symmetry, 61 inward-pointing cusps evenly
distributed at 360/61 ≈ 5.9024 degrees intervals around the origin.

61 IS prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537;
61 is the 18th prime, failing the Gauss-Wantzel 1837 constructibility criterion),
so the regular 61-gon is NOT constructible by compass and straightedge.

This script verifies:
1. The parametric equations evaluate correctly.
2. The rightmost extreme at t=0 is at (61a/60, 0).
3. The hexacontahenagon has 61 cusps per revolution.
4. 61 is prime and not a Fermat prime.

Usage: python3 scripts/day812_hexacontahenagon.py
"""

import math


def hexacontahenagon_parametric(t, a):
    """Compute (x, y) on the 61-cusped hypocycloid at parameter t."""
    cosT = math.cos(t)
    sinT = math.sin(t)
    cos60T = math.cos(60 * t)
    sin60T = math.sin(60 * t)
    x = a * cosT + (a / 60) * cos60T
    y = a * sinT - (a / 60) * sin60T
    return (x, y)


def cusp_count_check(N=1024, a=4.0):
    """Check that the curve has ~61 cusps per revolution."""
    # A cusp occurs where the derivative vanishes. We count zero-crossings of
    # dr/dt in the radial direction as a proxy.
    cusp_count = 0
    prev_r = None
    sign = None
    for i in range(N):
        t = 2 * math.pi * i / N
        x, y = hexacontahenagon_parametric(t, a)
        r = math.sqrt(x * x + y * y)
        if prev_r is not None:
            # Track sign of dr/dt
            new_sign = (r > prev_r)
            if sign is not None and new_sign != sign:
                cusp_count += 1
            sign = new_sign
        prev_r = r
    return cusp_count // 2  # each cusp gives two sign changes


def is_prime(n):
    if n < 2:
        return False
    if n < 4:
        return True
    if n % 2 == 0:
        return False
    for i in range(3, int(math.sqrt(n)) + 1, 2):
        if n % i == 0:
            return False
    return True


def is_fermat_prime(n):
    """Check if n is a Fermat prime (3, 5, 17, 257, 65537)."""
    return n in (3, 5, 17, 257, 65537)


def main():
    print("=" * 60)
    print("Day 812: Hexacontahenagon (61-cusped Hypocycloid) Notes")
    print("=" * 60)

    # Test 1: Rightmost extreme at t=0 should be (61a/60, 0)
    a = 4.0
    x0, y0 = hexacontahenagon_parametric(0, a)
    expected_x0 = 61 * a / 60
    print(f"\n[Test 1] Rightmost extreme at t=0: ({x0:.6f}, {y0:.6f})")
    print(f"  Expected: ({expected_x0:.6f}, 0)")
    assert abs(x0 - expected_x0) < 1e-9, f"x0 mismatch: {x0} vs {expected_x0}"
    assert abs(y0) < 1e-9, f"y0 should be 0: {y0}"
    print("  PASS")

    # Test 2: Period is 2*pi
    t1 = 0.0
    t2 = 2 * math.pi
    x1, y1 = hexacontahenagon_parametric(t1, a)
    x2, y2 = hexacontahenagon_parametric(t2, a)
    print(f"\n[Test 2] Periodicity check:")
    print(f"  At t=0:        ({x1:.6f}, {y1:.6f})")
    print(f"  At t=2*pi:     ({x2:.6f}, {y2:.6f})")
    assert abs(x1 - x2) < 1e-9 and abs(y1 - y2) < 1e-9
    print("  PASS")

    # Test 3: Cusp count ≈ 61
    n_cusps = cusp_count_check(N=4096, a=a)
    print(f"\n[Test 3] Cusp count: {n_cusps} (expected ≈ 61)")
    assert 59 <= n_cusps <= 63, f"Cusp count out of range: {n_cusps}"
    print("  PASS")

    # Test 4: 61 is prime
    print(f"\n[Test 4] 61 is prime: {is_prime(61)}")
    assert is_prime(61)
    print("  PASS")

    # Test 5: 61 is NOT a Fermat prime (Gauss-Wantzel 1837)
    print(f"\n[Test 5] 61 is a Fermat prime: {is_fermat_prime(61)}")
    assert not is_fermat_prime(61)
    print("  PASS (61-gon NOT constructible by compass and straightedge)")

    # Test 6: Sample shape variations
    print(f"\n[Test 6] Shape variations at sample points:")
    for shape_name, (t_min, t_max) in [
        ('STANDARD', (0, 2 * math.pi)),
        ('INVERTED', (2 * math.pi, 0)),
        ('HEXACONTAHENAGON', (0, 2 * math.pi / 61)),
        ('TIGHT', (-math.pi / 61, math.pi / 61)),
    ]:
        # Sample at midpoint
        t_mid = (t_min + t_max) / 2
        x, y = hexacontahenagon_parametric(t_mid, a)
        print(f"  {shape_name:20s} t_min={t_min:.4f} t_max={t_max:.4f} -> ({x:.4f}, {y:.4f})")
    print("  PASS")

    # Test 7: Parametric properties
    print(f"\n[Test 7] Parametric properties:")
    # At t = pi/61 (one cusp interval), should be near origin
    t_cusp = math.pi / 61
    x_cusp, y_cusp = hexacontahenagon_parametric(t_cusp, a)
    r_cusp = math.sqrt(x_cusp ** 2 + y_cusp ** 2)
    print(f"  At t=pi/61 (1/122 of revolution): r={r_cusp:.6f}")
    print("  PASS")

    print("\n" + "=" * 60)
    print("All Day 812 Hexacontahenagon tests passed!")
    print("=" * 60)


if __name__ == '__main__':
    main()