#!/usr/bin/env python3
"""Day 803: Pentacontadigon (52-cusped Hypocycloid) reproducibility script.

Generates a 52-cusped hypocycloid curve using the standard parametric form:
  x(t) = a*cos(t) + (a/51)*cos(51*t)
  y(t) = a*sin(t) - (a/51)*sin(51*t)

The pentacontadigon is the 52-cusped hypocycloid (also called the 52-pointed-star
hypocycloid), generated by a small circle of radius r=a/51 rolling inside a fixed
circle of radius R=52a/51. It has 52-fold D52 dihedral symmetry, 52 inward-pointing
cusps at 360/52 = 6.923 degree intervals, and (since 52 = 2^2 * 13 with 13 not a
Fermat prime) is NOT constructible by compass and straightedge (Gauss-Wantzel 1837).

This is the natural 52-cusped extension of the 1-2-3-...-50-51-52 cusp hypocycloid
sequence started on Day 740 (cardioid) and continued through Day 802 (pentacontahenagon).
"""

import math


def pentacontadigon_point(t, a):
    """Compute (x, y) on the pentacontadigon curve at parameter t with scale a."""
    a_over_51 = a / 51.0
    cos_t = math.cos(t)
    sin_t = math.sin(t)
    cos_51t = math.cos(51.0 * t)
    sin_51t = math.sin(51.0 * t)
    x = a * cos_t + a_over_51 * cos_51t
    y = a * sin_t - a_over_51 * sin_51t
    return x, y


def main():
    a = 4.0  # scale (default in PENTACONTADIGON_NOTES_DEFAULT_A)
    num_samples = 32  # clampedLength (default in PENTACONTADIGON_NOTES_DEFAULT_LENGTH)

    print("Day 803: Pentacontadigon (52-cusped Hypocycloid) Notes")
    print("=" * 60)
    print(f"a = {a}, num_samples = {num_samples}")
    print(f"Parametric: x = a*cos(t) + (a/51)*cos(51t), y = a*sin(t) - (a/51)*sin(51t)")
    print()
    print(f"{'i':>4} {'t':>10} {'x':>12} {'y':>12}")
    print("-" * 42)

    for i in range(num_samples):
        t = 2.0 * math.pi * i / max(1, num_samples - 1)
        x, y = pentacontadigon_point(t, a)
        if math.isfinite(x) and math.isfinite(y):
            print(f"{i:4d} {t:10.5f} {x:12.6f} {y:12.6f}")

    print()
    print(f"Number of cusps: 52 (= R/r)")
    print(f"Cusp interval: 360/52 = {360.0/52.0:.4f} degrees")
    print(f"52 = 2^2 * 13; 13 is prime but NOT Fermat -> NOT constructible")


if __name__ == "__main__":
    main()
