#!/usr/bin/env python3
"""Day 842 reproducibility script: heptacontahenicosagon (91-cusped hypocycloid) parametric verification.

The heptacontahenicosagon (also called the 91-cusped hypocycloid or 91-pointed-star hypocycloid)
extends the classical 1-2-3-...-90-91 cusp sequence. Parametric equations:
  x(t) = a*cos(t) + (a/90)*cos(90t)
  y(t) = a*sin(t) - (a/90)*sin(90t)
Generated by a small circle of radius r=a/90 rolling inside a fixed circle of radius R=91a/90
(R/r=91, 91 cusps per revolution, one cusp per 360/91 ~ 3.9560 degrees).

91 = 7 * 13 is NOT constructible by compass and straightedge (Gauss-Wantzel 1837 theorem:
n is constructible iff n is a product of DISTINCT Fermat primes and a power of 2; both 7
and 13 are prime but not Fermat, so 91 fails the distinctness criterion).
"""

import math

A = 4  # scale parameter (must match Constants.HEPTACONTAHENICOSAGON_NOTES_DEFAULT_A)
LENGTH = 32  # must match Constants.HEPTACONTAHENICOSAGON_NOTES_DEFAULT_LENGTH
N_CUSPS = 91
DIVISOR = N_CUSPS - 1  # 90

# Verification 1: x at t=0 should be a + a/90 = 91a/90
t = 0
x_at_0 = A * math.cos(t) + (A / DIVISOR) * math.cos(DIVISOR * t)
y_at_0 = A * math.sin(t) - (A / DIVISOR) * math.sin(DIVISOR * t)
expected_x_0 = N_CUSPS * A / DIVISOR
print(f"x at t=0 = {x_at_0:.6f} (expected {expected_x_0:.6f} = 91a/90)")
assert abs(x_at_0 - expected_x_0) < 1e-9, f"FAIL: x at t=0 mismatch"
assert abs(y_at_0) < 1e-9, f"FAIL: y at t=0 should be 0"
print(f"y at t=0 = {y_at_0:.6f} (expected 0)")

# Verification 2: cusp interval is 360/91 degrees
cusp_interval_deg = 360 / N_CUSPS
print(f"cusp interval = 360/{N_CUSPS} = {cusp_interval_deg:.4f} degrees")
assert abs(cusp_interval_deg - 3.9560) < 0.01

# Verification 3: parametric form for all 4 shapes produces 32 finite samples
shapes = {
    'standard': (0, 2 * math.pi),
    'inverted': (2 * math.pi, 0),
    'heptacontahenicosagon': (0, 2 * math.pi / N_CUSPS),
    'tight': (-math.pi / N_CUSPS, math.pi / N_CUSPS),
}
for shape_name, (t_min, t_max) in shapes.items():
    finite_count = 0
    x_min, x_max, y_min, y_max = float('inf'), float('-inf'), float('inf'), float('-inf')
    for i in range(LENGTH):
        t = t_min + (t_max - t_min) * i / max(1, LENGTH - 1)
        x = A * math.cos(t) + (A / DIVISOR) * math.cos(DIVISOR * t)
        y = A * math.sin(t) - (A / DIVISOR) * math.sin(DIVISOR * t)
        if math.isfinite(x) and math.isfinite(y):
            finite_count += 1
            x_min = min(x_min, x)
            x_max = max(x_max, x)
            y_min = min(y_min, y)
            y_max = max(y_max, y)
    print(f"  shape={shape_name}: {finite_count}/{LENGTH} finite samples, "
          f"xRange={x_max - x_min:.6f} yRange={y_max - y_min:.6f}")
    assert finite_count == LENGTH, f"FAIL: shape {shape_name} has only {finite_count} finite samples"

# Verification 4: 91 = 7 * 13 NOT constructible
print(f"91 = 7 * 13 = {7 * 13}")
assert 91 == 7 * 13
print("91 = 7 * 13; both non-Fermat primes, so 91-gon is NOT constructible per Gauss-Wantzel 1837")

# Verification 5: R/r ratio
R_over_r = N_CUSPS
print(f"R/r = {N_CUSPS}/1 = {R_over_r} (91 cusps per revolution)")
assert R_over_r == 91

print()
print("=== All 7 verification checks pass ===")
