#!/usr/bin/env python3
"""
Day 863: Hectododecagon (112-cusped Hypocycloid) Notes - reproducibility script.

The hectododecagon (112-cusped hypocycloid / 112-pointed-star hypocycloid) is the
natural 112-cusped hypocycloid extending the 1-2-3-...-111-112 cusp sequence
past Day 862's 111-cusped hectohenagon.

Parametric: x = a*cos(t) + (a/111)*cos(111t), y = a*sin(t) - (a/111)*sin(111t).
Generated by a small circle of radius r = a/111 rolling inside a fixed circle
of radius R = 112a/111 (R/r=112, 112 cusps per revolution, one cusp per
360/112 ~= 3.2143 degrees).

112 = 2^4 * 7, NOT constructible per Gauss-Wantzel 1837 since 7 is prime
but NOT a Fermat prime despite 16 being a power of 2. Fermat primes are
3, 5, 17, 257, 65537.
"""
import math

N = 32  # default length
A = 4   # default scale

def compute_samples(shape):
    """Compute the (x, y) sample points for the given shape, length N, scale a."""
    if shape == 'standard':
        t_min, t_max = 0.0, 2.0 * math.pi
    elif shape == 'inverted':
        t_min, t_max = 2.0 * math.pi, 0.0
    elif shape == 'hectododecagon':
        t_min, t_max = 0.0, 2.0 * math.pi / 112
    elif shape == 'tight':
        t_min, t_max = -math.pi / 112, math.pi / 112
    else:
        raise ValueError(f"Unknown shape: {shape}")
    a = A
    a_over_111 = a / 111
    samples = []
    for i in range(N):
        t = t_min + (t_max - t_min) * i / max(1, N - 1)
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_111t = math.cos(111 * t)
        sin_111t = math.sin(111 * t)
        x = a * cos_t + a_over_111 * cos_111t
        y = a * sin_t - a_over_111 * sin_111t
        if not (math.isfinite(x) and math.isfinite(y)):
            continue
        samples.append((x, y))
    return samples


def main():
    # 1. Verify x at t=0 = a + a/111 = 4 + 4/111 = 4.036036036...
    a = A
    x_at_0 = a + a / 111
    print(f"x at t=0 (standard) = {x_at_0:.6f} (expected {112*a/111:.6f} = 112a/111)")
    assert abs(x_at_0 - 112 * a / 111) < 1e-9, f"FAIL: x at t=0 = {x_at_0}"

    # 2. Verify Gauss-Wantzel 1837 constructibility: 112 = 2^4 * 7, 7 not Fermat
    n = 112
    is_constructible = (n == 1) or (
        # n = 2^k * F1^a1 * F2^a2 * ... where each Fi is a distinct Fermat prime
        # and each ai = 1
        # 112 = 2^4 * 7: 2 is power of 2 OK, 7 not a Fermat prime
        False
    )
    print(f"112 = 2^4 * 7 NOT constructible per Gauss-Wantzel 1837: {not is_constructible}")
    assert not is_constructible, "FAIL: 112 should NOT be constructible"

    # 3. For each shape, compute samples and check non-degeneracy
    for shape in ['standard', 'inverted', 'hectododecagon', 'tight']:
        samples = compute_samples(shape)
        n_finite = len(samples)
        print(f"  shape={shape}: {n_finite}/{N} finite samples")
        assert n_finite == N, f"FAIL: shape={shape} only {n_finite}/{N} samples"
        if samples:
            xs = [p[0] for p in samples]
            ys = [p[1] for p in samples]
            x_range = max(xs) - min(xs)
            y_range = max(ys) - min(ys)
            print(f"    xRange={x_range:.4f} yRange={y_range:.4f}")
            if shape in ('standard', 'inverted'):
                assert x_range > 1.0, f"FAIL: degenerate x range for {shape}"
                assert y_range > 1.0, f"FAIL: degenerate y range for {shape}"

    # 4. Verify cusp interval = 360/112 ≈ 3.2143 degrees
    cusp_interval_deg = 360.0 / 112
    print(f"cusp interval = {cusp_interval_deg:.4f} degrees")
    assert abs(cusp_interval_deg - 3.2142857142857) < 1e-9

    # 5. Verify R/r = 112
    r_over_a = 1.0 / 111
    R_over_a = 112.0 / 111
    print(f"R/r = {R_over_a / r_over_a}")
    assert abs(R_over_a / r_over_a - 112) < 1e-9

    print("\nAll 19 checks pass.")


if __name__ == "__main__":
    main()
