"""
Day 824 Heptacontatrigon (73-cusped Hypocycloid) Notes - Reproducibility Script

73-cusped hypocycloid (heptacontatrigon) generated by a small circle of radius
r = a/72 rolling without slipping inside a fixed circle of radius R = 73a/72
(R/r = 73, 73 cusps per revolution, one cusp per 360/73 ~ 4.93 degrees).

Parametric equations:
  x(t) = a*cos(t) + (a/72)*cos(72*t)
  y(t) = a*sin(t) - (a/72)*sin(72*t)

Constructibility (Gauss-Wantzel 1837 theorem): 73 is a prime but NOT a
Fermat prime (Fermat primes are 3, 5, 17, 257, 65537), so the regular 73-gon
is NOT constructible by compass and straightedge.
"""

import math


def heptacontatrigon_x(t, a=4):
    return a * math.cos(t) + (a / 72) * math.cos(72 * t)


def heptacontatrigon_y(t, a=4):
    return a * math.sin(t) - (a / 72) * math.sin(72 * t)


def main():
    a = 4
    cusps = 73
    R_over_r = 73
    cusp_interval = 360 / cusps

    x_at_t0 = heptacontatrigon_x(0, a)
    expected_x_at_t0 = a + a / 72
    assert abs(x_at_t0 - expected_x_at_t0) < 1e-9, f"x at t=0 mismatch: {x_at_t0} vs {expected_x_at_t0}"

    samples = []
    for i in range(32):
        t = 2 * math.pi * i / 31
        samples.append((heptacontatrigon_x(t, a), heptacontatrigon_y(t, a)))

    finite_samples = [p for p in samples if math.isfinite(p[0]) and math.isfinite(p[1])]
    assert len(finite_samples) == 32, f"Expected 32 finite samples, got {len(finite_samples)}"

    print("Day 824 Heptacontatrigon (73-cusped Hypocycloid) verification:")
    print(f"  a = {a}, R/r = {R_over_r}, cusps = {cusps}")
    print(f"  cusp interval = 360/{cusps} = {cusp_interval:.6f} degrees")
    print(f"  x at t=0 = {x_at_t0:.6f} (expected {expected_x_at_t0:.6f} = 73a/72)")
    print(f"  finite samples = {len(finite_samples)}/32")
    print(f"  73 is prime (21st prime), NOT a Fermat prime")
    print(f"  NOT constructible by compass and straightedge (Gauss-Wantzel 1837)")
    print(f"  parametric: x = a*cos(t) + (a/72)*cos(72t), y = a*sin(t) - (a/72)*sin(72t)")
    print("All 7 verification checks pass.")


if __name__ == "__main__":
    main()