#!/usr/bin/env python3
"""
Day 802: Pentacontahenagon (51-cusped Hypocycloid) - Reproducibility Script

This script renders the pentacontahenagon (51-cusped hypocycloid) curve for visual inspection.

Parametric equations (SnugOS Day 802):
  x(t) = a*cos(t) + (a/50)*cos(50*t)
  y(t) = a*sin(t) - (a/50)*sin(50*t)

Generated by a small circle of radius r = a/50 rolling without slipping inside a fixed circle
of radius R = 51a/50 (R/r = 51, 51 cusps per revolution).

The pentacontahenagon has 51-fold rotational symmetry (D51 dihedral symmetry) with 51 inward-pointing
cusps evenly distributed at 360°/51 ~ 7.059° intervals around the origin.

51 = 3 * 17. Both 3 and 17 are Fermat primes (2^(2^0)+1 = 3, 2^(2^2)+1 = 17), so 51 IS constructible
by compass and straightedge (Gauss-Wantzel 1837 theorem).
"""

import math
import sys

try:
    import matplotlib.pyplot as plt
    HAS_MPL = True
except ImportError:
    HAS_MPL = False


def render_pentacontahenagon(a=4.0, num_samples=512, filename="/tmp/pentacontahenagon_day802.png"):
    """Render the pentacontahenagon (51-cusped hypocycloid) curve and save to PNG."""
    samples = []
    for i in range(num_samples):
        t = 2.0 * math.pi * i / num_samples
        cos_t = math.cos(t)
        sin_t = math.sin(t)
        cos_50t = math.cos(50 * t)
        sin_50t = math.sin(50 * t)
        x = a * cos_t + (a / 50.0) * cos_50t
        y = a * sin_t - (a / 50.0) * sin_50t
        samples.append((x, y))

    if not HAS_MPL:
        print(f"matplotlib not available; would have written {len(samples)} samples to {filename}")
        return None

    xs = [p[0] for p in samples]
    ys = [p[1] for p in samples]
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.plot(xs, ys, '-', linewidth=0.8, color='#d8a657')
    ax.set_aspect('equal')
    ax.set_title('Day 802: Pentacontahenagon (51-cusped Hypocycloid)\n'
                 r'$x = a\cos(t) + (a/50)\cos(50t),\ y = a\sin(t) - (a/50)\sin(50t)$')
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(filename, dpi=120)
    plt.close(fig)
    return filename


if __name__ == "__main__":
    out = render_pentacontahenagon()
    if out:
        print(f"Wrote {out}")
    else:
        print("Skipped render (no matplotlib)")
        sys.exit(0)