#!/usr/bin/env python3
"""
Day 883 reproducibility script for the Hectoduotriacontagon (132-cusped Hypocycloid) Notes feature.

Verifies the parametric formula:
  x(t) = a*cos(t) + (a/131)*cos(131t)
  y(t) = a*sin(t) - (a/131)*sin(131t)

132 = 100 + 32 = hecto-100 + duo-2 + triaconta-30 (hectoduotriacontagon = 132 sides).
R/r = 132, generated by a small circle of radius r = a/131 rolling inside
a fixed circle of radius R = 132a/131. 132 cusps per revolution, one cusp
per 360°/132 = 2.7272...° = 2*PI/132 of revolution.

132 = 2² × 3 × 11. 4 is a power of 2 and 3 IS a Fermat prime, but 11 is
prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537).
So 132 is NOT constructible per Gauss-Wantzel 1837.
"""
import math

N = 132  # number of cusps
A = 4  # scale parameter
R_OVER_R = N  # 132 cusps per revolution
A_OVER_R_FACTOR = N - 1  # 131

x_at_zero = A + A / A_OVER_R_FACTOR
y_at_zero = 0
t_max = 2 * math.pi / N  # T_MAX
tight_t_max = math.pi / N  # TIGHT_T_MAX
print(f"x at t=0 = {x_at_zero:.6f} = {N}a/{A_OVER_R_FACTOR} (expected {N}*{A}/{A_OVER_R_FACTOR} = {N*A/A_OVER_R_FACTOR:.6f})")
print(f"HECTODUOTRIACONTAGON_NOTES_HECTODUOTRIACONTAGON_T_MAX = 2*PI/{N} = {t_max:.6f}")
print(f"HECTODUOTRIACONTAGON_NOTES_TIGHT_T_MAX = PI/{N} = {tight_t_max:.6f}")

shapes = ['standard', 'inverted', 'hectoduotriacontagon', 'tight']
for shape in shapes:
    finite_count = 0
    for i in range(32):
        t = t_max * i / max(1, 31)
        cosT = math.cos(t)
        sinT = math.sin(t)
        cos131T = math.cos(131 * t)
        sin131T = math.sin(131 * t)
        x = A * cosT + (A / 131) * cos131T
        y = A * sinT - (A / 131) * sin131T
        if math.isfinite(x) and math.isfinite(y):
            finite_count += 1
    print(f"  Shape {shape}: {finite_count}/32 finite samples for 32-sided sample sweep")

# Verify the cusp interval
cusp_deg = 360.0 / N
print(f"\nCusp interval: 360/{N} = {cusp_deg:.4f}° = 2*PI/{N} = {2*math.pi/N:.6f} rad")

# Check constructibility
print(f"\n132 = 2² × 3 × 11")
print(f"2² is a power of 2: YES (constructible criterion pass)")
print(f"3 IS a Fermat prime: YES (constructible criterion pass)")
print(f"11 is prime but NOT a Fermat prime (Fermat primes are 3, 5, 17, 257, 65537): FAILS")
print(f"Therefore 132 is NOT constructible per Gauss-Wantzel 1837")
print(f"R/r ratio: 132 (R = 132a/131, r = a/131)")

# Sweep t from 0 to T_MAX and report non-degenerate x/y range
xs, ys = [], []
for i in range(64):
    t = t_max * i / 63
    cosT = math.cos(t)
    sinT = math.sin(t)
    cos131T = math.cos(131 * t)
    sin131T = math.sin(131 * t)
    x = A * cosT + (A / 131) * cos131T
    y = A * sinT - (A / 131) * sin131T
    if math.isfinite(x) and math.isfinite(y):
        xs.append(x)
        ys.append(y)
if xs:
    print(f"\n64-sample sweep x range: [{min(xs):.4f}, {max(xs):.4f}]")
    print(f"64-sample sweep y range: [{min(ys):.4f}, {max(ys):.4f}]")
