#!/usr/bin/env python3
"""
Day 862: Hectohenagon (111-cusped Hypocycloid) Notes - reproducibility script.

The hectohenagon (111-cusped hypocycloid / 111-pointed-star hypocycloid) is the
natural 111-cusped hypocycloid extending the 1-2-3-...-110-111 cusp sequence
past Day 861's 110-cusped hectodecagon.

Parametric: x = a*cos(t) + (a/110)*cos(110t), y = a*sin(t) - (a/110)*sin(110t).
Generated by a small circle of radius r = a/110 rolling inside a fixed circle
of radius R = 111a/110 (R/r=111, 111 cusps per revolution, one cusp per
360/111 ~= 3.2432 degrees).

111 = 3 * 37, NOT constructible per Gauss-Wantzel 1837 since 37 is prime
but NOT a Fermat prime despite 3 being a Fermat prime. Fermat primes are
3, 5, 17, 257, 65537.
"""
import math

N = 32  # default length
A = 4   # default scale

def compute_samples(shape):
    """Compute the (x, y) sample points for the given shape, length N, scale a."""
    if shape == 'standard':
        t_min, t_max = 0, 2 * math.pi
    elif shape == 'inverted':
        t_min, t_max = 2 * math.pi, 0
    elif shape == 'hectohenagon':
        t_min, t_max = 0, 2 * math.pi / 111
    elif shape == 'tight':
        t_min, t_max = -math.pi / 111, math.pi / 111
    else:
        raise ValueError(f"Unknown shape: {shape}")
    a = A
    a_over_110 = a / 110
    samples = []
    for i in range(N):
        t = t_min + (t_max - t_min) * i / max(1, N - 1)
        x = a * math.cos(t) + a_over_110 * math.cos(110 * t)
        y = a * math.sin(t) - a_over_110 * math.sin(110 * t)
        if math.isfinite(x) and math.isfinite(y):
            samples.append((x, y))
    return samples

def xyrange(samples):
    if not samples:
        return (0, 0, 0, 0)
    xs = [p[0] for p in samples]
    ys = [p[1] for p in samples]
    return (min(xs), max(xs), min(ys), max(ys))

print("Day 862: Hectohenagon (111-cusped Hypocycloid) Notes")
print("=" * 60)
print(f"Parametric: x = a*cos(t) + (a/110)*cos(110t), y = a*sin(t) - (a/110)*sin(110t)")
print(f"R/r = 111, ~3.2432 degree cusp intervals")
print(f"111 = 3 * 37, NOT constructible per Gauss-Wantzel 1837")
print(f"(37 is prime but NOT a Fermat prime despite 3 being a Fermat prime)")
print()

for shape in ('standard', 'inverted', 'hectohenagon', 'tight'):
    samples = compute_samples(shape)
    xmin, xmax, ymin, ymax = xyrange(samples)
    print(f"Shape: {shape:14s}  samples={len(samples):2d}  x in [{xmin:+.4f}, {xmax:+.4f}]  y in [{ymin:+.4f}, {ymax:+.4f}]")

print()
print("Sample point at t=0 (standard shape):")
samples = compute_samples('standard')
x0, y0 = samples[0]
print(f"  x(0) = a*cos(0) + (a/110)*cos(0) = a + a/110 = a*(1 + 1/110) = a*111/110 = {x0:.6f}")
print(f"  Expected: 111a/110 = {111*A/110:.6f} (4*111/110 = {4*111/110:.6f})")
assert abs(x0 - 111 * A / 110) < 1e-10, "x(0) mismatch"
print(f"  y(0) = a*sin(0) - (a/110)*sin(0) = 0 - 0 = 0 (expected 0)")
print()

print("Number-theoretic facts:")
print(f"  111 = 3 * 37 (semiprime, NOT constructible per Gauss-Wantzel 1837)")
print(f"  111 = 100 + 11 (hecto + 11 sides, named hectohenagon)")
print(f"  111 IS the 30th sphenic number? No, 111 = 3*37 has only 2 primes, so semiprime")
print(f"  111 IS the 37th sphenic-adjacent semiprime (3*p where p is the 12th prime 37)")
print(f"  R/r = 111 = 111a/110 : (a/110) = 111, so 111 cusps per revolution")
print(f"  360/111 = {360/111:.6f} degrees per cusp")
